### ISSUE TITLE
How do I install on Windows?

### ISSUE THREAD

**Issue by saberking** [jhen0409/react-native-debugger#10]
I downloaded the zip but could not find out what to do next. Please could you explain it? Thanks a bundle

**Comment by jhen0409** [comment]
You should can be found `React Native Debugger.exe` in `rn-debugger-win32.zip` (It doesn't require installation), see [the usage of README](https://github.com/jhen0409/react-native-debugger#usage).

**Comment by saberking** [comment]
Ok i downloaded the x64 version, couldnt find anything in there. Thanks :)

**Comment by afilp** [comment]
@jhen0409 May I assume that Windows is not supported? Where can I find this EXE file? Thanks!
