### ISSUE TITLE
Uploading images broken when using Network inspector

### ISSUE THREAD

**Issue by mateoKaradza** [jhen0409/react-native-debugger#101]
I noticed a bug when I want to upload images while Network Inspector is active in RN Debugger application. The upload just doesn't work - images are not reaching the API endpoint.

I tried to upgrade RN (was on 0.42.3), didn't help. Started using `whatwg-fetch` instead of native `fetch`, didn't help.
I actually thought that something was broken with one of my modules (I use `react-native-image-picker`) and spent few hours upgrading everything, reverting to older versions, nothing helped. 

Here is an example of image object, which is appended to FormData
````
let photo = {
      'uri': image.uri,
      'type': image.type,
      'name': image.fileName
    }

let data = new FormData()
data.append('photo', photo)
````

Started using this tool several days ago, great piece of work guys!

React Native Debugger version: 0.7.1
React Native version: 0.45.1, exists in older versions too
Platform: both Android and iOS
Is real device of platform: yes
Operating System: macOs

**Comment by jhen0409** [comment]
I've mentioned it in https://github.com/jhen0409/react-native-debugger/issues/38#issuecomment-312419961, it's limitation for use Network Inspect.

**Comment by mateoKaradza** [comment]
@jhen0409 oh, thanks for clarification, I did go through the issues but couldn't find it, seems like I wasn't looking hard enough.

Closing.
