### ISSUE TITLE
"Waiting for React to connect..." 

### ISSUE THREAD

**Issue by NathHorrigan** [jhen0409/react-native-debugger#105]
React Native Debugger version:  0.6.0 because latest version crashes on load
React Native version: react-native@0.46.0
Platform: Android
Is real device of platform: Yes
Operating System: macOS 10.12.1

React and Redux inspectors don't attach to React-Native instance

**Comment by jhen0409** [comment]
Could you provide details about `latest version crashes on load` in another issue?

For this issue you can read [`How to use it with real device?`](https://github.com/jhen0409/react-native-debugger/blob/master/docs/react-devtools-integration.md#how-to-use-it-with-real-device) section, or if you're debug via USB, you can just run `adb reverse tcp:8097 tcp:8097` ([`v0.6.2`](https://github.com/jhen0409/react-native-debugger/releases/tag/v0.6.2) should run it automatically).

**Comment by NathHorrigan** [comment]
so running `adb reverse tcp:8097 tcp:8097` fixed the issue, Thanks!

**Comment by NathHorrigan** [comment]
Crashing error is identical to #81

**Comment by sunihegde** [comment]
> so running `adb reverse tcp:8097 tcp:8097` fixed the issue, Thanks!

after running adb reverse tcp:8097 tcp:8097 
getting error: closed but  bundler is not starting.

**Comment by Naser2** [comment]
On real device:  Shake device & Click "Debug Remote JS". 
On Simulator: Try: Cmd or control + D on the Simulator & Click "Debug Remote JS".

**Comment by DerekLiang** [comment]
```
adb tcpip 5555
adb reverse tcp:8097 tcp:8097
```
works for me.
