### ISSUE TITLE
OSX code sign issues?

### ISSUE THREAD

**Issue by chrisnojima** [jhen0409/react-native-debugger#107]
React Native Debugger version: 0.7.2 / 0.7.1
React Native version: [FILL THIS OUT]
Platform: [FILL THIS OUT: iOS, Android, ...]
Is real device of platform: [Yes or No]
Operating System: OSX 10.12.5 (Sierra)

I was running 0.7.1 normally today then suddenly the debugger stopped working. I get this dialog: 
![image](https://user-images.githubusercontent.com/516435/28086616-9df75cb2-664d-11e7-923b-c518b9bb0fbf.png)

When I try and run 0.7.2 I get this error
![image](https://user-images.githubusercontent.com/516435/28086652-b9ff5590-664d-11e7-8b6e-6cec5ed05abe.png)

**Comment by jhen0409** [comment]
Sorry my fault, the package is damaged, I'll publish it again.

**Comment by jhen0409** [comment]
I uploaded [v0.7.2](https://github.com/jhen0409/react-native-debugger/releases/tag/v0.7.2) again, please checkout for that. :)
