### ISSUE TITLE
Suggestion: Inspect AsyncStorage content

### ISSUE THREAD

**Issue by FredyC** [jhen0409/react-native-debugger#108]
I've just noticed the ability to clear AsyncStorage which is definitely very handy. It would be really nice to be able to see the content of it or at least being able to call its methods in a console. Is something like that planned or even possible?

Thanks for the tool, I've missed React devtools so much :)

**Comment by jhen0409** [comment]
I've wrote [a tip in debugger-integration.md](https://github.com/jhen0409/react-native-debugger/blob/master/docs/debugger-integration.md#use-requireprovidesmodule-in-the-console), you can just `require('AsyncStorage')` in the console. (`RNDebuggerWorker.js` context)

For the inspector UI, currently we have no plan to implement, but any contributions are welcome! If we want to do it, it should similar to #102, and we can get `AsyncStorage` in [debugger worker](https://github.com/jhen0409/react-native-debugger/blob/master/app/worker/devMenu.js#L34).
