### ISSUE TITLE
Settings to increase / decrease font size

### ISSUE THREAD

**Issue by chilijung** [jhen0409/react-native-debugger#109]
React Native Debugger version: latest
React Native version: latest
Operating System: MacOS

Is it possible to add features for increase or decrease fonts? Thanks.
The fonts in iMac 27-inch is rather small, tried `command + '+'` not working...

**Comment by jhen0409** [comment]
We could add this to application menu with Electron API, I'll implement this tomorrow.

**Comment by chilijung** [comment]
@jhen0409 thanks!!!

**Comment by tomernahum** [comment]
It doesn't work on firefox
