### ISSUE TITLE
Cannot find module 'remotedev-server'

### ISSUE THREAD

**Issue by sun2rise** [jhen0409/react-native-debugger#11]
My terminal window stucks with this message:
```bash
Cannot find module 'remotedev-server'
```

I think there is something i have to npm install on my project in order to use react-native-debugger as monitor, right? but what?

**Comment by jhen0409** [comment]
Should not need `remotedev-server` in your project, could you provide more messages?

**Comment by jhen0409** [comment]
Maybe you're used [`remotedev-debugger`](https://github.com/jhen0409/remote-redux-devtools-on-debugger) before, please run`$(npm bin)/remotedev-debugger --revert` to revert injected code.
