### ISSUE TITLE
Connecting to React...

### ISSUE THREAD

**Issue by FredyC** [jhen0409/react-native-debugger#110]
React Native Debugger version: 1.7.4
React Native version: 0.45.1
Platform: Android
Is real device of platform: Genymotion emulator
Operating System: Windows 10 x64

I've read the troubleshooting and the `react-devtools-core@2.4.0` installed. Strangely enough, it was working couple days ago, when I did not need it. Now I could use it and it's a fail :)

I tried to Reload debugger window, let it connect and then reload the app in the emulator. After a while, I see in the console error `failed to connect` coming directly from `react-devtools-core`. I also tried restarting whole system, did not help.

It is working correctly when using real Android device.

**Comment by jhen0409** [comment]
You can try all possible workarounds of #45 first (usually it cause by timers), but don't need to check requestIdleCallback problem because react-devtools-core@^2.3.0 will use polyfill for RN.

**Comment by FredyC** [comment]
Ok thanks, it's working now. Seems that `adb reverse tcp:8097 tcp:8097` did the trick, but I really don't understand how and why. Perhaps you can add it to troubleshooting as well :)

**Comment by jhen0409** [comment]
I don't think `adb reverse` related to this problem because we have already ran it on [RN debugger](https://github.com/jhen0409/react-native-debugger/blob/d41270cbf658dba3ccf30cdefa38f2016fbf6d7c/app/middlewares/debuggerAPI.js#L101), and it's unnecessary for Android emulator (See [setupDevtools.js](https://github.com/facebook/react-native/blob/master/Libraries/Core/Devtools/setupDevtools.js#L31)), but I'll explain the timer problem in troubleshooting.

**Comment by FredyC** [comment]
Interesting. I actually tried setting a date with adb as a first attempt, but that did not seem to have any effect. Then I tried the `reverse`, but I also restarted the simulator, so it possible that setting date actually solved it, but needed a restart. 🤷‍♂️

**Comment by BVasilev-zz** [comment]
For people still having this problem what worked for me was: 

1. Starting the simulator.
2. Closing the automatically opened Developer tools.
3. Opening the react-native-debugger.
----- At this point it usually doesn't work for me (Connecting to React issue..) -----
4. In the Debugger: 
**Debugger > New Window** 
5. Fill in your port (19001)

You are good to go!
That worked for me!

**Comment by GeorgyMalinovskiy** [comment]
Im getting "Uncaught ReferenceError: chrome is not defined" after [React DevTools] Connected, React DevTools pannel not working, redux works fine
