### ISSUE TITLE
"[RNDebugger] Try to set port of React Native server failed."

### ISSUE THREAD

**Issue by EzioKissshot** [jhen0409/react-native-debugger#111]
I'm using the latest version of react-native-debugger
 I have read README.md

React Native Debugger version: 0.7.3
React Native version: EXPO SDK 18.0.1
Platform: Android
Is real device of platform:No
Operating System:  Windows

I use
```
"scripts": {
  "postinstall": "rndebugger-open"
}
```
and run `npm run postinstall`, it shows `PASS Replace open debugger-ui with Chrome to open React Native Debugger.`

And I open app, everything is ok, but after I click `debug JS remotely`, Expo console show `[RNDebugger] Try to set port of React Native server failed.`, Android simulator show a white screen, react native debugger show `Connected(port 19002)` and have a error in console
`GET http://192.168.62.1:19002/node_modules/expo/AppEntry.bundle?platform=androi…&strict=false&minify=false&hot=false&assetPlugin=expo/tools/hashAssetFiles 502 (Read from server failed: Timeout)`

After long time, Android simulator turn to red screen, show a error which is Failed to execute 'importScripts' on 'WorkerGlobalScope': The Script at ' http://192.168.62.1:19002/node_modules/expo/AppEntry.bundle?platform=android&dev=true&strict=false&minify=false&hot=false&assetPlugin=expo/tools/hashAssetFiles' failed to load.

How to fix this `[RNDebugger] Try to set port of React Native server failed.`? It seems the setting port failed caused the problem.

**Comment by jhen0409** [comment]
It seems actually passed because you have been try to get bundle, the log is just my fault, I fixed it and released as `v0.3.12`. But I can't to help the problem of get bundle timeout, you should to check your RN packager.
