### ISSUE TITLE
not able to see network call in network tab 

### ISSUE THREAD

**Issue by somsin** [jhen0409/react-native-debugger#114]
not able to see network call in network tab ,
v0.7.3
<img width="1183" alt="screen shot 2017-08-03 at 12 22 19 pm" src="https://user-images.githubusercontent.com/4973590/28909644-ea029152-7846-11e7-8f53-1de806269ced.png">

<img width="993" alt="screen shot 2017-08-03 at 12 29 37 pm" src="https://user-images.githubusercontent.com/4973590/28909767-7703eeb6-7847-11e7-91f1-cccd38ade225.png">

**Comment by jhen0409** [comment]
It's disabled by default, have you enabled it in context menu or Touch bar? These should has been explained in [`docs/debugger-integration.md`](https://github.com/jhen0409/react-native-debugger/blob/master/docs/debugger-integration.md).

**Comment by jhen0409** [comment]
Feel free to reopen this if I misunderstood.

**Comment by DidYouKnow-Aston** [comment]
In the context menu, the option to enable or disable the network inspect is gone. Not sure if this happened after an update

**Comment by jhen0409** [comment]
@DidYouKnow-Aston what version are you using? Doesn't see the following the `Enable / Disable Network Inspect` item?

waiting:
<img width="214" alt="2017-08-24 9 41 33" src="https://user-images.githubusercontent.com/3001525/29669207-4dfd48b6-88a8-11e7-851e-b598d9739e7a.png">

debugging:
<img width="219" alt="2017-08-24 9 42 55" src="https://user-images.githubusercontent.com/3001525/29669206-4dfbf60a-88a8-11e7-9b9d-b491a74e30b3.png">

Note that you can't open the context menu in react component tree and chrome devtools.
