### ISSUE TITLE
How to install .zip in Linux

### ISSUE THREAD

**Issue by smezae** [jhen0409/react-native-debugger#116]
I downloaded the zip file, but i dont know how to install or run it, any help?

Operating System: Linux (Linux Mint)

**Comment by smezae** [comment]
I didn't realize that there was a executable file, sorry....thank you for this tool !!!

**Comment by likethemammal** [comment]
Wasnt clear to me either. For anyone else wondering, its the `React Native Debugger` executable file

**Comment by sanchit-8** [comment]
HOW RUN THE EXECUTABLE FILE IN UBUNTU?

**Comment by TechyTimo** [comment]
It doesnt run for me as well on Ubuntu

**Comment by fabriziobertoglio1987** [comment]
to install on Ubuntu you will need to:

1) download the latest [rn-debugger-linux-x64.zip from](https://github.com/jhen0409/react-native-debugger/releases)
2) unzip it and move the folder to `/opt`
```
cd ~/Downloads
sudo unzip rn-debugger-linux-x64.zip -d /opt/ReactNativeDebugger
```
3) preferably rename the executable 
```
cd /opt/ReactNativeDebugger 
sudo mv 'React Native Debugger' rndebugger
```
4) Add the folder which includes the `React Native Debugger` renamed executable to your path
```
vim ~/.bash_profile
export PATH="$PATH:/opt/ReactNativeDebugger"
```
5) Download the icon from the [repository](https://github.com/jhen0409/react-native-debugger/blob/master/dist/logo.png) and place it in your `/opt/ReactNativeDebugger` folder
```
sudo mv ~/Downloads/logo.png /opt/ReactNativeDebugger/logo.png
```
5) Create a desktop entry, so that you can pin react native debugger to your dock
```
vim ~/.local/share/applications/rndebugger.desktop
```
Include and edit the entry and save the file.
It is important that you replace Exec and Icon with the absolute path to the executable and logo files

```
[Desktop Entry]
Version=0.9.7
Type=Application
Name=ReactNativeDebugger
Exec=/opt/ReactNativeDebugger/rndebug
Icon=/opt/ReactNativeDebugger/logo.png
Categories=Development;IDE;
Terminal=false
StartupNotify=true
StartupWMClass=rndebugger
```

**Comment by amanboss9** [comment]
@fabriziobertoglio1987  Thanks !! I guess the Desktop Entry should have Exec as /opt/ReactNativeDebugger/rndebugger

**Comment by fabriziobertoglio1987** [comment]
@amanboss9  yes, you are right. Thanks !

**Comment by NikhilTomar15** [comment]
> to install on Ubuntu you will need to:
> 
> 1. download the latest [rn-debugger-linux-x64.zip from](https://github.com/jhen0409/react-native-debugger/releases)
> 2. unzip it and move the folder to `/opt`
> 
> ```
> cd ~/Downloads
> sudo unzip rn-debugger-linux-x64.zip -d /opt/ReactNativeDebugger
> ```
> 
> 1. preferably rename the executable
> 
> ```
> cd /opt/ReactNativeDebugger 
> sudo mv 'React Native Debugger' rndebugger
> ```
> 
> 1. Add the folder which includes the `React Native Debugger` renamed executable to your path
> 
> ```
> vim ~/.bash_profile
> export PATH="$PATH:/opt/ReactNativeDebugger"
> ```
> 
> 1. Download the icon from the [repository](https://github.com/jhen0409/react-native-debugger/blob/master/dist/logo.png) and place it in your `/opt/ReactNativeDebugger` folder
> 
> ```
> sudo mv ~/Downloads/logo.png /opt/ReactNativeDebugger/logo.png
> ```
> 
> 1. Create a desktop entry, so that you can pin react native debugger to your dock
> 
> ```
> vim ~/.local/share/applications/rndebugger.desktop
> ```
> 
> Include and edit the entry and save the file.
> It is important that you replace Exec and Icon with the absolute path to the executable and logo files
> 
> ```
> [Desktop Entry]
> Version=0.9.7
> Type=Application
> Name=ReactNativeDebugger
> Exec=/opt/ReactNativeDebugger/rndebugger
> Icon=/opt/ReactNativeDebugger/logo.png
> Categories=Development;IDE;
> Terminal=false
> StartupNotify=true
> StartupWMClass=rndebugger
> ```

I followed all the steps but it doesn't create any entry on my desktop and I am not able to start the debugger.

Please help me out.

Thanks in advance

**Comment by usama-asfar** [comment]
if the above doesn't work try 

```
Exec=/opt/ReactNativeDebugger/react-native-debugger
```
