### ISSUE TITLE
How should we edit setupDevtools?

### ISSUE THREAD

**Issue by jsdario** [jhen0409/react-native-debugger#12]
I have opened the file but don't know exactly which changes to perform in order to see the React hierarchy on the devtools.

I am developing on a real android device.

Thanks for your amazing work!

**Comment by jhen0409** [comment]
If you're debugging real device via USB, you can just run `adb reverse tcp:8097 tcp:8097` on your terminal. If you're debugging in LAN, you should edit `react-native/Libraries/Devtools/setupDevtools.js`:

```js
var ws = new window.WebSocket('ws://<your machine IP>:8097/devtools');
```

**Comment by grundmanise** [comment]
@jhen0409 could you please copy this `var ws = new window.WebSocket('ws://<your machine IP>:8097/devtools');` to the docs? :)

**Comment by jhen0409** [comment]
@grundmanise I updated the [readme](https://github.com/jhen0409/react-native-debugger#use-real-device), due to react-native changes I can't just copy the code.
