### ISSUE TITLE
Functional component doesn't get displayName

### ISSUE THREAD

**Issue by Noitidart** [jhen0409/react-native-debugger#124]
I actually am posting this from memory from last month.

If I export a functional component like this:

```
const Blah = <div />
export default Blah
```

Using this, the `displayName` is not shown in the inspector. I have do this:

```
function Blah() {
   return <div />
}
export default Blah
```

React Native Debugger version: [FILL THIS OUT]
React Native version: [FILL THIS OUT]
Platform: [FILL THIS OUT: iOS, Android, ...]
Is real device of platform: [Yes or No]
Operating System: [FILL THIS OUT: macOS, Linux, Windows]

Will update this topic later, really busy right now with the proper version numbers. But I thought it was simple enough to share the issue. It probably still is an issue, I ran into this just a couple weeks ago in end of July (new user here to rn debugger).

**Comment by jhen0409** [comment]
I don't think the returned element have `Blah` display name, or are you meaning `const Blah = () => <View />`?

You should report issue to [`react-devtools`](https://github.com/facebook/react-devtools) if you still have some problems about that, and don't forget to check [`react-devtools-core`](https://github.com/facebook/react-native/blob/master/package.json#L178) (backend) version in react-native.

If you want to downgrade `react-devtools` version of RNDebugger, you can checkout [release notes](https://github.com/jhen0409/react-native-debugger/releaseshttps://github.com/jhen0409/react-native-debugger/releases), it has some mention about `react-devtools-core` update.
