### ISSUE TITLE
Wrong expo default port

### ISSUE THREAD

**Issue by TheMightyPenguin** [jhen0409/react-native-debugger#126]
# Context

Expo default port is 19000, any reason why 19001 was used here?

https://github.com/jhen0409/react-native-debugger/blob/a2ed97bb10706d4542c33df834915ac9a291bc92/npm-package/bin/rndebugger-open.js#L5

**Comment by jhen0409** [comment]
Expo will open two servers, the debug proxy is on 19001 by default.
