### ISSUE TITLE
Redux Does Not Connect

### ISSUE THREAD

**Issue by Clete2** [jhen0409/react-native-debugger#127]
React Native Debugger version: 0.7.6
React Native version: 0.47.2
Platform: iOS 10.3
Is real device of platform: No; simulator
Operating System: macOS Sierra

Using `"remote-redux-devtools": "^0.5.12"`

Store is created as such:
```
import reducers from '../reducers/index';
import { composeWithDevTools } from 'remote-redux-devtools';
import { createStore, applyMiddleware } from 'redux';
...
const store = createStore(reducers, composeWithDevTools(applyMiddleware(thunk)));
```

If I use [VSCode Redux Devtools](https://marketplace.visualstudio.com/items?itemName=jingkaizhao.vscode-redux-devtools) it works:

<img width="731" alt="screen shot 2017-08-28 at 7 18 06 pm" src="https://user-images.githubusercontent.com/361546/29798907-ace77dc6-8c25-11e7-86f8-30724fa7087c.png">

However `React Native Debugger` looks like this:
![screen shot 2017-08-28 at 7 19 28 pm](https://user-images.githubusercontent.com/361546/29798951-dcc4bcde-8c25-11e7-9e74-f65b067b4b75.png)

(Yes even when VSCode is totally closed)

You can see the last line in the log is showing that it's connected to `remotedev-server` as part of `devTools.js` which is part of `remote-redux-devtools` from what I can tell.

What can be done to troubleshoot?

**Comment by jhen0409** [comment]
Please read [documentation](https://github.com/jhen0409/react-native-debugger/blob/master/docs/redux-devtools-integration.md). (Redux DevTools Integration)

I guess you have same misunderstanding with https://github.com/jhen0409/react-native-debugger/issues/29.

**Comment by Clete2** [comment]
@jhen0409 Thank you so much! I had read the documentation but I didn't understand the difference between `remote-redux-devtools` and `redux-devtools-extension` -- I figured they worked the same since their wrapper method was the same name. Big mistake!

For anyone else who may run into this issue:
`yarn remove remote-redux-devtools; yarn add redux-devtools-extension`

In `createStore` (no change from above):
`const store = createStore(reducers, composeWithDevTools(applyMiddleware(thunk)));`

But the import (by the same name) now comes from `redux-devtools-extension`:
`import { composeWithDevTools } from 'redux-devtools-extension';`


P.S. @jhen0409 Thanks so much for your hard work on this project. It's immensely helpful to us!

**Comment by BinaryMuse** [comment]
Just popping in to say that I also had the same misunderstanding as #29 (and this), @Clete2's comment was exactly what I needed. Thanks to you both ❤️

**Comment by stevematdavies** [comment]
```
import { createStore, applyMiddleware  } from 'redux';
import { composeWithDevTools } from 'redux-devtools-extension';
import thunk from 'redux-thunk';
import placeReducer from './placeReducer';

const store = createStore(
    placeReducer,
    composeWithDevTools(applyMiddleware(thunk)));
export default store
```
Yet when debugging react-native remote debugger, devtools redux extension says no store found, app works fine.
