### ISSUE TITLE
Can't connect with Android Emulator

### ISSUE THREAD

**Issue by xianlinbox** [jhen0409/react-native-debugger#13]
Hi 

> React Native  v^0.30
> React Redux  v^4.4.5

I try to use this tool for my React Native App,  It works in iOS simulator, I reload JS, it connected with React Native Debugger. But in Android, It doesn't work, I started android app, the output as follow:

```
Starting JS server...
Running /Users/xnliu/Library/Android/sdk/platform-tools/adb reverse tcp:8081 tcp:8081
Building and installing the app on the device (cd android && ./gradlew installDebug...
Incremental java compilation is an incubating feature.
...
Installing APK 'app-debug.apk' on 'AVD_for_Nexus_5_by_Google(AVD) - 7.0' for app:debug
Installed on 1 device.

BUILD SUCCESSFUL

Total time: 12.302 secs

This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.10/userguide/gradle_daemon.html
Starting the app on emulator-5554 (/Users/xnliu/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am start -n com.propertyfinder/.MainActivity)...
Starting: Intent { cmp=com.propertyfinder/.MainActivity }
```
but no matter how much times i reload JS, it never connected with React Native Debugger.

A weird thing is that I open http://localhost:8081/debugger-ui in chrome, It says Another Debugger is already connected. after I close React Native Debugger, the web page didn't say that anymore, It looks like React Native Debugger is really connect with the app just  didn't show anything in Debugger UI.

Is there any additional setting for Android dedug?

**Comment by jhen0409** [comment]
Hey @xianlinbox, thanks for report, but unfortunately, I can't reproduce it with the same environment, it looks work fine for me: (for RN 0.30, if you want to use React DevTools, remember run [`$ adb reverse tcp:8097 tcp:8097`](https://github.com/jhen0409/react-native-debugger#note-for-android))

![2016-10-10 12 02 46](https://cloud.githubusercontent.com/assets/3001525/19226714/9e75e030-8ee1-11e6-9c2d-527c7e429495.png)

**Comment by xianlinbox** [comment]
@jhen0409 Thanks for the kindly reply, 

I found the issuer, I didn't open remote JS debug in Android simulator, after open it, everything works fine, Thanks so much for such a cool tool.

**Comment by CyrusZei** [comment]
for anybody that comes here.

If you have the remote debugger tab open, close that and then do a reload on the app and it will work
