### ISSUE TITLE
Dimensions are missing

### ISSUE THREAD

**Issue by aloifolia** [jhen0409/react-native-debugger#132]
React Native Debugger version: 2.5.0
React Native version: 0.47.0
Platform: Android
Is real device of platform: Yes
Operating System: macOS

For me, the debugger tends to show the dimensions of an element unreliably. Sometimes it appears after a while, but most times there is just an indicator "loading" in the side panel.

**Comment by jhen0409** [comment]
I guess RN for Android have some problem of layout measure, for me it just slow than iOS, doesn't keep `loading`. I'll check if that with real device made some problems.

**Comment by jhen0409** [comment]
I guess
