### ISSUE TITLE
Render process gone

### ISSUE THREAD

**Issue by pocesar** [jhen0409/react-native-debugger#134]
React Native Debugger version: 0.7.6
React Native version: 0.48.1
Platform: Android 6.0.1
Is real device of platform: Yes
Operating System: Windows

![image](https://user-images.githubusercontent.com/461084/30096771-aff68a34-92b0-11e7-9988-f8b08573e36c.png)

When navigating through my app, randomly the error appears. The app then hangs, having to forcefully close it, and RN Debugger.
I'm using react-native-router-flux 4.0 beta FWIW, and I'm not being able to remotely debug the app anymore

**Comment by jhen0409** [comment]
I had a Windows machine and I tried [example of react-native-router-flux](https://github.com/aksonov/react-native-router-flux/tree/master/Example), it works fine, would be great if you could provide a minimal example project.

**Comment by pocesar** [comment]
it was random, but it seems that was an error with Babel (babelHelpers.objectDestructuringEmpty is not a function) that was being swalled by RN. it seems that it's not happening anymore
