### ISSUE TITLE
Bypass ERR_INSECURE_RESPONSE

### ISSUE THREAD

**Issue by tquiroga** [jhen0409/react-native-debugger#137]
When you are making https requests on a local web server, you get Chrome's warning ERR_INSECURE_RESPONSE, the only way to bypass is usually to open a tab and click the Proceed anyway link at the bottom of the warning. There is no way to do that on the editor.

Any solution for that?

**Comment by jhen0409** [comment]
We should can fix this by catch [`certificate-error`](https://electron.atom.io/docs/api/app/#event-certificate-error).
