### ISSUE TITLE
Waiting For React To Connect. Android | Windows | Real Device and Emulator 

### ISSUE THREAD

**Issue by ThalaHemanth** [jhen0409/react-native-debugger#138]
React Native Debugger version: 0.3.12
React Native version: 0.47
Platform:  Android, 
Is real device of platform: Yes 
Operating System:  Windows

Redux is working but stuck at react. i've tried with genymotion emulator that too has same issue. modified  setupDevtools.js for real device but still didn't work

**Comment by ThalaHemanth** [comment]
i found the problem. virtual box ip is given priority than my wifi. i changed it back to wifi. now its working. #Genymotion/windows Issue.

**Comment by Naser2** [comment]
On real device:  Shake device & Click "Debug Remote JS". 
On Simulator: Try: Cmd or control + D on the Simulator & Click "Debug Remote JS".
