### ISSUE TITLE
Haul issues

### ISSUE THREAD

**Issue by jhen0409** [jhen0409/react-native-debugger#141]
Note that if you're using [Haul](https://github.com/callstack-io/haul) as RN bundler and debug via RNDebugger, the following features are not supported:

## Debugger features

* [Developer Menu integration](https://github.com/jhen0409/react-native-debugger/blob/master/docs/debugger-integration.md#developer-menu-integration) - currently we used [require polyfill](https://github.com/facebook/metro-bundler/blob/master/packages/metro-bundler/src/Resolver/polyfills/require.js) from `metro-bundler`, it assigned `__DEV__` / `require` global vars, but `undefined` for Haul. But `Network Inspect` is supported.
* Ignore `__RND_INTERVAL__` logging on MessageQueue.spy (#140), the reason same as above.
* [Enable open in editor for console log](https://github.com/jhen0409/react-native-debugger/blob/master/docs/debugger-integration.md#enable-open-in-editor-for-console-log) - Webpack have no tell project root of file path for console log. (need #73 and follow-up works)

Currently these features are only for [`metro-bundler`](https://github.com/facebook/metro-bundler) (RN default bundler). I might to help if I want to migrate to Haul, otherwise these may need a maintainer.

## CLI

* Currently we have yet support patch Haul by [the npm package](https://github.com/jhen0409/react-native-debugger/tree/master/npm-package)
* Currently the `REACT_DEBUGGER` env doesn't support in Haul

**Comment by blackxored** [comment]
Been playing with Haul myself. Adding to this (which I've yet to verify), AsyncStorage clear doesn't work as well.

**Comment by jhen0409** [comment]
@blackxored Thanks! I think it should be bug because the item is not hidden. (fixed in master)
