### ISSUE TITLE
RND doesn't play well with Expo.

### ISSUE THREAD

**Issue by visylvius** [jhen0409/react-native-debugger#142]
Hi guys. I've been trying to use RND with expo for some time and have been running into a few problems. i've been following these posts 
https://www.gravitywell.co.uk/latest/rd/posts/react-native-debugger-expo-awesome/
https://github.com/jhen0409/react-native-debugger/issues/84

Major problem i've been running into is that whenever I try to run anything CLI related I get the following
This is the command I typically run 
```
rndebugger://set-debugger-loc?host=localhost&port=19001
```
```
[1] 7146
zsh: no such file or directory: rndebugger://set-debugger-loc?host=localhost
[1]  + 7146 exit 127   rndebugger://set-debugger-loc?host=localhost
```

React Native Debugger app version: 0.7.7
React Native version: https://github.com/expo/react-native/archive/sdk-20.0.0.tar.gz
Platform: Android
Is real device of platform: [Yes or No] No. Genymotion/Expo
Operating System: macOS

any help would be greatly appreciated. Thanks!

**Comment by jhen0409** [comment]
The command should be `open rndebugger://set-debugger-loc?host=localhost&port=19001`, you're missing `open ` so it causes `no such file or directory` error.

**Comment by jhen0409** [comment]
Also, you could type `Command+T` to new debugger window and specify the Expo packager port ([documentation](https://github.com/jhen0409/react-native-debugger/blob/master/docs/debugger-integration.md#multiple-react-native-packager-custom-port-support)), or use [npm package](https://github.com/jhen0409/react-native-debugger/tree/master/npm-package) (see [doucmentation](https://github.com/jhen0409/react-native-debugger/blob/master/docs/getting-started.md#getting-started) and [examples](https://github.com/jhen0409/react-native-debugger/tree/master/examples)).

**Comment by visylvius** [comment]
Right on man! Thank you so much.
