### ISSUE TITLE
set localhost port on ubuntu

### ISSUE THREAD

**Issue by clearproof** [jhen0409/react-native-debugger#143]
How do I set the localhost port on ubuntu ?
Cause this is only working on mac ("open 'rndebugger://set-debugger-loc?host=localhost&port=19001'")
When I open remote debugger from the avd nexus phone it always opens the debugger in chrome.. Thanks

**Comment by jhen0409** [comment]
We have yet to support URI scheme for Linux / Windows.

You can `Ctrl+T` to new debugger window and specify packager port, or just use [npm package](https://github.com/jhen0409/react-native-debugger/tree/master/npm-package) ([examples](https://github.com/jhen0409/react-native-debugger/tree/master/examples) are used), these should be already mentioned in the documentation, please read the issue template first.

**Comment by clearproof** [comment]
Thanks it works fine. Sorry I didn't see it.

Best,
Junes

2017-09-12 20:06 GMT+02:00 Jhen-Jie Hong <notifications@github.com>:
