### ISSUE TITLE
[React DevTools] Memory issue

### ISSUE THREAD

**Issue by hushicai** [jhen0409/react-native-debugger#147]
I wonder that when i use react-native-debugger,the xcode memory grow fast, but after i switch to debugger-ui,it becomes normal...

![image](https://user-images.githubusercontent.com/1249423/30857918-2aed8720-a2f0-11e7-8293-0b1ce780f47c.png)

I am using flatList with a `setInterval` countdown.
![image](https://user-images.githubusercontent.com/1249423/30858031-82b7e3c4-a2f0-11e7-9841-e27748886219.png)

React Native Debugger app version: 0.77
Platform: IOS
Is real device of platform: NO
Operating System: macOS

**Comment by jhen0409** [comment]
I think some behaviors of react-devtools will cause it, you can try to close react panel (CMD+OPTION+J), in addition for that, RNDebugger should not be much different with debugger-ui.

**Comment by jhen0409** [comment]
Also, if you stay on `Runtime is not ready for debugging` error for some reason like close RNDebugger or directly close packager, [the RND interval](https://github.com/jhen0409/react-native-debugger/blob/master/app/worker/index.js#L42) will cause the memory issue, reload JS doesn't seem to release memory. I fixed it in https://github.com/jhen0409/react-native-debugger/commit/7f02445757a8882265aa30860010d8ac19d6e7fc here, I'll release new version.

If the above doesn't work for you, provide a minimal example project will be great.

**Comment by hushicai** [comment]
Actually, using official react-devtools still run into the same issue..

**Comment by hushicai** [comment]
Hi, I make [a minimal project](https://github.com/hushicai/XcodeReactDevTools/tree/master) that can reproduce this issue. 
I think it should be something wrong with `react-devtools`.

**Comment by jhen0409** [comment]
@hushicai Thanks! I'll help to investigate for it, you can also file the issue in [react-devtools](https://github.com/facebook/react-devtools) repo.

**Comment by hushicai** [comment]
facebook/react-devtools#900
