### ISSUE TITLE
Debugger hijacks "Apple-R" of entire OS on Mac

### ISSUE THREAD

**Issue by GeoffreyPlitt** [jhen0409/react-native-debugger#153]
I am on the latest version.

When I am using Chrome, if I do Apple-R, my chrome tab does not refresh; instead, the simulator refreshes. Closing the debugger restores things to normal. So it seems the debugger hijacks this shortcut OS-wide. I would expect it to only use this shortcut when the simulator or debugger are the currently focused app.

Only started happening today.

**Comment by jhen0409** [comment]
It's [feature](https://github.com/jhen0409/react-native-debugger/pull/129) included in 0.7.8. What is use case you need to reload debugger?

**Comment by jhen0409** [comment]
Oh sorry I misunderstood, it's bug of the keyboard shortcuts, I'll investigate this.

**Comment by GeoffreyPlitt** [comment]
Thanks!
