### ISSUE TITLE
Help with Remote debugging in Windows and a iPhone (question)

### ISSUE THREAD

**Issue by diegofrayo** [jhen0409/react-native-debugger#161]
Hello, I have tried to debug my RN application using react-native-debugger but Im not be able.

Im using expo, Im doing these steps:

- I modified this file: `node_modules/react native/Libraries/Core/Devtools/setupDevtools.js`  and update the host property value with my ip `192.168.1.11`
- I open react-native-debugger application
- I run my application: `exp start --lan --dev`

This is my App.js code
```
import { NativeModules, Platform } from 'react-native';

import App from './src/screens';

if (__DEV__ && Platform.OS === 'ios') {
  // im sure it is executing
  NativeModules.DevSettings.setIsDebuggingRemotely(true);
}

export default App;
```

Im running my application in a real device, an iPhone 5, via **wi-fi**

I can debug JS code entering to this url: http://localhost:19001/debugger-ui, but I want to do the same in react-native-debugger, but my application never connects with it.

Expo version: 21.0.2
React Native Debugger app version: 0.7.10
React Native version: 0.48.4
Platform: iOs 11.0.3
Is real device of platform: Yes
Operating System: Windows 7 32 bits

before hand, thank you.

**Comment by jhen0409** [comment]
Do you followed [Getting Started](https://github.com/jhen0409/react-native-debugger/blob/master/docs/getting-started.md) to specify the React Native packager port for Expo?

**Comment by diegofrayo** [comment]
@jhen0409 That is the solution!, I didn't understand that step, I'm sorry. I already can connect my application to React Native Debugger, Thank you, this tool is great!!!
