### ISSUE TITLE
Suggestion: No Auto Update

### ISSUE THREAD

**Issue by DavidDionise** [jhen0409/react-native-debugger#164]
React Native Debugger app version: [7.12]
React Native version: [0.42.3]
Platform: [iOS]
Is real device of platform: [No]
Operating System: [macOS]

After RND 7.10, the debugger causes the entire simulator (and debugger) to freeze when I try to open a drawer from react-native-drawer. I can't tell exactly why this is happening, but it would be much prefered by me if I could decide whether or not to update react-native-debugger, rather than having it forced on me every time I open my project.

**Comment by jhen0409** [comment]
#149 have mentioned about this.

Also, I still wondering the problem, would be great if you can file an issue with a minimal example project.
