### ISSUE TITLE
[QUESTION] differentiate between chrome and react-native-debugger 

### ISSUE THREAD

**Issue by 7ynk3r** [jhen0409/react-native-debugger#169]
I need to execute a function only while debugging with `react-native-debugger`.

Is there a way to know in `react-native` if I'm using the chrome debugger or `react-native-debugger`.

Thanks!
JM 

React Native Debugger app version: 0.7.12
React Native version: 0.45.1
Platform: any
Is real device of platform: NO
Operating System: macOS

**Comment by jhen0409** [comment]
You can check by the following code:

```js
navigator.userAgent && navigator.userAgent.indexOf('ReactNativeDebugger/') > -1
```

Also, [these redux global APIs](https://github.com/jhen0409/react-native-debugger/blob/master/docs/redux-devtools-integration.md) could be help to know it on RNDebugger as well.
