### ISSUE TITLE
binary / problem building

### ISSUE THREAD

**Issue by jondot** [jhen0409/react-native-debugger#17]
Hi,
Since documentation and release (and what's on homebrew) are not in-sync I'd suggest putting a new build or removing binaries completely, or maybe putting a note about the incompatibility. I just spent an hour trying to figure out why the 0.4.0 build isn't working :(

Continuing on, when trying to build, one of the requirements (`jss@3.11.1`) needs a node version < 6.0.0, which means I had to fetch dependencies with my node 4.3.1 version, and then build with 6.0.0, since when building with 4.3.1 I got a broken app.

I'll happily upload the binary I just built somewhere if needed.

**Comment by jhen0409** [comment]
Hi @jondot!

> Since documentation and release (and what's on homebrew) are not in-sync

I'm doing the work of `v0.5.0`, I should updates the document after release... sorry about that, it released later than expected, updated documentation differences [here](https://github.com/jhen0409/react-native-debugger/commit/f7be096dfb2b9f8b277d5fced1fa12e73ab59b42).

> Continuing on, when trying to build, one of the requirements (jss@3.11.1) needs a node version < 6.0.0

It may related to https://github.com/alexkuz/redux-devtools-inspector/issues/45, we need to update it, but it seems still works on node 6.

**Comment by jondot** [comment]
Thanks! Please let me know how I can help if needed

**Comment by jondot** [comment]
Just saw the new release, awesome!
