### ISSUE TITLE
Add option to "keep window always on top"

### ISSUE THREAD

**Issue by lucasbento** [jhen0409/react-native-debugger#170]
I would like a functionality to keep the window always on top, my use case is that I like to keep the IDE on fullscreen on macOS but want to see the debugger as well, that option can stay on the menu.

On Electron it's possible to use [`win.setAlwaysOnTop`](https://electron.atom.io/docs/api/browser-window/#winsetalwaysontopflag-level-relativelevel). I can send a PR if it's considered a good addition to the project.

React Native Debugger app version: `0.7.12`
React Native version: `0.49.3`
Platform: `iOS`
Is real device of platform: `Yes`
Operating System: `macOS`

**Comment by jhen0409** [comment]
We have [`Stay In Front`](https://github.com/jhen0409/react-native-debugger/blob/master/electron/menu/darwin.js#L55) in `Debugger` of application menu, is that doesn't work for you?

**Comment by lucasbento** [comment]
@jhen0409: ah, sorry, didn't know that option existed, works nicely, thank you and sorry for opening the issue!
