### ISSUE TITLE
API Request failes, if the debugger is running

### ISSUE THREAD

**Issue by Xyzor** [jhen0409/react-native-debugger#172]
Hello,

I am trying to reach my computer (api server) from my mobile with local IP address, but if I use the debugger, it failes. It would be great to figure out whats causing this issue, because this debugger app is awesome. Any idea why does it happens?

React Native Debugger app version: 0.7.12
React Native version: 0.49
Platform: Android (5.0.1)
Is real device of platform: Yes
Operating System: Ubuntu 14.04

**Comment by jhen0409** [comment]
Is that have any logs? Could you provide an example?

**Comment by Xyzor** [comment]
Sorry for the poor description.

I updated a couple packages, and now I can't reproduce the error. It works fine. :)
