### ISSUE TITLE
[Feature request]  the keyboard shortcut of changing tabs

### ISSUE THREAD

**Issue by kimown** [jhen0409/react-native-debugger#178]
![image](https://user-images.githubusercontent.com/7932380/32646570-c1afda84-c5b2-11e7-80df-0370cdbd6b99.png)

I have two tabs, first tab 8081 is for ios,  second tab 8082 is for android.The only way changing tabs now is using the shortcut below, but they always switch application but not changing tabs in react-native-debugger.

![image](https://user-images.githubusercontent.com/7932380/32646637-0b699142-c5b3-11e7-8547-8faeca7d594e.png)

When I use chrome, I can change tabs using shortcut `command+shift+[` or `command+shift+]` , Can react-native-debugger support these shortcuts? Thanks.

**Comment by jhen0409** [comment]
Yeah we could support it by the [API](https://github.com/electron/electron/blob/master/docs/api/browser-window.md#winselectprevioustab-macos) or custom [roles](https://github.com/electron/electron/blob/0694334487a10a9c29632b597874a2fada453d3a/docs/api/menu-item.md#roles), but note that it only support Electron 1.8 (#130).

> The only way changing tabs now is using the shortcut below, but they always switch application but not changing tabs in react-native-debugger.

Is `control+tab` switched application not `command+tab` for you?

**Comment by kimown** [comment]
@jhen0409   
Many thanks, control+tab works for me , now I can change tabs use this shortcut.

**Comment by kimown** [comment]
I also found another problem, when I Reload first tab 8081 , the second tab 8082 throw errors, It seems the RN's problem, the two tabs use  the same debug port.
```
bundle.js:1 Uncaught TypeError: this.props.debugger.syncState is not a function
    at EventEmitter.U.ipcRenderer.on (bundle.js:1)
    at emitTwo (events.js:106)
    at EventEmitter.emit (events.js:194)
```
![image](https://user-images.githubusercontent.com/7932380/32651867-fd66f99e-c5c7-11e7-867b-86152435a92f.png)

tab1:
![image](https://user-images.githubusercontent.com/7932380/32651960-5bb3068c-c5c8-11e7-833e-900dea8b8f1c.png)

tab2:
![image](https://user-images.githubusercontent.com/7932380/32651978-682419e2-c5c8-11e7-90ba-c39803715f74.png)
