### ISSUE TITLE
Data in State inconsistent with data in app 

### ISSUE THREAD

**Issue by prodigynelson** [jhen0409/react-native-debugger#184]
I’m using expo to build a meetup type app that also features a social media section similar to yik yak. I am using react-native (obviously) and redux for the frontend, and for the backend I am using django. Fetching “local posts” (social media section) will return a localpost object, with attributes such as: “upvote_count”, “downvote_count”, “is_user_upvoting” and “is_user_downvoting”.

I know that the backend logic that return those attributes functions as it should because it has been tested via postman, and most of it works as it should in the frontend, however I’m getting a very weird bug: in the “state” of react-native-debugger, the attribute “is_user_upvoting” will be “true” (which is how it should be as it’s what is returned from the backend, which I know to be correct because I tested it in parallel using postman on top of verifying that there is no upvote record in my django database manager) but the app (and console log) think that “is_user_upvoting” is false. is_user_upvoting has exactly the same code as everything involved with "is_user_downvoting" (which works) but returns the opposite as it should
[Screenshot of it side by side with postman](http://prntscr.com/hgyr8s) (NOTE in the logger, it is ordered alphabetically so though on first glance it appears to be "true, false" like the state/postman, it is reversed)

I’m 99% certain that I don’t have any functions that would change the value of “is_user_upvoting” to be false (I do have functions/actions that change that value but if they were called they would show up in the “dif” part of the react-native-debugger state, on top of being displayed as “false” in the react-native-debugger state which it’s not).

What makes me certain it’s not something I coded incorrectly is the fact that it’s one way in the “state” and another way in the app. Am I maybe misunderstanding react-native-debugger state? Or is there some sort of caching that expo does about attributes that I don’t understand?

React Native Debugger app version: [0.7.13]
React Native version: [0.47.1]
Platform: [iOS]
Is real device of platform: [No]
Operating System: [macOS]

**Comment by jhen0409** [comment]
> I do have functions/actions that change that value but if they were called they would show up in the “dif” part of the react-native-debugger state, on top of being displayed as “false” in the react-native-debugger state which it’s not

You may do something mutation instead of create new object, it will be made the old console object changes, for example:

<img width="164" alt="screen shot 2017-11-30 at 12 14 12 pm" src="https://user-images.githubusercontent.com/3001525/33412732-525e4e92-d5c8-11e7-8734-759fcd38d13b.png">

I guess it's why `redux-logger` printed the result, but I'm not sure what you did.

**Comment by prodigynelson** [comment]
@jhen0409 redux logger is a dependency that automatically logs all action dispatches, so it logged all the information associated with the action "fetch_local_posts" of which is the "payload" of data it requested from the backend. Said payload is the first record of the information being returned to the frontend hence any subsequent actions would not have had a chance to change the data. So, it is console logging incorrect data, but somehow the state preview in react-native-debugger gets the correct information.

**Comment by jhen0409** [comment]
If you do some mutation, the old console object will be changed even `redux-logger` (it used `console.dir`), the good practice is do state change immutability by reducer. For react-native-debugger it use `stringify / parse` to send state between app and devtools, so the mutation doesn't apply for it, and it's expected.

Try to use [`predicate`](https://github.com/evgenyrodionov/redux-logger#predicate--getstate-function-action-object--boolean) to log the action / state by `JSON.stringify`, you may be get the correct information.

**Comment by jhen0409** [comment]
Closed because the problem may not related here. Feel free to re-open if you sure the problem is related here. (You can try debug [the API in worker](https://github.com/jhen0409/react-native-debugger/blob/master/app/worker/reduxAPI.js))
