### ISSUE TITLE
Debugging Expo/React-Native Project with GenyMotion  in Windows Problem 

### ISSUE THREAD

**Issue by clarktank** [jhen0409/react-native-debugger#187]
On my Geneymotion emulator, I am trying to use react-native-debugger and getting the file error:
![2017-12-10 4](https://user-images.githubusercontent.com/31081495/33814855-186fca9a-ddfb-11e7-987d-996cd4f053a1.png)
Do I have to add react-native-debugger to my path? since the rndebugger-open doesn't execute?

I run my expo with the following command:
`exp start -c --dev --lan`

I don't have any issues with the current remote debugger. Only the react-native-debugger doesn't work!
I have read the guides and before running the project, I execute the following:

`set REACT_DEBUGGER="rndebugger-open --open --expo"`

and also I have added the following to my package.json:

```
  "devDependencies": {
    "eslint-config-rallycoding": "^3.2.0",
    "react-native-debugger-open": "^0.3.15"
  },
  "scripts": {
    "postinstall": "rndebugger-open"
  }
```

Also my react-native-debugger looks like this:
![2017-12-10 1](https://user-images.githubusercontent.com/31081495/33814869-42c0e586-ddfb-11e7-96a3-09cb5720e0c7.png)

Can you make a step by step guide or help me out with this issue?

React Native Debugger app version: [v0.7.13]
React Native version: [0.50]
Expo:[23]
Platform: [Android-Genymotion-2.11.0]
Is real device of platform: [No]
Operating System: [Windows10]

**Comment by jhen0409** [comment]
If you've set the `postinstall` script, you don't need to set the `REACT_DEBUGGER` env.

For Windows, the [package](https://github.com/jhen0409/react-native-debugger/tree/master/npm-package) is only send port to RND, it can't execute RND automatically. Please keep RND opened before enable remote debug mode.

If it still not work for you, try [`Ctrl+T`](https://github.com/jhen0409/react-native-debugger/blob/master/docs/shortcut-references.md#keyborad-shortcuts) to new debugger window and specify the port will be helpful, and I'll try to reproduce the issue on Windows.
