### ISSUE TITLE
Error: there is no way to give you money

### ISSUE THREAD

**Issue by infostreams** [jhen0409/react-native-debugger#192]
I just want to say "thank you" for creating and open sourcing react-native-debugger. It's been an invaluable tool for me and I don't know how I would get my work done without it. THANK YOU SO MUCH! That being said, I would love to send you some money to express my gratitude, but there's currently no way to do it. Please resolve this issue (patreon? paypal?) and then close :-)

**Comment by jhen0409** [comment]
Thank you!

I created the [open collective page](https://opencollective.com/react-native-debugger) for improving this project, if you are interested please use it. 😄
