### ISSUE TITLE
Performance monitor 

### ISSUE THREAD

**Issue by nesterman** [jhen0409/react-native-debugger#199]
Hi, 
It would be great if you add to the app performance monitor like in a browser.
Thanks.

**Comment by gre** [comment]
agreed. is it easy to add?

**Comment by Xiot** [comment]
Would love to have this.

**Comment by muraterd** [comment]
+1 for this

**Comment by gre** [comment]
I would recommend you guys to test React Profiler tab in the meantime. it's pretty cool and focus on the React part of the perf.
