### ISSUE TITLE
Inspector missing actions when scrolling up, is there a limit ? 

### ISSUE THREAD

**Issue by alfonsodev** [jhen0409/react-native-debugger#200]
Is there a limit of actions in the Inspector?
I'm seeing all the actions appear on the Inspector correctly until the scroll is enabled, then scrolling back to the top doesn't show the first 12 actions.
Only @@INIT action remains on top. 

React Native Debugger app version: 0.7.13
React Native version: 0.49.3
Platform: iOS
Is real device of platform: No
Operating System:  macOS

**Comment by luisnaranjo733** [comment]
How can we configure this options obj when we are already using the param to composeWithDevTools?

For example:
```
export function configureStore() {

  let middleware = applyMiddleware(
    loggingMiddleware,
    epicMiddleware, 
    navMiddleware, 
    ...telemetryMiddlewares);
  
  if (__DEV__) {
    middleware = composeWithDevTools(middleware);
  }

  return createStore(reducer, middleware);
}
```

**Comment by jhen0409** [comment]
@luisnaranjo733, the documentation already explained:

```js
composeWithDevTools(options)(middleware)
```

You can also check out [the example](https://github.com/jhen0409/react-native-debugger/blob/master/examples/counter-with-redux/src/configureStore.js#L8-L12).

**Comment by jhen0409** [comment]
I'll close this issue because no responses.

**Comment by Yaolegol** [comment]
check [maxAge](https://github.com/zalmoxisus/redux-devtools-extension/blob/f77253c65841569c1b588f13a14221ea30f11e98/docs/API/Arguments.md#maxage) option
