### ISSUE TITLE
port is not defined at launchChromeDevTools

### ISSUE THREAD

**Issue by idrakimuhamad** [jhen0409/react-native-debugger#201]
I'm getting #194 initially, so after I've update to 0.3.16, I'm getting this now.

`ReferenceError: port is not defined at launchChromeDevTools (/node_modules/react-native/local-cli/server/middleware/getDevToolsMiddleware.js:65:75)`

I've take a look at the code and found an undeclared variable `port`. Not sure if it was declared initially.

```
function launchChromeDevTools(host, args = '', skipRNDebugger) {
  var __rnd_path = 'rndebugger://set-debugger-loc?host=localhost&port=' + port ; <---
...
```

As workaround for now, I just hardcoded 8081 to the variable and solved the problem.

React Native Debugger app version: 0.3.16
React Native version: 0.53.0
Platform: iOS, Andorid
Is real device of platform: Yes
Operating System: MacOS

**Comment by danieljvdm** [comment]
can confirm. In some cases this actually silently failed for me and ended up trying to load an old bundle. Spent the better half of today trying to debug this!

**Comment by idrakimuhamad** [comment]
And not sure if its related, on iOS it just stuck at the splashscreen with no indication of the problem. I usually only see it when I ran the app on Android simulator.

**Comment by jhen0409** [comment]
Yeah, it looks like #198 doesn't solved the issue fully, I'll fix it later!
