### ISSUE TITLE
Using with iPhone device

### ISSUE THREAD

**Issue by AndrejGajdos** [jhen0409/react-native-debugger#208]
If I want to connect devtools with a simulator, it works. When I try an iPhone device connected by USB, I see a message "Waiting for React to connect…"

React Native Debugger app version: [0.7.13]
React Native version: [0.52.0]
Platform: [macOs Sierra 10.12.6, iOS 11.2.6, Xcode 9.2]
Is real device of platform: [Yes]
Operating System: [macOs Sierra 10.12.6]

**Comment by jhen0409** [comment]
Please read the [`How to use it with real device?`](https://github.com/jhen0409/react-native-debugger/blob/master/docs/react-devtools-integration.md#how-to-use-it-with-real-device) section in the documentation.

**Comment by AndrejGajdos** [comment]
It means that under 0.53 it doesn't work at all?

**Comment by jhen0409** [comment]
> It means that under 0.53 it doesn't work at all or I should use older version of react-native-debugger?

That documentation just mentioned about RN versions. Under v0.53 you need to change the `setupDevtools` file manually.

**Comment by AndrejGajdos** [comment]
Ok, thanks
