### ISSUE TITLE
How do you define the port number when running executable "React Native Debugger"

### ISSUE THREAD

**Issue by jtara1** [jhen0409/react-native-debugger#212]
can't start via the cli alias added by `react-native-debugger-open`
```
j@j-desktop:/usr/lib/node_modules/react-native/local-cli/server/middleware$ rndebugger-open 
FAIL Replace `open debugger-ui with Chrome` to `open React Native Debugger`, the file 'local-cli/server/middleware/getDevToolsMiddleware.js' not found.
```

text replace failed because there is not such text as `open debugger-ui with Chrome` in the .js file it's searching in
```
j@j-desktop:/usr/lib/node_modules/react-native/local-cli/server/middleware$ ls
total 36
-rw-r--r-- 1 nobody j  822 Mar  9 09:21 copyToClipBoardMiddleware.js
-rw-r--r-- 1 nobody j 2452 Mar  9 09:21 getDevToolsMiddleware.js
-rw-r--r-- 1 nobody j  217 Mar  9 09:21 index.html
-rw-r--r-- 1 nobody j  546 Mar  9 09:21 indexPage.js
-rw-r--r-- 1 nobody j  534 Mar  9 09:21 loadRawBodyMiddleware.js
-rw-r--r-- 1 nobody j  673 Mar  9 09:21 openStackFrameInEditorMiddleware.js
-rw-r--r-- 1 nobody j  606 Mar  9 09:21 statusPageMiddleware.js
-rw-r--r-- 1 nobody j  944 Mar  9 09:21 systraceProfileMiddleware.js
-rw-r--r-- 1 nobody j  531 Mar  9 09:21 unless.js
j@j-desktop:/usr/lib/node_modules/react-native/local-cli/server/middleware$ cat getDevToolsMiddleware.js | grep "open debugger-ui"
j@j-desktop:/usr/lib/node_modules/react-native/local-cli/server/middleware$ 
```

I can run the program directly via the release files, but I don't understand how to define port here or connect to my react-native app
```
j@j-desktop:~/software/rn-debugger-linux-x64$ ./React\ Native\ Debugger 
Starting listen set-debugger-loc request on port 42171
Will save port to `$HOME/.rndebugger_port` file
[Updater] Checking updates...
[Updater] Error There is no newer version. false
```

React Native Debugger app version: v0.7.14
React Native version: 
```
j@j-desktop:~/_Github-Projects/base_converter$ react-native --version
react-native-cli: 2.0.1
react-native: 0.52.0
```

Platform: react-native setup to render on real android phone with help of Expo
Is real device of platform: Yes
Operating System: Linux

**Comment by jhen0409** [comment]
> can't start via the cli alias added by react-native-debugger-open

You need to do that in root path of your RN project. I recommend to add the [postinstall](https://github.com/jhen0409/react-native-debugger/tree/master/npm-package#inject-to-react-native-packager) script, such as the [examples](https://github.com/jhen0409/react-native-debugger/tree/master/examples).

Also, you can use `Ctrl+T` to define port manually, please read the [documentation](https://github.com/jhen0409/react-native-debugger/blob/master/docs/getting-started.md#getting-started).
