### ISSUE TITLE
[RN 0.50 / 0.51] "Requiring unknown module" error after hot reloading

### ISSUE THREAD

**Issue by yqz0203** [jhen0409/react-native-debugger#214]
Using react-native debugger, throw an Error after hot reloading.

![image](https://user-images.githubusercontent.com/8850879/37451903-05daccbe-286e-11e8-9bf9-d4a6add55040.png)

React Native Debugger app version: 0.7.15
React Native version: 0.51.0
Platform: iOS & Android
Is real device of platform: false
Operating System: macOS

**Comment by jhen0409** [comment]
Please follow the issue template.

**Comment by yqz0203** [comment]
@jhen0409 sorry, did that.

**Comment by jhen0409** [comment]
After #211 we enabled Delta bundler by default, so It may affect RN 0.50 / 0.51 (included the bundler but not enabled in default Chrome debugger).

We can try to fix that, or upgrade the RN version.

**Comment by yqz0203** [comment]
@jhen0409 ok, thanks。

**Comment by jhen0409** [comment]
Fixed in #215. I'll release the new version later.

**Comment by w10036w** [comment]
**Bug report**
same scenario with the issue owner, connecting to chrome debugger has no issue.
**Requiring unknown module "0"**

React Native Debugger app version: 0.9.8
React Native version: 0.59.8
Platform: iOS as of now
Is real device of platform: false
Operating System: macOS

**Comment by bockc** [comment]
@w10036w I'm currently running into the same issue, did you find a solution ?
I have to restart metro every time it occurs...

React Native Debugger app version: 0.10.6
React Native version: 0.61.5
Platform: iOS & Android
Is real device of platform: true
Operating System: macOS
Xcode version: 11.3.1
build system: Legacy
