### ISSUE TITLE
Waiting for roots to load...

### ISSUE THREAD

**Issue by Vasiliev90** [jhen0409/react-native-debugger#216]
after latest updating got the problem: the React tab shows "Waiting for roots to load ... to reload the inspector [ click here ]"

clicking on the button doesn't change the situation

how to fix it?

<img width="404" alt="2018-03-15 16 38 25" src="https://user-images.githubusercontent.com/6060112/37472599-255bff48-2875-11e8-8b2f-652f03802b12.png">

React Native Debugger app version: 0.7.15
React Native version: 0.45.1
Platform: iOS
Is real device of platform: No
Operating System: macOS

**Comment by jhen0409** [comment]
The new version of RNDebugger have no effects for react-devtools (Still used 2.5.2). Would be helpful if you can provide an example project for reproduce this issue.

**Comment by milesibastos** [comment]
the same here...

**Comment by jhen0409** [comment]
Merge to #218 because it is more clear.
