### ISSUE TITLE
Since version 0.7.14 we always get the application not Rendering and get a Blank screen.

### ISSUE THREAD

**Issue by FranckyBoy1977** [jhen0409/react-native-debugger#218]
Most of the time i get "Waiting for roots to load ..." and the Application is not rendering. Only getting a blank screen.

React Native Debugger app version: 0.7.16
React Native version: 0.45
Platform: IOS
Is real device of platform: Simulator
Operating System: macOS

**Comment by milesibastos** [comment]
The same here...

**Comment by jhen0409** [comment]
Confirmed it is happened on RN 0.45 (or some older versions).

**Comment by jhen0409** [comment]
It should fixed in #219.
