### ISSUE TITLE
[Feature] Remember last state

### ISSUE THREAD

**Issue by artem-russkikh** [jhen0409/react-native-debugger#22]
In my project I don't use Redux, so I have to hide Redux DevTools always when I start React Native Debugger. It would be great if app will remeber my last toggled/untoggled tools.

**Comment by jhen0409** [comment]
> It would be great if app will remeber my last toggled/untoggled tools.

I think it should already in [`v0.5.0`](https://github.com/jhen0409/react-native-debugger/releases/tag/v0.5.0) (by https://github.com/jhen0409/react-native-debugger/commit/e036eaf8d901a8da85c25b556b9195b9973dfb6c), should remember you toggled devtools, it doesn't work for you?

**Comment by artem-russkikh** [comment]
Oh, I have 0.4.0
![image](https://cloud.githubusercontent.com/assets/3540978/20228906/572f6e78-a875-11e6-8ee3-25e34aefa47c.png)
