### ISSUE TITLE
Application crashes after opening inspector

### ISSUE THREAD

**Issue by AndrejGajdos** [jhen0409/react-native-debugger#222]
If I want to "Show Inspector" to inspect UI elements, application crashes with message "Project has stopped". I don't have this issue with default UI inspector in simulator.

React Native Debugger app version: [0.7.17]
React Native version: [0.54.2]
Platform: [Android-Genymotion-2.12.0 -- Google Nexus 5X - 8.0 - API 26 - 1080x1920]
Is real device of platform: [No]
Operating System: [macOS Sierra 10.12.6]

**Comment by jhen0409** [comment]
Is that have any error logs on Android logcat?

**Comment by AndrejGajdos** [comment]
@jhen0409 please close the issue, it doesn't happen now, but I don't why.
