### ISSUE TITLE
Please give me full step by step suggestion for how to debug application on chrome.

### ISSUE THREAD

**Issue by ChirantanPatel** [jhen0409/react-native-debugger#227]
React Native Debugger app version: [FILL THIS OUT]
React Native version: [FILL THIS OUT]
Platform: [FILL THIS OUT: iOS, Android, ...]
Is real device of platform: [Yes or No]
Operating System: [FILL THIS OUT: macOS, Linux, Windows]

**Comment by jhen0409** [comment]
It may not be related to this app, you can ask on [stackoverflow](https://stackoverflow.com/questions/tagged/react-native). I don't know if I misunderstood what you mean.
