### ISSUE TITLE
[Feature] Stay in front

### ISSUE THREAD

**Issue by artem-russkikh** [jhen0409/react-native-debugger#23]
There is no way to turn on "Stay in front" option (or "Always on top")

For example it's possible to enable "Stay in front" option in Xcode Simulator app through `Window > Stay in front`

**Comment by jhen0409** [comment]
@artem-russkikh, Thanks for suggestion! It will be very useful, and it should be simple [for electron](https://github.com/electron/electron/blob/master/docs/api/browser-window.md#winsetalwaysontopflag-level), I'll add to TODOs of `v0.5.1`.

**Comment by jhen0409** [comment]
[v0.5.1](https://github.com/jhen0409/react-native-debugger/releases/tag/v0.5.1) is released, @artem-russkikh please check. :)
