### ISSUE TITLE
[Question] When might we expect to get a new release?

### ISSUE THREAD

**Issue by megalithic** [jhen0409/react-native-debugger#230]
Presently, `0.7.18` has some issues that causes recent Expo SDK versions (v26, v27) to fail to launch the target expo instance.. it just hangs. It looks like there are some commits to master, as of 19 days ago, that just might fix this.

Is there a timeline on releasing a new packaged build? Last one looks to be 2 months old.

Thanks!!!!!!!!!!!!!!

**Comment by jhen0409** [comment]
That latest commit isn't related to the Expo SDK issue, and I tried Expo SDK 27, it works fine for me. I can try to help if you could provide an example project.

**Comment by megalithic** [comment]
@jhen0409 thank you so much!

would you happen to have an example of your workflow/usage of `rndebugger` alongside expo, preferably via the `exp` CLI client?

we execute the following npm scripts, pulled from my package.json:

```json
    "start": "exp start --tunnel -i -c --dev",
    "hit-me": "yarn && yarn rndebugger",
    "rndebugger": "rndebugger-open",
```

specifically, we do this: `yarn hit-me; yarn start`

again, i'd love to see your workflow for firing up react-native-debugger and launching expo.

thanks again!

**Comment by bmakuh** [comment]
Yeah, I've also noticed that when I run `yarn` without the postinstall hook the simulator starts up fine, but if I run `yarn` _with_ the postinstall hook then `yarn start` just hangs before booting up the simulator.

**Comment by megalithic** [comment]
Oh wow, yeah, same exact behavior for me too. It doesn't fire up the metro bundler, and like you said, doesn't fire up the simulator. @jhen0409 please let me know if there is more info I can provide.
