### ISSUE TITLE
ExceptionsManager.js error. Can't get the debugger up and running!

### ISSUE THREAD

**Issue by MimiLau** [jhen0409/react-native-debugger#231]
Can't get the debugger up and running!
It said `failed to parse json: eval:'use strict';` on ExceptionsManager.js:73
![screen shot 2018-05-09 at 5 44 20 pm](https://user-images.githubusercontent.com/12113325/39810001-0e20cdf6-53b6-11e8-90c9-5d6d9fc32369.png)

React Native Debugger app version: 0.3.0
React Native version: 0.52.0
Platform: iOS
Is real device of platform: No
Operating System: macOS

Anyone please help, without debugger life sucks.

**Comment by jhen0409** [comment]
It seems like you're using bundler like Haul (saw the webpack bootstrap), you can follow issue #141. Currently I don't guarantee that it is working properly on Haul.
