### ISSUE TITLE
Feature request - shorten big strings in redux state for improved usability

### ISSUE THREAD

**Issue by hbarylskyi** [jhen0409/react-native-debugger#232]
React Native Debugger app version: [0.7.18]
React Native version: [0.52.2]
Platform: [iOS, Android]
Is real device of platform: [No]
Operating System: [macOS]

Big thanks for your work, the debugger is awesome. 

In our app we have a lot of huge strings being saved to redux state. This makes it hard to explore the redux state tree. This would be much easier if debugger could shorten the strings, e.g.: 

```
propertyName: 'huge string beginning... ...huge string end'
```

These strings may explode into full length on a click.

Screenshot:
<img width="552" alt="screen shot 2018-05-22 at 12 40 04 pm" src="https://user-images.githubusercontent.com/12055535/40354904-b312d5a0-5dbd-11e8-9a9c-bdf2ce091c61.png">

**Comment by Gongreg** [comment]
Hey, this issue should be opened on https://github.com/zalmoxisus/redux-devtools-extension
