### ISSUE TITLE
In redux devtools - if a key is present but value undefined - key is not shown

### ISSUE THREAD

**Issue by Noitidart** [jhen0409/react-native-debugger#233]
In redux devtools - if a key is present but value undefined - key is not shown

React Native Debugger app version: 0.7.18
React Native version: 0.53.3
Platform: Android
Is real device of platform: Yes
Operating System: Windows 10

**Comment by jhen0409** [comment]
You could use [the `serialize` option](http://extension.remotedev.io/docs/API/Arguments.html#serialize) to show the `undefined` key, it should be works by just set `serialize: true`.

**Comment by Noitidart** [comment]
Oh tahnk you so much!
