### ISSUE TITLE
Can it be used with Windows? How to Install this using npm?

### ISSUE THREAD

**Issue by zainulabd786** [jhen0409/react-native-debugger#234]
React Native Debugger app version: [FILL THIS OUT]
React Native version: [FILL THIS OUT]
Platform: [FILL THIS OUT: iOS, Android, ...]
Is real device of platform: [Yes or No]
Operating System: [FILL THIS OUT: macOS, Linux, Windows]

**Comment by jhen0409** [comment]
The [releases](https://github.com/jhen0409/react-native-debugger/releases) page has prebuilt binaries you can use, you can't just install the application by npm.
