### ISSUE TITLE
Cannot Read property 0 of null

### ISSUE THREAD

**Issue by gauravr7** [jhen0409/react-native-debugger#235]
**Cannot Read property 0 of null** error when connected to the react native debugger.

![simulator screen shot - iphone 6 - 2018-05-31 at 07 43 27](https://user-images.githubusercontent.com/6669433/40757497-64376e6a-64a6-11e8-80a4-25c1745bb684.png)

React Native Debugger app version: 0.55.3
React Native version: 0.55.3
Platform: iOS
Is real device of platform: Yes
Operating System: macOS

Package.json: {
  "name": "reactnativepoc",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "contentful": "4.4.0",
    "react": "16.3.1",
    "react-native": "0.55.3",
    "react-native-navigation": "^1.1.464",
    "react-redux": "5.0.7",
    "redux": "4.0.0"
  },
  "devDependencies": {
    "babel-jest": "22.4.3",
    "babel-preset-react-native": "4.0.0",
    "jest": "22.4.3",
    "react-test-renderer": "16.3.1"
  },
  "jest": {
    "preset": "react-native"
  },
  "rnpm": {
    "assets": [
      "./assets/fonts"
    ]
  }
}

**Comment by jhen0409** [comment]
I need more information for reproduce the issue (e.g. An example project). Are you using [haul](https://github.com/callstack/haul)?

**Comment by Kailash23** [comment]
@jhen0409 
This project has the same problem you can check this.
[https://github.com/Kailash23/learn-react-native/tree/d484b9c1cd65e1cda89dcc8c1bdc8a51a2bb7b9e](project link)
