### ISSUE TITLE
Should show functions stored in redux state

### ISSUE THREAD

**Issue by iosdev-republicofapps** [jhen0409/react-native-debugger#237]
React Native Debugger app version: 0.7.18
React Native version: 0.55.2
Platform: iOS
Is real device of platform: Yes
Operating System: macOS 10.13.4

I have Redux state that stores a function as part of the state because that function is a Firebase observer that is needed to later subscribe from watching updates on a key.  Right now, RN Debugger doesn't show the function in the state (no views, not tree, chart or raw) even though ReduxLogger does.  Further RN Debugger incorrectly reports the child count as only 1 when it's really 2 including the function.

My state is something like:
```
{
  myState: {
    value: 12,
    observer: function() {...},
  }
}
```
I don't expect RN Debugger to print out the guts of the function, but at least if it could include it in the child count and maybe print its contents as "function" that would be awesome.  Right now, since it prints nothing for the function and gets the child count wrong, I'm left wondering if my reducers are broken, when the issue is really that RN Debugger is just displaying the state correctly in this case.

I'd be happy to help with a PR if you could give me some hints where to look to fix this?  Or maybe you could fix it more quickly?  :-)  Either way, let me know how I can help and thanks so much for making RN Debugger available, it's really helpful.

**Comment by jhen0409** [comment]
You can use [the `serialize` option](http://extension.remotedev.io/docs/API/Arguments.html#serialize). It should be works by just set `serialize: true`.

**Comment by iosdev-republicofapps** [comment]
Hi, thanks @jhen0409 .  Unfortunately, setting serialize to anything other than `undefined` or `false` causes react-native-debugger to go insane and gobble up enormous amounts of memory.  I have to force kill it in the macos activity monitor and start it again.

I even tried your examples at http://extension.remotedev.io/docs/API/Arguments.html#serialize and
```
import Immutable from 'immutable'; // https://facebook.github.io/immutable-js/
// ...
// Like above, only showing off compose this time. Reminder you might not want this in prod.
const composeEnhancers = typeof window === 'object' && typeof window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ !== 'undefined' ?
 window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__({
   serialize: {
     immutable: Immutable
   }
}) : compose;
```
and they don't work either - they also cause rnd to gobble up tons of memory and become unresponsive - nothing gets rendered and rnd does not respond to mouse clicks in the visual area (although the console still seems to work).  Then it claims that something is "paused in the debugger" which is not true because I'm not using the debugger nor am I pausing anything.

Any ideas?

Would it matter if some of the functions in redux state have references back to store.getState or dispatch?

Thanks

**Comment by iosdev-republicofapps** [comment]
Hmm, I tried to fix this by attaching a `toJSON` method to the function I want serialized, but it appears that RND doesn't honor that when JSON.stringify is applied to functions?

For example:
```
let observer = ... some function ...;
observer.toJSON = () => "some function";
```
I would expect that if my state had
```
{
  observer: observer
}
```
then it would show as
```
{
  observer: "some function"
}
```
in the RND redux inspector.  It does not ... Would that be an easy fix for you?

Thanks!  :-)
