### ISSUE TITLE
Breakpoints removed when code changed

### ISSUE THREAD

**Issue by gagaJay** [jhen0409/react-native-debugger#239]
Hi, This is a great tool for debugging react native but I still encounter this issues.

The break points are all removed when the code is changed. This is super annoying since I have to add the breakpoints back every time. Is there a fix or workaround to address this issue? Or is it just me having this issue? Thank you very much guys.

React Native Debugger app version: 0.7.18
React Native version: 0.55.4
Platform: iOS
Is real device of platform: No
Operating System: macOS

**Comment by mithunm93** [comment]
I'm having the same issue, the breakpoints disappear when I refresh the app. It works on the standard Chrome Devtools, however.

**Comment by sundayha** [comment]
same issue...
```
 React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
      Memory: 4.18 GB / 32.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.14.0 - /usr/local/opt/node@8/bin/node
      npm: 6.4.1 - /usr/local/opt/node@8/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.1 => 16.6.1 
      react-native: 0.57.5 => 0.57.5 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

**Comment by mlostekk** [comment]
Unfortunately same here

**Comment by rkram5424** [comment]
Seconded

**Comment by cs1717c** [comment]
Also having this issue. Great tool, but this ruins everything!

**Comment by mlostekk** [comment]
the only workaround for now is downgrading to `0.8.1`

**Comment by mlostekk** [comment]
This seems to be the commit that breaks it!

https://github.com/jhen0409/react-native-debugger/pull/277/commits/f547f7f6019c471209f7095dcf130c071dff4108

**Comment by jhen0409** [comment]
@mlostekk Thanks for catch! https://github.com/jhen0409/react-native-debugger/commit/b7f0c2dfa880a4ed4743e9eba0c437903e209fcf should fix it, I'll release it later.

**Comment by mlostekk** [comment]
Great! Works like a charm!

**Comment by nabylb** [comment]
I'm on v0.9.4 and still have my breakpoints disappear at app reload. Works on Chrome DevTools.

React Native Debugger app version: 0.9.4
React Native version: 0.56.0
Platform: iOS
Operating System: macOS

**Comment by pkreipke** [comment]
Hmm. I'm using 0.9.8 and breakpoints still disappear. Any other advice?
