### ISSUE TITLE
How to change default port

### ISSUE THREAD

**Issue by navotera** [jhen0409/react-native-debugger#243]
React Native Debugger app version: [0.7.18]
React Native version: [0.55]
Platform: [ Android, ...]
Is real device of platform: [No]
Operating System: [FILL THIS OUT:  Linux,]

How to change default port... my computer use 19002 port but this default port is 19001

thanks

**Comment by jhen0409** [comment]
It should be explained by the [documentation](https://github.com/jhen0409/react-native-debugger/blob/master/docs/getting-started.md), you can change port by New Window, or just use react-native-debugger-open.

**Comment by navotera** [comment]
sorry cannot find where to change **default port on doc** 
what i find is open new tab / windows and  yes confirmed to input new port NOT change default password on the first tab / windows of this tools

**Comment by shide1989** [comment]
same issue here, this should be opened

**Comment by MickaelNeves** [comment]
Read docs...

 "RNDebugger will try connect to debugger proxy, use port 8081 by default, **you can new debugger window (macOS: Command+T, Linux/Windows: Ctrl+T) to specify the port if you want**."

**Comment by checkmatez** [comment]
> Read docs...
> 
> "RNDebugger will try connect to debugger proxy, use port 8081 by default, **you can new debugger window (macOS: Command+T, Linux/Windows: Ctrl+T) to specify the port if you want**."

What if I don't want to do that every time I open the app? I want some setting where I can specify on what port debugger should start when I launch it.

**Comment by manuelbautista** [comment]
Control + T in the React Native Debugger windows, and change the port.

**Comment by matwming** [comment]
command+T in the react native debugger window in mac os and change the port

**Comment by myselfarun1998** [comment]
if you want to change the the Port **Press ctrl+T** to change the port and the default port is 8081 you want to change that every time opening  follow my steps:  open react-native debugger > select debugger menu on the Top > Open Config file > there change 8081 to 8082 your  version
