### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by liuqiang1357** [jhen0409/react-native-debugger#249]
I am using RN debugger with mobx-remotedev. When I combine mulitple store to one and pass root reference to child, it will give this error. For example like this:
```
class UserStore {...}
class TodosStore {...}

class Store {
    constructor() {
        this.user = new UserStore(this);
        this.todos = new TodosStore(this);
    }
}
```
When I remove this, the problem went away. I think RN debugger cannot handle circular dependency.

React Native Debugger app version: v0.7.18
React Native version: 0.55.4
Platform: iOS and Android
Is real device of platform: Yes
Operating System: macOS 10.13.6

**Comment by Gongreg** [comment]
Hello. This issue is quite old and not really clear. So we are closing it. Feel free to write a comment to reopen it.

**Comment by tyleralves** [comment]
I'm also experiencing this issue.

Based on this very specific case, I am assuming that circular references cause `react-native-debugger` to freeze and eventually crash with the error in the title `Maximum call stack size exceeded`. 

Steps to reproduce:
1. Create a store with a circular reference (a possible pattern is outlined by @liuqiang1357)
2. Click on any in the Redux devtools pane

Issue:
The standalone devtools freezes for ~15 seconds, then `Paused before potential out-of-memory crash`

Screenshot:
![Screen Shot 2019-06-21 at 4 08 09 PM](https://user-images.githubusercontent.com/13406078/59955431-f8872380-943e-11e9-89f4-5db77e8a6f81.png)

@Gongreg What further information can I provide to flush this out?

**Comment by arthedza** [comment]
Are any updates for this issue?
