### ISSUE TITLE
It does not let me change port on linux. Following error I am getting

### ISSUE THREAD

**Issue by shubhamdeol** [jhen0409/react-native-debugger#252]
\Cannot read property 'x' of undefined
    at F (/home/shubham-deol/ReactNative/react native tools/resources/app.asar/main.js:1:93678)

**Comment by codejamninja** [comment]
I'm am getting this same error on mac when I try and open a new window.

**Comment by shubhamdeol** [comment]
Try using their previous versions, It helped for me.

**Comment by codejamninja** [comment]
Ok, thanks, I will. However, that doesn't fix the bug in the software.

**Comment by Gongreg** [comment]
Hey, do you still get this error?

**Comment by madox2** [comment]
I am having the same issue when trying to open new window (on Ubuntu 18.04)

**Comment by RyanTG** [comment]
I get this error with 10.5.1. I haven't tried any other versions.

**Comment by JoshuaKGoldberg** [comment]
I still get this with a fresh install of v0.10.5 on a macOS Catalina 10.15.1. Pressing <kbd>Cmd</kbd>+<kbd>t</kbd> on the keyboard creates a popup window with:

**A JavaScript error occurred in the main process**

```
Uncaught Exception:
TypeError: Cannot read property 'x' of undefined
    at Ee (/Applications/React Native Debugger.app/Contents/Resources/app.asar/main.js:2:252980)
    at /Applications/React Native Debugger.app/Contents/Resources/app.asar/main.js:10:2608
    at MenuItem.click (electron/js2c/browser_init.js:1513:9)
    at Function.executeCommand (electron/js2c/browser_init.js:1774:13)
```

**Comment by htanjo** [comment]
I encountered this issue as well when I open React Native Debugger for the first time, but it doesn't reproduce from the second time. I think it's caused by missing config.json.

I'm going to send a PR to fix it.
