### ISSUE TITLE
unknown call: "profiler:update"

### ISSUE THREAD

**Issue by danilobuerger** [jhen0409/react-native-debugger#256]
React Native Debugger app version: 0.7.20
React Native version: 0.57.0-rc.4
Platform: Android
Is real device of platform: Yes
Operating System: macOS and Linux

After upgrading react-native from 0.55 to 0.57 I am constantly seeing

![screenshot from 2018-09-06 13-07-55](https://user-images.githubusercontent.com/996231/45153893-eb61b680-b1d5-11e8-83f5-111098b44455.png)

**Comment by jhen0409** [comment]
I've yet to use RN 0.57-rc, but I guess it may related to new profiler feature of `react-devtools`. We need to upgrade the version of `react-devtools` in RNDebugger.

**Comment by jacob-israel-turner** [comment]
@jhen0409 I'm looking at upgrading my project to React Native 0.57, so I can use the new profiler - are you planning on implementing the profiler in this project?

**Comment by Freddy03h** [comment]
PR : https://github.com/jhen0409/react-native-debugger/pull/262

**Comment by jhen0409** [comment]
Released as `v0.8.0`.
