### ISSUE TITLE
Redux panel not working

### ISSUE THREAD

**Issue by fkereki** [jhen0409/react-native-debugger#259]
The Redux debugger doesn't work - but the others panels work perfectly well.

I googled, and found this issue, related to `remote-redux-devtools`: https://github.com/zalmoxisus/remote-redux-devtools/issues/117

By using `remote-redux-devtools-sp`, I *can* connect using the browser.

The attached screenshot shows the other two panels working, but the Redux one non-functional.

![image](https://user-images.githubusercontent.com/2468063/45749246-703ece00-bbe1-11e8-9a4b-207424face20.png)

The independent Redux tool works:

![image](https://user-images.githubusercontent.com/2468063/45749556-636eaa00-bbe2-11e8-95e6-532ac3a809eb.png)

My environment data:

React Native Debugger app version: 1.1.0
React Native version: 0.55.4
Platform: ANDROID
Is real device of platform: NO
Operating System: LINUX

**Comment by jhen0409** [comment]
You need to use [the API from redux-devtools-extension](https://github.com/jhen0409/react-native-debugger/blob/master/docs/redux-devtools-integration.md), this integration isn't work with `remote-redux-devtools`.

**Comment by KEMBL** [comment]
@jhen0409 `remote-redux-devtools` looks like still broken. Do you probably know, is there a way to debug android react native app remotely with `redux-devtools-extension`?
