### ISSUE TITLE
Could not read from localStorage. SyntaxError: Unexpected token C in JSON at position 0

### ISSUE THREAD

**Issue by EskelCz** [jhen0409/react-native-debugger#267]
React Native Debugger app version: 0.8.0
React Native version: 0.55.1
Platform: iOS
Is real device of platform: Yes
Operating System: macOS

After the debugger updated to the latest version, I started getting this error (in console):

![Could not read from localStorage](https://i.imgur.com/tY87T4L.png)

I'm using ejected react native and react native navigation, otherwise nothing out of the ordinary I guess

**Comment by jhen0409** [comment]
It’s from the new version of react-devtools, you can try to reset local storage and restart again.

**Comment by jhen0409** [comment]
It's now on the release note.

**Comment by smirea** [comment]
still no luck, I cleared Local Storage and a full "Clear Site Data". 
Note: I'm getting the "Cannot parse JSON" message, but it's not prefixed by "Could not read from local storage"

<img width="655" alt="screen shot 2018-10-01 at 3 51 41 pm" src="https://user-images.githubusercontent.com/544097/46320198-0c79b500-c592-11e8-9038-4a1c9c154765.png">

**Comment by lucianomlima** [comment]
This is another error.

**Comment by jordanmkoncz** [comment]
To make it clear for others, below is a screenshot showing where you need to go to clear local storage of React Native Debugger, which will fix this error. You do not need to clear the AsyncStorage of your app itself.

<img width="576" alt="screen shot 2018-10-02 at 3 02 36 pm" src="https://user-images.githubusercontent.com/3453584/46330043-40b5aa00-c654-11e8-9e68-34b99bb551a5.png">

**Comment by jhen0409** [comment]
Please open an another issue with details for tracking the JSON.parse error of WebSocket message.

**Comment by smirea** [comment]
@fronteed if you want a patch-work solution, you can download the source code for 7.10, open `electron/update.js` and put a `return` at the beginning of the function, you can then build it with `scripts/package-macos.sh` and just run that

sorry for the hack-job, but having your devtool force update in the middle of development is a cause for desperate measures
