### ISSUE TITLE
Uncaught SyntaxError: Unexpected token a in JSON at position 0

### ISSUE THREAD

**Issue by fronteed** [jhen0409/react-native-debugger#270]
![image](https://user-images.githubusercontent.com/1612675/46332931-0255c600-c627-11e8-944b-4d1dddf575a3.png)

I've tried to clear the storage https://github.com/jhen0409/react-native-debugger/issues/267#issuecomment-426150024, but this doesn't fix the issue, I'm still getting an endless cycle of errors.
I've also tried to rebuild the app, nothing changed.

React Native Debugger version: v0.8.0
React Native version: v0.37.0 (can't be updated) 
Is real device of platform: Xcode Simulator (iPad Pro) 
Operating System: macOS
Xcode: v9.3 (9E145)

This may occur because of the outdated version of React Native.
We may need an option to ignore an upcoming Debugger update. Even if I install an older version, it updates itself on next reboot.

**Comment by jhen0409** [comment]
> This may occur because of the outdated version of React Native.

Yes, we've no longer supported RN 0.37 on react-devtools. :(

See [the documentation](https://github.com/jhen0409/react-native-debugger/blob/master/docs/react-devtools-integration.md#react-devtools-integration).

> We may need an option to ignore an upcoming Debugger update. Even if I install an older version, it updates itself on next reboot.

It looks like a bug, it should have prompt for update, shouldn't be forced. I may consider to release a patch version for `v0.7`.

**Comment by fronteed** [comment]
> It looks like a bug, it should have prompt for update, shouldn't be forced. I'll consider to release a patch version for v0.7.

It prompts the update, but updates itself on reboot when I press Later.

**Comment by sachinB94** [comment]
@jhen0409 We're also facing the same issue. The `autoUpdate` field in config file doesn't seem to work with v0.7.20.

React Native Debugger version: v0.7.20
React Native version: v0.42.0

**Comment by jhen0409** [comment]
@sachinB94 yep, it's new feature in `0.8.0`.

**Comment by Nemo108** [comment]
@jhen0409 We need some kind of a workaround asap. RND updates automatically every time you reboot your machine. Maybe there is a hacky way out of this situation? Please point us to the right direction.

**Comment by sachinB94** [comment]
@jhen0409 How about releasing another update for 0.7.x with the support for config file (just the `autoUpdate` field) ?

Or, if it's too much, could you point to the code, where update is being checked, so that we can change the source and build it ourselves ?

**Comment by jhen0409** [comment]
#272 will fix the update issue.

> Or, if it's too much, could you point to the code, where update is being checked, so that we can change the source and build it ourselves ?

In the docs of contributing.

**Comment by jhen0409** [comment]
Please try [`v0.7.21`](https://github.com/jhen0409/react-native-debugger/releases/tag/v0.7.21).

**Comment by Glebasty8** [comment]
@jhen0409 how to downgrade version to 0.7.21?

**Comment by sachinB94** [comment]
@jhen0409 Great. It works fine.

**Comment by evanjmg** [comment]
I'm still getting this - with RN 0.57.1 and 0.9.7 :(

**Comment by evanjmg** [comment]
I get this with RN 0.57.1 and latest (0.9.7) when I receive an html response with a 502 - really annoying to debug my issues
