### ISSUE TITLE
Cannot reload app since upgrading RN from 0.54.4

### ISSUE THREAD

**Issue by vrgimael** [jhen0409/react-native-debugger#274]
Hi, did some research but couldn't find this issue anywhere else, maybe I'm just being silly.

Basically, I've been using react-native 0.54.4 for a while and decided to upgrade straight to 0.57.2 to get rid of some bugs. 

Since upgrading, I am not able to reload the app through the React Native Debugger window by pressing cmd + R. 

The right click context menu doesn't show the "reload" option anymore either.

Is this a bug or is this something you guys actually removed? And is there any way to have it back there? It's pretty useful.

React Native Debugger app version: 0.8.1
React Native version: 0.57.2
Platform: iOS
Is real device of platform: Real device
Operating System: MacOS Mojave

Thanks!

**Comment by jhen0409** [comment]
Feel free to reopen this if you still getting the same issue in latest version of RNDebugger.

**Comment by vrgimael** [comment]
Latest version fixed this, thanks!
