### ISSUE TITLE
RN 0.57.2 - Navigator is deprecated error

### ISSUE THREAD

**Issue by stevesouth** [jhen0409/react-native-debugger#279]
React Native Debugger app version: 0.8.1
React Native version: 0.57.2
Platform: ios
Is real device of platform: no
Operating System: macOS

I can't quite see why, but the debugger ends up trying to call get Navigator during a redux action which is now deprecated in 0.57.

// Deprecated
  get Navigator() {
    invariant(
      false,
      'Navigator is deprecated and has been removed from this package. It can now be installed ' +
        'and imported from `react-native-deprecated-custom-components` instead of `react-native`. ' +
        'Learn about alternative navigation solutions at http://facebook.github.io/react-native/docs/navigation.html',
    );
  },

**Comment by jhen0409** [comment]
We don't have any extra code to call get Navigator. You may need to check your project.
