### ISSUE TITLE
It looks like you are passing several store enhancers to createStore()

### ISSUE THREAD

**Issue by learnlapp** [jhen0409/react-native-debugger#280]
React Native Debugger app version: v0.8.1
React Native version: 0.57.3
Platform: iOS
Is real device of platform: No
Operating System: macOS

I am getting this error

`It looks like you are passing several store enhancers to createStore(). This is not supported. Instead, compose them together to a single function`

It was working before I updated from 0.55.

This is how I create my store.

```
import { createStore, compose, applyMiddleware } from 'redux';
import thunk from 'redux-thunk';
import reducers from '../reducers';

const store = createStore(
  reducers,
  window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__(),
  compose(applyMiddleware(thunk)),
);

export default store;


```

It works fine when I use Chrome to debug. 

Please help, thanks

**Comment by TomboFry** [comment]
I've just had this same problem with almost exactly the same code, and have managed to fix it.

Instead of passing three arguments to the `createStore` function, you need to pass two. To get around that, while still using the redux dev tools, you need to use the dev tools as the composer itself:

```javascript
import { createStore, compose, applyMiddleware } from 'redux';
import thunk from 'redux-thunk';
import reducers from '../reducers';

const composeEnhancer = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;

const store = createStore(
  reducers,
  composeEnhancer(applyMiddleware(thunk)),
);

export default store;
```

I realised this was the solution after digging around the redux library's, the debugger app's, and the dev tool's source code, and found this section: https://github.com/zalmoxisus/redux-devtools-extension#12-advanced-store-setup

Hope this helps!

**Comment by learnlapp** [comment]
Thanks @TomboFry

**Comment by firstred** [comment]
Thanks so much @TomboFry!

**Comment by tonywong625** [comment]
Getting the same error however my store has a few more object in createStore and dont know how to fix it :/ 

```
import {createStore, applyMiddleware, compose} from "redux";
import thunk from "redux-thunk";
import rootReducer from "./reducers/rootReducer";
import { createBrowserHistory } from 'history'
import { connectRouter, routerMiddleware } from 'connected-react-router'

export const history = createBrowserHistory()

const composeEnhancers = (window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__()) || compose;

export default function configureStore(initialState = {}) {
  return createStore(
    connectRouter(history)(rootReducer), // new root reducer with router state
    composeEnhancers,
    compose(
      applyMiddleware(
        routerMiddleware(history), // for dispatching history actions
        thunk
        // ... other middlewares ...
      ),
    ),
    rootReducer // Need to be under middleware
  );
}
```

**Comment by MuhammadSulman** [comment]
> const composeEnhancer = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;

it does work

**Comment by SirFart4lot** [comment]
redux dev tool extension wrap your actions with it's own action, what you can do is change the oreder of the middlewares load,
`const store = createStore(
    rootReducer,
    compose(
        applyMiddleware(
            /* ----  middlewares ----  */
           
        ),
        window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__(),
    )
);`

if you place the the redux devtools middleware before your middlewares, you will get the warped action.

**Comment by Ethanng329** [comment]
> composeEnhancer(applyMiddleware(thunk)),

it works ,thanks

**Comment by tuanluu-agilityio** [comment]
It's saved my time
```
const composeEnhancer = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;
```
Thanks,

**Comment by nicollasmatheus** [comment]
work like a charm thks @TomboFry

**Comment by AndrewZou** [comment]
For React 16, you may just use function composeWithDevTools( applyMiddleWare( thunk, logger )). Code block as below.

import { createStore, combineReducers, applyMiddleware } from 'redux';
import { composeWithDevTools } from 'redux-devtools-extension';
import thunk from 'redux-thunk';
import logger from 'redux-logger';

const store = createStore(
        combineReducers({
            dishes: Dishes,
            comments: Comments,
            leaders: Leaders,
            promotions: Promotions
        }), composeWithDevTools( applyMiddleware(thunk, logger) )
    );

**Comment by osamasayed** [comment]
> import { createStore, combineReducers, applyMiddleware } from 'redux';
> import { composeWithDevTools } from 'redux-devtools-extension';
> import thunk from 'redux-thunk';
> import logger from 'redux-logger';
> 
> const store = createStore(
> combineReducers({
> dishes: Dishes,
> comments: Comments,
> leaders: Leaders,
> promotions: Promotions
> }), composeWithDevTools( applyMiddleware(thunk, logger) )
> );

```
import { createStore, applyMiddleware } from "redux";
import { composeWithDevTools } from "redux-devtools-extension";

const store = createStore(
  allReducers,
  composeWithDevTools(applyMiddleware(thunk, sagaMiddleware))
);
```

Works like a charm thanks a lot!!

**Comment by fg0611** [comment]
> I've just had this same problem with almost exactly the same code, and have managed to fix it.
> 
> Instead of passing three arguments to the `createStore` function, you need to pass two. To get around that, while still using the redux dev tools, you need to use the dev tools as the composer itself:
> 
> ```js
> import { createStore, compose, applyMiddleware } from 'redux';
> import thunk from 'redux-thunk';
> import reducers from '../reducers';
> 
> const composeEnhancer = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;
> 
> const store = createStore(
>   reducers,
>   composeEnhancer(applyMiddleware(thunk)),
> );
> 
> export default store;
> ```
> 
> I realised this was the solution after digging around the redux library's, the debugger app's, and the dev tool's source code, and found this section: https://github.com/zalmoxisus/redux-devtools-extension#12-advanced-store-setup
> 
> Hope this helps!

Thanks! it worked!
