### ISSUE TITLE
Cannot read property 'displayName' of null

### ISSUE THREAD

**Issue by tannera** [jhen0409/react-native-debugger#287]
Since upgrade to RN 0.57.5 and the latest React, the following issue arose upon running React Native Debugger and starting the App:

`ExceptionsManager.js:84 Warning: React DevTools encountered an error: TypeError: Cannot read property 'displayName' of null`.

I believe it is linked to https://github.com/facebook/react-devtools/issues/1195 and https://github.com/facebook/react-devtools/issues/1168

React Native Debugger app version: 0.8.1
React Native version: 0.57.5
Platform: iOS AND Android
Is real device of platform: Simulator and Real device in debug mode
Operating System: macOS

**Comment by phil-flyclops** [comment]
As a heads up, I did a local build with the version of react devtools upgraded to 3.4.2 in line with part of the discussion infacebook/react-devtools#1168 and it did not resolve the issue

**Comment by owinter86** [comment]
Also as a heads up, This error only occurs with React Devtools toggled, so disabling that will still allow you to use the console and Redux Devtools. I can also confirm upgrading react devtools does not solve this issue.

**Comment by dan-lee** [comment]
I don't fully understand where a fix has to be deployed, but is there anything we could do on our end?
Because that bug is currently blocking me (_and probably others_) using this very useful app.
