### ISSUE TITLE
EXTREMELY long delay 

### ISSUE THREAD

**Issue by crobinson42** [jhen0409/react-native-debugger#288]
React Native Debugger app version: `0.8.1`
React Native version: `0.57.4`
Platform: Android
Is real device of platform: real/physical
Operating System: MacOS

Related to #139 I experience an extremely long delay (30-60 seconds) on any interactions or instructions. I tried solultion mentioned in #139 to disabled React Dev Tools but that didn't solve anything.

I resolved this issue when I set both my MacOS and Android device to use the same time sync server (`time.apple.com`).

It's important to mention that this happens without `react-native-debugger` running so I believe this is a `react-native` core bug, I'm simply posting to help others navigate or find aid.

Ref: https://stackoverflow.com/questions/42142933/react-native-debugger-is-too-slow

**Comment by icxcat** [comment]
I resolved this issue by right click and Toggle React DevTools
