### ISSUE TITLE
Warning: unknown call: "relay:check"

### ISSUE THREAD

**Issue by Ashoat** [jhen0409/react-native-debugger#291]
This is a specific instance of this issue: https://github.com/facebook/react-devtools/issues/1233

It occurs because of a mismatch of versions of `react-devtools-core` between this package and React Native. Recent versions of React Native use `react-devtools-core@3.4.3`, but the most recent version of React Native Debugger is on `react-devtools-core@3.4.2`. I'm not sure why 3.4.3 introduces this issue.

React Native Debugger app version: 0.8.1
React Native version: 0.57.7
Platform: iOS, Android
Is real device of platform: Simulator/emulator
Operating System: macOS

**Comment by vovkasm** [comment]
Released version of react-native-debugger is on 3.4.0 according to this: https://github.com/jhen0409/react-native-debugger/blob/v0.8.1/yarn.lock#L6894

Sure it should get update.

**Comment by servocoder** [comment]
Any workaround on this until the package gets updated?

**Comment by phil-flyclops** [comment]
Popped up a PR to upgrade

**Comment by jhen0409** [comment]
Released as [`v0.8.2`](https://github.com/jhen0409/react-native-debugger/releases/tag/v0.8.2).
