### ISSUE TITLE
Unable to clear cookies for website

### ISSUE THREAD

**Issue by terreb** [jhen0409/react-native-debugger#293]
I'm unable to clear cookies for network requests. I make the fist request (using XMLHttpRequest and  I'm not setting request cookies there) and as it should be for the first request all is good cookies are not sent. Then I go to Application tab -> Cookies to check whether any cookies were saved on respons, it's empty, so I assume they are not saved. When I send the second request to the same pageI see that request cookies are sent. How come? How to clear them? Restarting debugger doesn't help they still are being sent.

React Native Debugger app version: 0.8.1
React Native version: 0.56.0
Platform: iOS
Operating System: macOS

**Comment by jhen0409** [comment]
The `Application tab -> Cookies` is only work for Network Inspect enabled, if you're not using that, you need to use another way to clear cookies.
