### ISSUE TITLE
Network Inspect adds `Origin: null` header (messing with CORS)

### ISSUE THREAD

**Issue by denisw** [jhen0409/react-native-debugger#296]
React Native Debugger app version: 0.8.1
React Native version: 0.57.7
Platform: iOS
Is real device of platform: No
Operating System: macOS

Whenever I enable "Network Inspect" in React Native Debugger, requests have an extra `Origin: null` header. This causes our backend's CORS protection to kick in, resulting in 403 responses. If possible, I'd rather have RN Debugger pass no `Origin` header at all, or at least make the `Origin` configurable.

**Comment by rajat-np** [comment]
@denisw I don't see any Origin header in the request headers when Network Inpect is enabled.

**Comment by nol13** [comment]
we're just setting ours to an empty string for now

**Comment by rajat-np** [comment]
@nol13 , axios can be the reason because I am using native fetch

**Comment by denisw** [comment]
Axios could indeed be the reason because it uses the `XMLHttpRequest` API instead of `fetch`. Perhaps that leads to the `Origin: null` somehow ending up in the request.

**Comment by Lughino** [comment]
It's clearly a problem related to the debugger with network inspect, when the network inspect is off any request is performed properly.
Also, this happens to graphql as well, that internally use `fetch`.
