### ISSUE TITLE
RN not connecting after upgrading to 0.5.3

### ISSUE THREAD

**Issue by asgvard** [jhen0409/react-native-debugger#30]
Hi,

First of all thank you for amazing package that includes everything needed for RN development in one app :)
Today I got an automatic upgrade to 0.5.3 version on my MacOS Sierra, and after this upgrade my RN project connecting to Debugger only for the first load. But when I reload the RN app (with Live reload or manually with Cmd+R) it couldn't connect to Debugger anymore.
Also I can see a JS errors related to the Redux chart tree building. Not sure if it's related to the not reloading issue though.

<img width="666" alt="screen shot 2016-11-25 at 22 27 18" src="https://cloud.githubusercontent.com/assets/2877657/20635564/ef3b6458-b35e-11e6-84fe-001069e8b4df.png">

**Comment by jhen0409** [comment]
Thanks for report!

> Also I can see a JS errors related to the Redux chart tree building. Not sure if it's related to the not reloading issue though.

It does appear at v0.5.3, and it looks broken the JS reload, I'll update `remotedev-app` to v0.10 stable and release v0.5.4 at later.

**Comment by zalmoxisus** [comment]
It's fixed in https://github.com/romseguy/d3-state-visualizer/pull/11. You can just update `d3-state-visualizer@1.3.1` for now.

**Comment by jhen0409** [comment]
It should fixed in [`v0.5.4`](https://github.com/jhen0409/react-native-debugger/releases/tag/v0.5.4).
