### ISSUE TITLE
Chocolatey installer

### ISSUE THREAD

**Issue by atrauzzi** [jhen0409/react-native-debugger#303]
Would love to see a chocolatey package for Windows based installs!

https://chocolatey.org/

♥

**Comment by caiodeambrosio** [comment]
Please guys throw the chocolatey package

**Comment by BunnyTheLifeguard** [comment]
That would be very nice, yes.

**Comment by atrauzzi** [comment]
Would rather see this done: https://github.com/jhen0409/react-native-debugger/issues/85

People should be running linux anyway.
