### ISSUE TITLE
Ignoring library 

### ISSUE THREAD

**Issue by pvpshoot** [jhen0409/react-native-debugger#31]
Hi, how about Ignoring library code in call stack on breakpoints?
chrome just have an experimental setting for it: 'Enable frameworks debugging support';
and i can add some libs to blacklist;
Usually  i don't want to see the guts of React or Redux

**Comment by jhen0409** [comment]
You can add a pattern to `blackboxing` tab:

![2016-11-30 4 39 39](https://cloud.githubusercontent.com/assets/3001525/20728094/27cf1f16-b6b7-11e6-800f-44370027499a.png)

If you want only blackboxing `react` and `redux`, add `node_modules/(react|redux)` should work.

**Comment by pvpshoot** [comment]
Oh, thank you.
My mistake is that i didn't see setting menu,
Sorry for this stupid question!
