### ISSUE TITLE
Unable to copy or paste in the Console

### ISSUE THREAD

**Issue by rsml** [jhen0409/react-native-debugger#310]
React Native Debugger app version: 0.9.0
React Native version: 0.57.8
Platform: iOS
Is real device of platform: No
Operating System: macOS

After updating from React Native Debugger v0.8.3 to v0.9.0, I can no longer copy and paste content in the Console area. I didn't change anything else.

Thanks!

**Comment by jhen0409** [comment]
v0.9.0 got an exception for launching application. It should working on v0.9.1.
