### ISSUE TITLE
0.9.0 IllegalStateException with Apollo on Android

### ISSUE THREAD

**Issue by danilobuerger** [jhen0409/react-native-debugger#311]
React Native Debugger app version: 0.9.0
React Native version: 0.57.8
Platform: Android 9
Is real device of platform: Real Pixel 3
Operating System: macOS 10.13.6

Ref: 
* https://github.com/jhen0409/react-native-debugger/pull/298
* https://github.com/apollographql/apollo-client/pull/4386

When I select "Debug JS remotely", React Native Debugger connects, works for a second, shows the console output:

> [React DevTools] Connected
> [React DevTools] Connection to RN closed

Then a red box appears on the device:

> IllegalStateException: Expected a name but was STRING

Works on 0.8.3 without a problem.

**Comment by jhen0409** [comment]
Sorry about that, I got something wrong in packaged app. It should working on v0.9.1.

**Comment by danilobuerger** [comment]
@jhen0409 Same error on 0.9.1

**Comment by danilobuerger** [comment]
Side not: It works with a real iOS Device. Seems to be an Android problem.

**Comment by amwill04** [comment]
Can confirm still issue on `0.9.1`.

**Comment by Gongreg** [comment]
@jhen0409 already pushed a fix, but the version wasn't released yet.

**Comment by jhen0409** [comment]
`v0.9.2` have been released. It's included the bug fix about this. :)
