### ISSUE TITLE
No way to access Redux Devtools settings

### ISSUE THREAD

**Issue by mmavko** [jhen0409/react-native-debugger#319]
I need to change "Limit the action history" parameter to a greater number than default 50. How can I do this?

React Native Debugger app version: 0.9.4
React Native version: 0.57.5
Platform: Android
Is real device of platform: Yes
Operating System: macOS

**Comment by jhen0409** [comment]
You can use the [`manage`](http://extension.remotedev.io/docs/API/Arguments.html#maxage) option.

**Comment by JulianKingman** [comment]
@jhen0409 looks like your link was hijacked. How does one set the maxage setting in react native? Is the only way through the dev tools extension middleware, or is there an environment variable that can be set on launch, or a setting within the app?

**Comment by jhen0409** [comment]
> @jhen0409 looks like your link was hijacked. How does one set the maxage setting in react native? Is the only way through the dev tools extension middleware, or is there an environment variable that can be set on launch, or a setting within the app?

The [repo docs](https://github.com/jhen0409/react-native-debugger/blob/master/docs/redux-devtools-integration.md) could help to visit the docs of redux-devtools-extension. ([`maxage`](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#maxage))

**Comment by JulianKingman** [comment]
That did it, thanks! In case anyone is wondering how to apply maxAge, there's instructions on how to invoke the debugger with options here: https://github.com/zalmoxisus/redux-devtools-extension
