### ISSUE TITLE
Uncaught SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by ekimlinger** [jhen0409/react-native-debugger#325]
React Native Debugger app version: 0.9.5
React Native version: 0.56.0 w/o expo,
Platform: iOS
Is real device of platform: No, iPhone 8 Plus simulator 
Operating System: Mac

Was running the debugger just fine on a previous version (most likely 0.9.4, as I try to keep utd, could have been 0.9.3 though), and immediately after upgrading versions I see the error message below.

Attempted restarting everything: simulator, packager/bundler, debugger. No dice. 

Please let me know if I need to gather more info in order to troubleshoot or what to try. 

Also, thank you for creating/maintaining such a great package! 

![simulator screen shot - iphone 8 plus - 2019-02-15 at 23 19 21](https://user-images.githubusercontent.com/15257582/52894997-2e5a8980-3179-11e9-9871-4e811e5380b1.png)

**Comment by emiletobias** [comment]
Got the same issue on React Native version 0.55, React Native Debugger app version: 0.9.5.

Stack of the error: 
"Error: Uncaught SyntaxError: Unexpected identifier
    at executeApplicationScript (file:///Applications/React%20Native%20Debugger.app/Contents/Resources/app.asar/js/RNDebuggerWorker.js:1:93479)
    at e (file:///Applications/React%20Native%20Debugger.app/Contents/Resources/app.asar/js/RNDebuggerWorker.js:1:93937)"

**Comment by jhen0409** [comment]
It should be fixed and released as [`v0.9.6`](https://github.com/jhen0409/react-native-debugger/releases/tag/v0.9.6).

**Comment by ekimlinger** [comment]
It works! Thank you @jhen0409 !
