### ISSUE TITLE
Release version 0.9.6 fails to start on macOS

### ISSUE THREAD

**Issue by fo-fo** [jhen0409/react-native-debugger#326]
React Native Debugger app version: 0.9.6
Operating System: macOS 10.14.3

I get the following error when trying to start React Native Debugger downloaded from the GitHub Releases page (https://github.com/jhen0409/react-native-debugger/releases):

`“React Native Debugger” is damaged and can’t be opened. You should move it to the Trash.`

**Comment by jhen0409** [comment]
Sorry about that, I've re-upload the binaries.
