### ISSUE TITLE
DevMenu - AsyncStorage not working (Android)

### ISSUE THREAD

**Issue by wuifdesign** [jhen0409/react-native-debugger#327]
React Native Debugger app version: 0.9.6
React Native version: 0.58.3
Platform: Android
Is real device of platform: No
Operating System: macOS

---

"Clear AsyncStorage" isn't working and clicking "Log AsyncStorage content" produces following error:

```
RNDebuggerWorker.js:1 Uncaught (in promise) TypeError: Cannot read property 'map' of null
    at v.showAsyncStorage.e (RNDebuggerWorker.js:1)
    at <anonymous>
```

**Comment by jhen0409** [comment]
It already fixed in https://github.com/jhen0409/react-native-debugger/commit/55c3c195264de16d4261e1ee888e047614e250dd (It not only for 0.59), I'll release it later.

**Comment by abhirup03** [comment]
@jhen0409  I am facing the same issue when I run my app on an android device. AsyncStorage doesn't work. Can you help me out and provide a fix?

**Comment by MrOggy85** [comment]
The same issue happens on iOS too

React Native Debugger app version: 0.9.10
React Native version: ^0.59.9
Platform: iOS
Is real device of platform: No
Operating System: macOS

I'm also using @react-native-community/async-storage: ^1.5.0

**Comment by domingowensnsoft** [comment]
I also had this problem
react native debugger app version: 
react native version: 0.58.6
platform: ios
