### ISSUE TITLE
rndebugger-open doesn't work on RN 0.59

### ISSUE THREAD

**Issue by jpaas** [jhen0409/react-native-debugger#328]
React Native Debugger app version: 0.9.7
React Native version: 0.59.0-rc.2
Platform: all
Is real device of platform: no
Operating System: macOS

Error: `FAIL Replace `open debugger-ui with Chrome` to `open React Native Debugger`, the file 'local-cli/server/middleware/getDevToolsMiddleware.js' not found.`

Looks like RN 0.59 has moved to `@react-native-community/cli/build/server/middleware/getDevToolsMiddleware.js`

**Comment by jhen0409** [comment]
Is [v0.3.18](https://github.com/jhen0409/react-native-debugger/commit/a61b9586c3891b982376c0798928ab6d45a1362e) not work for you? It updated recently for support RN 0.59.

**Comment by jhen0409** [comment]
I confirmed your error is from the old version of `react-native-debugger-open`, so I'll close the issue.

**Comment by jpaas** [comment]
Confirmed. Once I upgraded to 0.3.18 was fine. Thanks.
