### ISSUE TITLE
Unable to figure out how to initialize properly to store, different from examples

### ISSUE THREAD

**Issue by GeoffreyPlitt** [jhen0409/react-native-debugger#33]
I'm trying to add these tools to a react-native project at https://github.com/GeoffreyPlitt/RN-NavigationExperimental-Redux-Example/blob/master/app/app.js

The store construction (with middleware etc) doesn't quite follow the examples you guys have, and every combination I've tried leads to confusing errors.

Is it easy to point out the proper way to do it? If not, I can put together a few branches showing my attempts and the error messages I'm getting.

**Comment by jhen0409** [comment]
```js
const createStoreWithMiddleware = applyMiddleware(thunk)(createStore)
const store = createStoreWithMiddleware(reducers)
```

Looks like it's old usage of redux `createStore`, you should take a look at the current [API reference](http://redux.js.org/docs/api/createStore.html). However, it shouldn't be difficult to migrate [here](https://github.com/jhen0409/react-native-debugger#advanced-store-setup).

**Comment by GeoffreyPlitt** [comment]
Perfect, thanks!
