### ISSUE TITLE
react-native-debugger-open syntax error on RN 0.59.0-rc.3

### ISSUE THREAD

**Issue by jpaas** [jhen0409/react-native-debugger#330]
React Native Debugger app version: NA - can't start metro
React Native version: 0.59.0-rc.3
Platform: NA - can't start metro
Is real device of platform: NA
Operating System: macOS

using react-native-debugger-open 0.3.18 with RN 0.59.0-rc.3 I can't start the metro bundler because of the following syntax error caused by the rndebugger-open postinstall...

```
yarn run v1.13.0
$ node node_modules/react-native/local-cli/cli.js start --reset-cache
/Users/jpaas/Documents/osaaru/tapshot-react/node_modules/@react-native-community/cli/build/server/middleware/getDevToolsMiddleware.js:86
dule', {
    ^^^^

SyntaxError: Invalid or unexpected token
```

**Comment by RemyLivewall** [comment]
I am experiencing the same issue on react-native 0.59 stable. Once I remove the post-install action, the problem is solved.

**Comment by v0lume** [comment]
@jhen0409 any updates on this? in #333 i describe another error and i don't think it's related to this issue. i still can't use react-native-debugger-open with RN  0.59

**Comment by jhen0409** [comment]
Fixed in the npm package `v0.3.19`. Please ensure `@react-native-community/cli` version is `^1.5.0` in your lock file.

@v0lume, it looks different, but it is actually the same problem.

**Comment by v0lume** [comment]
@jhen0409 thanks, it works now

**Comment by santhoshselvan** [comment]
sdfvgghjuikhgfdc

**Comment by mxmzb** [comment]
I am having this issue with v0.3.20 and `@react-native-community/cli` v2.9.0 again.

**Comment by alvelig** [comment]
@mxmzb I confirm!

`yarn add -D @react-native-community/cli@2.8` as a workaround for now

**Comment by ShaneMatthias** [comment]
For me, under `devDependencies` I had `react-native-debugger-open ` at version `0.3.19`. I switched that to `^0.3.22` and it fixed it.
