### ISSUE TITLE
Apollo Dev Tools breaks when you select Mutation

### ISSUE THREAD

**Issue by mikeislearning** [jhen0409/react-native-debugger#332]
While the GraphiQL, Queries, and Mutations buttons are work properly, it breaks when I select `Mutation`. 
<img width="1164" alt="Screen Shot 2019-03-08 at 11 29 28 PM" src="https://user-images.githubusercontent.com/3151928/54066207-537f6c80-41fa-11e9-9ae7-2edb867adf86.png">

Apollo Client version: 2.5.1
Apollo In Cache Memory version: 1.5.1
React Native Debugger app version: 0.97
React Native version: 0.58.5
Platform: iOS
Is real device of platform: No
Operating System: macOS

**Comment by svegan** [comment]
I got it broken on mutations tab. The rest work fine.

**Comment by jhen0409** [comment]
Some issues of apollo-client-devtools was fixed, we need to update. But it seems not published as npm package.

**Comment by mikeatblockx** [comment]
@svegan I updated, and yes, now I have that issue with the mutations tab

**Comment by mikeislearning** [comment]
@svegan I updated my npm packages, and now cache is fine, but I have the same issue as you - Mutations Tab shows a blank screen

**Comment by pbassut** [comment]
Me too. Mutation tab shows a blank screen as soon as a mutation happens. Then I need to restart the tool

**Comment by jonas-arkulpa** [comment]
@mikeislearning which npm packages? Would prefer a broken mutation tab over the cache tab atm. 😅 
Tried to update `apollo-cache-inmemory` and `apollo-client` to the newest version.

**Comment by Gongreg** [comment]
Hey,
The issue is that Apollo dev tools npm version was not updated, so we are not getting the latest version. I will create an issue for them and then we will update the debugger.

**Comment by Gongreg** [comment]
https://github.com/apollographql/apollo-client-devtools/issues/202

**Comment by Gongreg** [comment]
https://github.com/jhen0409/react-native-debugger/pull/354 Will solve it.

**Comment by mikeislearning** [comment]
Works great! Thank you @Gongreg!
