### ISSUE TITLE
now working on RN 0.59

### ISSUE THREAD

**Issue by v0lume** [jhen0409/react-native-debugger#333]
facing an error on fresh RN 0.59.0 (not RC)

FAIL Replace `open debugger-ui with Chrome` to `open React Native Debugger`, the file inject file not found.

![image](https://user-images.githubusercontent.com/5075100/54313871-40e6a800-45eb-11e9-9182-9591cdc661ce.png)

React Native Debugger app version: 0.3.18
React Native version: 0590
Platform: any
Operating System: macOS

**Comment by jhen0409** [comment]
Duplicate of #330.
