### ISSUE TITLE
React Native Debugger doesn't show styles for Styled Components

### ISSUE THREAD

**Issue by imagentleman** [jhen0409/react-native-debugger#339]
Running into this issue (https://github.com/styled-components/styled-components/issues/805)

## Steps
Create a styled component (with [v4.1.3](https://github.com/styled-components/styled-components/releases/tag/v4.1.3))
Give it some styles
Use React Native Debugger to inspect the created components

## Expected Behavior
The styles used for the component should show up in the inspector
Actual Behavior
There's no styles at all

React Native Debugger app version: 0.9.7
React Native version: 0.59
Platform: Iphone X on IOS 12.2 (Simulator 10.2) 
Is real device of platform: No
Operating System: MacOS 10.14.3

**Comment by jhen0409** [comment]
It works to me with https://github.com/styled-components/styled-components/issues/805#issuecomment-303037961 and react-native-debugger. You should be able to see that by inspect the inner view of styled component.
