### ISSUE TITLE
The debugger does not allow switching between nested tabs (react-navigation)

### ISSUE THREAD

**Issue by Juliocbr** [jhen0409/react-native-debugger#352]
React Native Debugger app version: 0.9.8
"react-native-debugger-open": "^0.3.19"
React Native version: 0.59.8
Platform: Android
Is real device of platform: Yes
Operating System: macOS

On Android with nested tabs (I use react-navigation v2.18.1) I can't change between nested tabs if I enable the debugger mode, but when I disable the debugger I can change between nested tabs without problem.

**Comment by sudheerDev** [comment]
@Juliocbr did you find any resolutions for this?
