### ISSUE TITLE
Disable warnings in console

### ISSUE THREAD

**Issue by pianoman730** [jhen0409/react-native-debugger#353]
React Native Debugger app version: [0.9.8]
React Native version: [0.59.8]
Platform: [Android]
Is real device of platform: [No]
Operating System: [Linux]

I didn't know if this should be a feature request or if it's built in, but is there a way to disable certain warnings in the console? For instance I have a warning that hits every time because of some libraries I installed, but the warnings repeat themselves 7 or 8 times and it fills up the logs and makes a lot of noise. Is this a possibility?

Thanks! Great work on the app itself!

**Comment by Gongreg** [comment]
Hello @pianoman730, you could override console.log inside your app to only log specific messages.

**Comment by Aryk** [comment]
> Hello @pianoman730, you could override console.log inside your app to only log specific messages.

I tried overwriting console.log and the yellow warnings that I get in the console on my Expo app still show up. Do you know which function warnings go through?
