### ISSUE TITLE
V 0.9.9 is missing apple signature

### ISSUE THREAD

**Issue by rborn** [jhen0409/react-native-debugger#357]
React Native Debugger app version: 0.9.9
React Native version: m/a
Platform: n/a
Is real device of platform: n/a
Operating System: macOS

Trying to update from 0.9.8 to 0.9.9 will make macOs complain that the app has no code signature and won't start. I had to add it to the exceptions. 
Thanks

**Comment by benfurber** [comment]
To do the downgrade I struggled with brew. Others may find it helpful to go straight for the binary: https://github.com/jhen0409/react-native-debugger/releases/tag/v0.9.7

**Comment by jhen0409** [comment]
Sorry about that. I released new version [v0.9.10](https://github.com/jhen0409/react-native-debugger/releases/tag/v0.9.10) and it should fixed this.
