### ISSUE TITLE
Can't scroll in Apollo dev tools new explorer feature (0.9.9)

### ISSUE THREAD

**Issue by arrygoo** [jhen0409/react-native-debugger#359]
React Native Debugger app version: 0.9.9
React Native version: 0.59.8
Platform: Both Android and iOS
Is real device of platform:  No
Operating System: macOS

After updating to `0.9.9`, the explorer field is added to Apollo which is awesome, however if the list is too long you can scroll to see the rest of the queries.
<img width="689" alt="Screen Shot 2019-06-11 at 4 31 31 PM" src="https://user-images.githubusercontent.com/965429/59304637-a5ef7f80-8c66-11e9-8153-163bb0736d1b.png">

**Comment by Gongreg** [comment]
Hello @arrygoo, could you open the issue in https://github.com/apollographql/apollo-client-devtools ? We are just including their devtools here.

**Comment by kurniawanw0194** [comment]
@Gongreg 

It is fixed in `2.2.5`. We just need to update our version.

https://github.com/apollographql/apollo-client-devtools/pull/225

**Comment by Gongreg** [comment]
@kurniawanw0194, oh my. I meant inside https://github.com/jhen0409/react-native-debugger/

**Comment by ScreamZ** [comment]
Also same issue in cache page, ping when released :) Thanks

**Comment by mlnchk** [comment]
Any updates?

**Comment by jhen0409** [comment]
It should be fixed in the latest version.
