### ISSUE TITLE
React native app runs slow when debugging remotely

### ISSUE THREAD

**Issue by Tochukwuibe** [jhen0409/react-native-debugger#361]
Every time I try to turn on "Debug JS Remotely" the UI of my app becomes unresponsive. It starts to take 10 or more seconds for navigations to happen and the UI to set it. I also get warnings like "Native text input is 10 events ahead of your JS. speed up your JS". Keep in mind NONE of these issues happen when I am not debugging JS remotely. I have tried almost everything I can think of but I keep experiencing this issue.

React Native Debugger app version: [0.9.9]
React Native version: [0.59.9]
Platform: [ iOS &  Android, ...]
Is real device of platform: [Yes]
Operating System: [FILL THIS OUT: macOS]

**Comment by Gongreg** [comment]
Hello. When you are using remote debugging the app is expected to run slower.

**Comment by Tochukwuibe** [comment]
Yes, I am aware of that. However, I don't think it is normal for the app to become so slow that it is unusable/unresponsive, is it?

**Comment by Gongreg** [comment]
You are correct, it should become that slow. But if you are getting warnings about events one of slowness reasons may be the code that you have. I am using the debugger with a really big app and there is no big difference between using the debugger or not. It is quite difficult to help you without having issue reproduction.

**Comment by Tochukwuibe** [comment]
Thanks @Gongreg, I solved this issue by using an older iPhone emulator (iPhone  6) rather than the iPhone X
