### ISSUE TITLE
Module AppRegistry is not a registered callable module (calling runApplication)

### ISSUE THREAD

**Issue by gsklee** [jhen0409/react-native-debugger#362]
React Native Debugger app version: 0.9.10
React Native version: 0.57.8
Platform: Android emulator (Pixel 2)
Is real device of platform: (see above)
Operating System: macOS Mojave

I have the following app initialization code:

```js
import React from 'react';
import { AppRegistry } from 'react-native';
import App from './src/App';

(async () => {
    ...

    await 10; // it's awaiting for something else but apparently the thing it's awaiting for doesn't really matter; the bug appears even when it's awaiting a primitive value

    AppRegistry.registerComponent('My App', App);
})();
```

It is working fine when React Native Debugger is not attached but as soon as JS remote debugging is turned on, I will see this error:

![https://i.imgur.com/WYeUl3E.png](https://i.imgur.com/WYeUl3E.png)

Any ideas?

**Comment by gsklee** [comment]
Another thing that might be worth mentioning: the name of my entry file is called `index.js` instead of `index.android.js` which is the default since React Native v0.49. I am wondering if this is the cause of the issue and if it is - is there a way to tell React Native Debugger to look somewhere else for the entry file.

**Comment by dantenol** [comment]
any updates?

**Comment by renanbronchart** [comment]
Any updates @gsklee ?
