### ISSUE TITLE
cant  resize or reset the left side of the debugger

### ISSUE THREAD

**Issue by arnoldc** [jhen0409/react-native-debugger#363]
This seems a very easy question but i couldnt find to reset again my view aspect ratio on debugger on the left side

can anyone help me on it?  this happen after updating my react-native-debugger to the latest

heres a screenshot of my debugger
![Screen Shot 2019-07-03 at 3 24 13 PM](https://user-images.githubusercontent.com/242780/60572034-4a1ca000-9da7-11e9-85a9-b9212d244108.png)

it seems zoom out for some reason kinda like when your doing debugging for responsive web apps

**Comment by jhen0409** [comment]
It may no normal way to close since we closed the Elements tab.

You can reset that by `Restore defaults and settings` in devtools setting, or just delete cache dir  `/Users/<user>/Library/Application Support/React Native Debugger` and restart the app.
