### ISSUE TITLE
Can't seem to print $r from console, $r is not defined.

### ISSUE THREAD

**Issue by maxcmoi89** [jhen0409/react-native-debugger#37]
When I print $r in the console I get "Uncaught ReferenceError: $r is not defined(…)". I changed the context from "top" to "RNDebuggerWorker.js" in the console but it does not seem to change anything. I cannot see the React component either in the React debugger.

Any ideas what it might be?

Thanks for the great debugging tool :)

**Comment by jhen0409** [comment]
> I cannot see the React component either in the React debugger

Could you provide your React Native version and platform?

**Comment by maxcmoi89** [comment]
My version of React Native is 0.40, I am working on ubuntu 16.04. I am developping on an Android galaxy tab A device. My version of React Native Debugger is React Native Debugger 0.5.5.

**Comment by jhen0409** [comment]
> I am developping on an Android galaxy tab A device.

So it's real Android device? See #12 may be help you. :)

**Comment by maxcmoi89** [comment]
My bad for the late reply. I am developing on a physical Android device and I found the solution in issue #12 like you suggested.

I did run this in console and it worked: `adb reverse tcp:8097 tcp:8097`
