### ISSUE TITLE
react-native-debugger-open not working with RN 0.60 and react-native-community/cli 2.+

### ISSUE THREAD

**Issue by lukebrandonfarrell** [jhen0409/react-native-debugger#372]
<img width="568" alt="Screenshot 2019-07-20 at 13 53 42" src="https://user-images.githubusercontent.com/18139277/61578374-2e7afe80-aaf6-11e9-87b7-e25b0b0962c8.png">

"react-native": "0.60.3",
"@react-native-community/cli": "^2.0.1",
"react-native-debugger-open": "^0.3.19",
Platform: Both
Operating System: macOS

**Comment by usrbowe** [comment]
For me it breaks the latest version `2.7.0`. Here is more details: https://github.com/react-native-community/cli/issues/570

**Comment by jhen0409** [comment]
I've added [a test](https://github.com/jhen0409/react-native-debugger/commit/cb425270ac74109b6d8f2f80ab58c21f3a321777) for the latest version (`2.8.3`) of `@react-native-community/cli` and it passing, so I think it has been fixed.
