### ISSUE TITLE
Network Inspect not working with RN 0.59.9 

### ISSUE THREAD

**Issue by ndiyansah** [jhen0409/react-native-debugger#375]
React Native Debugger app version: [FILL THIS OUT]
React Native version: [FILL THIS OUT]
Platform: [FILL THIS OUT: iOS, Android, ...]
Is real device of platform: [Yes or No]
Operating System: [FILL THIS OUT: macOS, Linux, Windows]

**Comment by davicorreiajr** [comment]
@ndiyansah why did you close the issue? Did you find a solution? I'm facing the same problem.

**Comment by jun58** [comment]
@ndiyansah Did you find a solution? I have the same problem
