### ISSUE TITLE
Connecting network debugger causes error when upgrading to Expo 34

### ISSUE THREAD

**Issue by nferrara100** [jhen0409/react-native-debugger#378]
The following error is caused when running a snapshot test in a CI:

`ReferenceError: fetch is not defined`

The `fetch` in question is the one on line 8 of this example code: [Network Inspect of Chrome Devtools](https://github.com/jhen0409/react-native-debugger/blob/master/docs/network-inspect-of-chrome-devtools.md)

The only comment given for that fetch is "Ensure to get the lazy property", but I have no idea what that means and at any rate it shouldn't be causing an error. The code worked perfectly fine until we upgraded from Expo 33 to Expo 34 this morning.

React Native Debugger app version: N/A as the problem is in code the docs said to put in
React Native version: Expo 34
Platform: All
Is real device of platform: No
Operating System: Travis CI Linux

**Comment by jhen0409** [comment]
You can use `global.fetch` instead, just like we [did](https://github.com/jhen0409/react-native-debugger/blob/master/app/worker/networkInspect.js#L9-L11) in the Network Inspect feature.

It just to ensure to finish `whatwg-fetch` setup (it [defined](https://github.com/facebook/react-native/blob/0ee5f68929610106ee6864baa04ea90be0fc5160/Libraries/Core/setUpXHR.js#L23) as [lazy property](https://github.com/facebook/react-native/blob/0ee5f68929610106ee6864baa04ea90be0fc5160/Libraries/Utilities/defineLazyObjectProperty.js)) if it's never taken before.
