### ISSUE TITLE
Error: flatMap is not a function

### ISSUE THREAD

**Issue by tonmanayo** [jhen0409/react-native-debugger#379]
React Native Debugger app version: 0.9.10
React Native version: 0.59.5
Platform: IOS
Is real device of platform: NO
Operating System: OSX

Using flatMap causes the app to crash if the debugger is open. Really weird

**Comment by jhen0409** [comment]
We are still using the old version of Chromium, this is why there is no flatMap to use. It will be fix by #302.

**Comment by jhen0409** [comment]
Please try [`v0.10.0`](https://github.com/jhen0409/react-native-debugger/releases/tag/v0.10.0).
