### ISSUE TITLE
network inspector is notworking for axios

### ISSUE THREAD

**Issue by innocces** [jhen0409/react-native-debugger#388]
I use this tool to listen for network requests, but it doesn't work.
the libary i used for network is axios
![image](https://user-images.githubusercontent.com/38065966/63328883-8447fe00-c363-11e9-8a0d-98c6a02cd784.png)

React Native Debugger app version: 0.90.1
React Native version: 0.60.4
Platform: iOS
Is real device of platform: No
Operating System: macOS

**Comment by jhen0409** [comment]
Inspect the network requests for `axios` is works for me by click `Enable Network Inspect`.

Also, please checkout the new version [`0.9.11`](https://github.com/jhen0409/react-native-debugger/releases/tag/v0.9.11).
