### ISSUE TITLE
Missing reload button in debugger UI

### ISSUE THREAD

**Issue by piashcse** [jhen0409/react-native-debugger#389]
Please add reload button as supported by react native 60.5

React Native Debugger app version: 0.9.10
React Native version: 60.5
Platform: IOS, Android
Is real device of platform: Yes
Operating System: Mac

**Comment by jhen0409** [comment]
I confirmed it's still working on React Native v0.60.5. There may be a possibility of this problem:

- If you're not using dev bundle (dev=true) from React Native packager, it will not working as expected.
- For some reasons, some dependencies may affected [Promise](https://github.com/jhen0409/react-native-debugger/blob/master/app/worker/utils.js#L7) behavior. It is recommended to use the initial project to find out the reason.
