### ISSUE TITLE
Support React Devtools v4

### ISSUE THREAD

**Issue by tomasswood** [jhen0409/react-native-debugger#391]
React Native Debugger app version: 0.9.10
React Native version: 0.59
Platform: iOS, Android
Is real device of platform: Yes
Operating System: macOS, Linux, Windows

There are a lot of awesome improvements (especially performance improvements) in the new react devtools. It would be great to update to the latest.

https://github.com/facebook/react/blob/master/packages/react-devtools/CHANGELOG.md

**Comment by jhen0409** [comment]
PR is already here: #371
