### ISSUE TITLE
Throws error on trying to connect to debugger

### ISSUE THREAD

**Issue by deorukhkarchaitanya** [jhen0409/react-native-debugger#392]
Cannot connect to debugger on 0.9.11. I was able to connect before the update.

<img width="686" alt="Screenshot 2019-08-23 at 1 34 00 PM" src="https://user-images.githubusercontent.com/24487274/63577007-1130c880-c5ab-11e9-9ac6-ae4bae42688f.png">

React Native Debugger app version: [0.9.11]
React Native version: [0.59.3]
Platform: [IOS]
Is real device of platform: [No]
Operating System: [macOS]

**Comment by SergueyPutilin** [comment]
I've got the same issue after updating to the newest version

**Comment by ludwig-adoria** [comment]
same here :/

**Comment by san-smith** [comment]
And me too. I've got the same error.

React Native Debugger app version: [0.9.11]
React Native version: [0.58.4]
Platform: [IOS]
Is real device of platform: [No]
Operating System: [macOS]

**Comment by alyalya** [comment]
The same problem :(

**Comment by bnjmnjns** [comment]
Yep, seems like latest update is broken...

**Comment by jhen0409** [comment]
Please try [`v0.9.12`](https://github.com/jhen0409/react-native-debugger/releases/tag/v0.9.12).
