### ISSUE TITLE
Disable randomized port for react devtools websocket

### ISSUE THREAD

**Issue by jdhorner** [jhen0409/react-native-debugger#397]
```
React Native Debugger app version: v0.9.12
React Native version: 0.59.8 via Expo 34
Platform: iOS and Android
Is real device of platform: Yes. iPhone XR & Android Pixel 3a
Operating System: Windows 10
```
First, some background: 

My company observes strict PCI compliance rules, one of which is that our internal private WiFi needs to be separated from our wired computers. I have in-office-only test phones at 10.10.4.X  and my work PC where I develop with React Native and Expo at 10.10.8.X. They are not allowed to communicate with each other, unless we specifically open ports between the subnets in our company firewall. 

I've had them open 19000, 19001, and 19002 in order to be able to use Expo and the Metro bundler and debugger. And that all works great. But...

I cannot get the React Devtools section of React-Native-Debugger to "Connect to React" in the lower-left. As a test, I had our IT department temporarily unblock the currently randomized port of `window.__REACT_DEVTOOLS_PORT__`, and finally everything worked great! 

So my problem is that I can't allow React Devtools to use a randomized port for itself, but I can't see anywhere to specify a custom port **for that specific purpose**. Do you know where I could specify this port manually to make `window.__REACT_DEVTOOLS_PORT__` predictable?

**Comment by jhen0409** [comment]
Usually the random port will be [19567](https://github.com/jhen0409/react-native-debugger/blob/master/app/index.js#L82) if it is't being used. Also, you can change that by change `window.reactDevToolsPort` on DevTools console. (Remember switch to top context)

I'll consider to add it in the [config file](https://github.com/jhen0409/react-native-debugger/blob/master/docs/config-file-in-home-directory.md#config-file-in-home-directory). Thanks!

**Comment by jdhorner** [comment]
This is great news! And answers all of my questions. Thank you so much.
