### ISSUE TITLE
JSON value of type NSString cannot be converted to NSNumber [iOS]

### ISSUE THREAD

**Issue by kevinbarabash** [jhen0409/react-native-debugger#40]
I was trying to add a style to a Text element, `lineHeight: 15` and then my iOS app crashed.  I tried using the copy function to copy the stack trace, but that doesn't seem to be work so here's a screenshot.
![screen shot 2017-01-31 at 12 02 08 pm](https://cloud.githubusercontent.com/assets/1044413/22475436/f466bc52-e7ac-11e6-816c-95da0549a531.png)

**Comment by jhen0409** [comment]
I was fixed the problem in https://github.com/facebook/react-devtools/pull/392, just realized that I haven't fix [part of new attribute](https://github.com/jhen0409/react-devtools/blob/master/plugins/ReactNativeStyle/StyleEdit.js#L73), it will fix in the next version.

**Comment by jhen0409** [comment]
`v0.5.6` is released. :)
