### ISSUE TITLE
Error upgrading react-native-debugger

### ISSUE THREAD

**Issue by ghoshabhi** [jhen0409/react-native-debugger#410]
React Native Debugger app version: can't check the version. But assuming it's the latest version.
React Native version: 0.60
Platform: Both
Is real device of platform: No
Operating System: macOS

I got an alert to upgrade the app a couple times, but clicking on the "Download" button did nothing. I tried to reinstall the debugger using `brew`:

```sh
brew cask install react-native-debugger
```
and
```sh
brew cask reinstall react-native-debugger
```
And got this error after running install/reinstall:
<img width="1153" alt="Screen Shot 2019-10-11 at 9 18 40 AM" src="https://user-images.githubusercontent.com/19292575/66668741-c62a4d80-ec0a-11e9-8350-9dafba85d793.png">

Saw this error when I tried to check the version:
<img width="532" alt="Screen Shot 2019-10-11 at 9 18 55 AM" src="https://user-images.githubusercontent.com/19292575/66668742-c62a4d80-ec0a-11e9-8baa-5ac3b0af8a47.png">

I was starting to post a new issue here, and tried one last time. Voila¡ it worked with this command:
```sh
brew update && brew cask reinstall react-native-debugger
```

Just wanted to post the issue here with the error screenshots for you guys to look into :) Love the tool btw ❤️

**Comment by ITSjwags** [comment]
I'm getting this exact same error after the update through homebrew.

**Comment by niceprototypes** [comment]
Any luck with this? Can we at least get instructions on rolling back to 0.9?

**Comment by niceprototypes** [comment]
If you're still having this issue, roll back to `react-native-debugger@0.10.1` by running:
```
brew cask uninstall react-native-debugger
brew cask edit react-native-debugger
```
Then change the version number and SHA256 to the old values shown here:
https://github.com/Homebrew/homebrew-cask/pull/71158/files
And finally, run:
```bbrew cask install react-native-debugger```
