### ISSUE TITLE
Insatiable Update Notifications 

### ISSUE THREAD

**Issue by aliciakw** [jhen0409/react-native-debugger#411]
Every time I open React Native Debugger I am prompted to install the same update (v0.10.1). 

Clicking "download" closes the notification, but does not seem to download the update.
Deleting and reinstalling ReactNative Debugger did not work.
There is no way to turn off the annoying notifications, and no other way to manually download the update.
Please help! I've been dealing with this for months.

**Comment by jhen0409** [comment]
Please update it manually to [v0.10.2](https://github.com/jhen0409/react-native-debugger/releases/tag/v0.10.2). The update issue was fixed by https://github.com/jhen0409/react-native-debugger/commit/d6a46058ab1d780ee7e207fd4be61f0ecb0ca8b5.

**Comment by aliciakw** [comment]
Thanks @jhen0409 !
