### ISSUE TITLE
Application freezing during operation!!! Inability to download updates!!!

### ISSUE THREAD

**Issue by KassoBrapik** [jhen0409/react-native-debugger#416]
I want to ask you guys - Are you going to torture developers for a long time?

Your application is very cool and awesome, but it constantly freezing (on average every 3-4 application reloads)
Unable to download the update while you are in the application

React Native Debugger app version: 0.10.1
React Native version: 0.59
Platform: iOS, Android
Operating System: macOS

**Comment by gradinarot** [comment]
the same thing here.

React Native Debugger app version: 0.10.2
React Native version: 0.60
Platform: Android
Operating System: Windows

**Comment by GunnarAK** [comment]
Same issue here.
Closing debugger and running the following does not fix this...
```
brew cask reinstall react-native-debugger
```

React Native Debugger app version: 0.10.2
React Native version: 0.95.9
Operating System: MacOS Catalina 10.15

**Comment by rafaismyname** [comment]
I've been suffering from this same issue since forever too! :(
I was hoping that the last update would resolve this, but seems like it won't :(

Keeps freezing for every 4-5 refreshes :(

React Native Debugger app version: 0.10.2
React Native version: 0.61
Platform: iOS, Android
Operating System: macOS

**Comment by jhen0409** [comment]
The freezing issue is duplicated of #405. The update issue for `0.10.0` / `0.10.1` please read [the release note of v0.10.2](https://github.com/jhen0409/react-native-debugger/releases/tag/v0.10.2).
