### ISSUE TITLE
Reload App [Feature Request]

### ISSUE THREAD

**Issue by wamry** [jhen0409/react-native-debugger#419]
The web debugger has that button which is helpful, so i don't have to shake my phone like a crazy person.

Could you please add that feature in the app ?

**Comment by fierysolid** [comment]
I think you can right-click on the Elements pane and select "Reload JS"

**Comment by jhen0409** [comment]
👉 [`Shortcut references`](https://github.com/jhen0409/react-native-debugger/blob/master/docs/shortcut-references.md#shortcut-references)

**Comment by wamry** [comment]
> I think you can right-click on the Elements pane and select "Reload JS"

a button will only require one click instead of two, but that's ok
