### ISSUE TITLE
Change port of development console

### ISSUE THREAD

**Issue by obabichev** [jhen0409/react-native-debugger#42]
Maybe I'm doing smth wrong but If I'm right I's not possible to choose port of development console now.

For example I have two development consoles opened on ports 8081 and 8085, and debugger automatically chooses 8081.

Is there a way to fix it?

**Comment by jhen0409** [comment]
Currently available solution is [react-native-debugger-open](https://github.com/jhen0409/react-native-debugger/tree/master/patch), it can detect RN packager port.

If you're using macOS, you can just run the following command:

```bash
$ open "rndebugger://set-debugger-loc?host=localhost&port=8085"
```

**Comment by obabichev** [comment]
Thank you very much! ^_^
