### ISSUE TITLE
Enable Network Request By Default

### ISSUE THREAD

**Issue by Deg5112** [jhen0409/react-native-debugger#421]
I get that leaving this disabled can save resources but there should be an option to allow it to be enabled by default. It's an extra step that has to be made numerous times a day. Thoughts?

**Comment by jhen0409** [comment]
Yes, you can set [`defaultNetworkInspect`](https://github.com/jhen0409/react-native-debugger/blob/master/docs/config-file-in-home-directory.md) option in `~/.rndebuggerrc`.

**Comment by Deg5112** [comment]
@jhen0409 amazing thank you. sorry i missed this on the docs
