### ISSUE TITLE
react-native-debugger causes app to load stale JS code

### ISSUE THREAD

**Issue by rikur** [jhen0409/react-native-debugger#423]
React Native Debugger app version: 0.10.2
React Native version: 0.61.2
Platform: iOS
Is real device of platform: No
Operating System: macOS 10.14.6

When I enable Debug from the developer menu and connect through react-native-debugger, my app is stuck on an old, stale version of the JS code and editing files and reloading doesn't pick up any changes either. Debugging via the usual debugging tab in Chrome doesn't have this issue.

**Comment by bockc** [comment]
I can confirm that this issue occurs and stays there even if you kill the app and restart it as the debugging option stays enabled, so this is definitely not an issue with the new react-native fast-reload feature.

**Comment by mtnt** [comment]
> this is definitely not an issue with the new react-native fast-reload feature
Live reload still updates code (with the debugger turned on).

**Comment by mtnt** [comment]
@bockc 0.61.1

**Comment by bockc** [comment]
How can you choose to use live-reload specifically instead of the new fast-refresh feature ?

**Comment by martinezguillaume** [comment]
same problem here !

**Comment by rikur** [comment]
@jhen0409 any idea what could becausing this? Maybe Fast Refresh? I love this tool but now it's useless :/

**Comment by JacobJaffe** [comment]
Also facing this issue, 
React Native Debugger app version: 0.10.2
React Native version: 0.61.2
Platform: iOS
Is real device of platform: No
Operating System: macOS 10.14.3

**Comment by toby-pondr** [comment]
This is happening to me as well. As soon as I start debugging, it reverts back to a previous version. With debugging off, it works fine. Fast refresh works with debugging off.

react-native: 0.61.2
Android
Mac OS 10.15

**Comment by fendorio** [comment]
Happening for me too, stale code served with debugger connected. 


react-native: 0.61.3
iOS
Max OS: 10.14.6

**Comment by dquessenberry** [comment]
I am having the same issue with v0.10.4. It took me nearly 2 hours to figure out what is causing it - I thought I was going mad! Does anyone have any work arounds? I already downgraded this tool once recently because it was freezing and I was forced to restart it about 5 times a day. Decided to upgrade hoping my previous issue was fixed, but it looks like there is an even more serious bug now, so for now it back to v0.9.14...

RN: 0.61.2
iOS
MacOS: 10.14.6

**Comment by bockc** [comment]
@dquessenberry this is not an issue with `react-native-debugger`, this is an issue with `react-native` itself and its new `fast refresh` feature. By using the chrome console as a debugger I encounter the same issue. There's nothing much to do right now but to wait for the react-native team to fix this

**Comment by dquessenberry** [comment]
@bockc hmmm, I don't seem to be encountering the issue via Chrome console. What is especially odd is if RND is connected it loads stale js, if disconnected it shows the latest code, however if I complete uninstall RND and then reinstall it, it still shows stale code. So with that said, I suppose you're correct, it must be something outside of RND, such as RN itself. Thanks.

**Comment by bockc** [comment]
Well, that's nice to hear for you, glad that you could find a way out of this.
But I guess this issue will reappear sooner or later for you, I sometimes have a whole day where this does not happen, and the following day everything starts to go rogue...
Anyway, I hope for you that you're definitely out of it :)

I don't think the issue comes from a combination of RND and RN either, as I tried with both Chrome and RND, this issue is exactly the same. The only common thing I see between all I have tested is... RN itself haha, but of course I could be missing something

**Comment by dyancat** [comment]
![image](https://user-images.githubusercontent.com/848589/69504219-b0d46d00-0f85-11ea-99ed-de5e4e2e59c0.png)

What worked for me is disabling the cache in the network tab

**Comment by bockc** [comment]
@dyancat nope, did not work for me

**Comment by martinezguillaume** [comment]
For me, when this happens, I'm using a software (CleanMyMac) to clean React Native Debugger files. Then, restart it and works again !

![image](https://user-images.githubusercontent.com/17292331/69532034-4a475300-0f75-11ea-8977-e69be8f0ee41.png)

**Comment by lafiosca** [comment]
Today was the first time I ran into this problem, coincidentally right after doing a self-update of React Native Debugger to 0.10.5. I'm not certain which version I upgraded from, but it was at least 0.10.2 and likely 0.10.4. @dyancat 's suggestion of disabling the network cache worked for me, which leads me to assume that the development build of my app was fetching a cached version of the bundle. This seems reinforced by the fact that the only network fetch in the log window is for `http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false`.

I had previously tried deleting the watchman cache, upgrading watchman, resetting the metro cache (multiple times), deleting my entire repo and reinstalling it, rebuilding the app, etc. The only consistent behavior was that each time I turned on debugging, the old version of the app loaded.

After turning on debugging again, disabling network cache in React Native Debugger, and hitting reload on the app, the latest version of my app code loaded. Re-enabling the cache after that and reloading again still showed the latest version.

**Comment by bockc** [comment]
I confirm that disabling the network cache prevents the issue from occurring. It didn't work for me because I didn't restart react-native-debugger after disabling the network cache.

**Comment by export-mike** [comment]
Google clearing breaking shit for RN only, its androidx all over again.

**Comment by irondsd** [comment]
> ![image](https://user-images.githubusercontent.com/848589/69504219-b0d46d00-0f85-11ea-99ed-de5e4e2e59c0.png)
> 
> What worked for me is disabling the cache in the network tab

I was so confused and it took me an hour to figure out it was a debugger's fault. This worked great. Thank you, sir

**Comment by KingAmo** [comment]
i suggest pin this issue before it is resolved. i have spend hours before come here

**Comment by terence612** [comment]
I should have search this issue earlier. This solution solved my problem.

> ![image](https://user-images.githubusercontent.com/848589/69504219-b0d46d00-0f85-11ea-99ed-de5e4e2e59c0.png)
> 
> What worked for me is disabling the cache in the network tab

**Comment by vinhdothe93** [comment]
> ![image](https://user-images.githubusercontent.com/848589/69504219-b0d46d00-0f85-11ea-99ed-de5e4e2e59c0.png)
> 
> What worked for me is disabling the cache in the network tab

Thanks so much. You saved my life. :D

**Comment by dihan** [comment]
> > ![image](https://user-images.githubusercontent.com/848589/69504219-b0d46d00-0f85-11ea-99ed-de5e4e2e59c0.png)
> > What worked for me is disabling the cache in the network tab
> 
> Thanks so much. You saved my life. :D

This image is not loading for me :(

**Comment by aditodkar** [comment]
I am not able to debug the app because when I try to connect emulator with react native debugger it stops and app is not running. Now if I close the debugger then app starts working fine why is this happening how to fix this? Without debugger it will become very difficult. See screenshot below:


React Native version: v0.61.5

react native debugger version v0.10.6

![Screenshot_17](https://user-images.githubusercontent.com/16613832/74595802-0fccee00-506c-11ea-83d7-b4bb8729a1a6.png)

**Comment by rikur** [comment]
Alright, I think we can close this issue. Thanks @dyancat!

**Comment by infostreams** [comment]
@rikur What do you mean close it? That's not a solution, that's a workaround! Can you make changes in the debugger so that it never loads stale Javascript code? This bug has caused me multiple hours TWICE! And I'm sure I'm not the only one. The problem described in this ticket is not resolved.

**Comment by infostreams** [comment]
Thanks for re-opening it. Is it possible that this https://stackoverflow.com/a/55026131 is the solution for this problem?

**Comment by junaid5546** [comment]
the app runs old code since the evening I don't know why this is happening?

**Comment by cryptedx** [comment]
> the app runs old code since the evening I don't know why this is happening?

Disable the cache like mentioned above.

**Comment by chudaotrucnhan** [comment]
> ![image](https://user-images.githubusercontent.com/848589/69504219-b0d46d00-0f85-11ea-99ed-de5e4e2e59c0.png)
> 
> What worked for me is disabling the cache in the network tab

You saved my life :D

**Comment by eurobob** [comment]
This is so fucking dumb. Yesterday no problem, today I had the issue. Wtf. Thanks for the fix @dyancat

**Comment by kbrandwijk** [comment]
Never happened to me before, but started happening in 0.11.0-beta-4.

**Comment by mertuner** [comment]
> ![image](https://user-images.githubusercontent.com/848589/69504219-b0d46d00-0f85-11ea-99ed-de5e4e2e59c0.png)
> 
> What worked for me is disabling the cache in the network tab

Thank you good sir

**Comment by Ben-Mark** [comment]
The react native debugger must set that checkbox by default!

Thank you @dyancat  !!

**Comment by darkbasic** [comment]
> The react native debugger must set that checkbox by default!

It does. Make sure to not use outdated versions.

**Comment by Ben-Mark** [comment]
I'm on RN 0.62.2

**Comment by darkbasic** [comment]
> I'm on RN 0.62.2

RN version doesn't matter, it's the **Debugger** than you have to upgrade.

**Comment by BrunoVillanova** [comment]
> ![image](https://user-images.githubusercontent.com/848589/69504219-b0d46d00-0f85-11ea-99ed-de5e4e2e59c0.png)
> 
> What worked for me is disabling the cache in the network tab

Thank you so much!!!

**Comment by seanlangley** [comment]
> ![image](https://user-images.githubusercontent.com/848589/69504219-b0d46d00-0f85-11ea-99ed-de5e4e2e59c0.png)
> 
> What worked for me is disabling the cache in the network tab

Thank you so much, I spent an hour on this problem and this fix worked for me.

**Comment by FuzzyBuckBeak** [comment]
I spent hours on this before i ended up here. This is a life saver!

**Comment by FuzzyBuckBeak** [comment]
> ![image](https://user-images.githubusercontent.com/848589/69504219-b0d46d00-0f85-11ea-99ed-de5e4e2e59c0.png)
> 
> What worked for me is disabling the cache in the network tab

I spent hours on this before i ended up here. Thanks @dyancat

**Comment by SethArchambault** [comment]
Ah this explains why I was only encountering this in the native debugger - on the web I commonly use the Disable Cache feature to test website page reloads, so that was already checked.. Thanks!

**Comment by AndrewEastwood** [comment]
The disabling cache feature does not work for me

**Comment by renwenci** [comment]
i met this problem after a git.lock generated, delete it, and every thing is ok

**Comment by Roselai** [comment]
> Today was the first time I ran into this problem, coincidentally right after doing a self-update of React Native Debugger to 0.10.5. I'm not certain which version of RND I upgraded from, but it was at least 0.10.2 and likely 0.10.4. This is a RN 0.61.4 app. @dyancat 's suggestion of disabling the network cache worked for me, which leads me to assume that the development build of my app was fetching a cached version of the bundle. This seems reinforced by the fact that the only network fetch in the log window is for `http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false`.
> 
> I had previously tried deleting the watchman cache, upgrading watchman, resetting the metro cache (multiple times), deleting my entire repo and reinstalling it, rebuilding the app, etc. The only consistent behavior was that each time I turned on debugging, the old version of the app loaded.
> 
> After turning on debugging again, disabling network cache in React Native Debugger, and hitting reload on the app, the latest version of my app code loaded. Re-enabling the cache after that and reloading again still showed the latest version.

Thank you! This worked for me.

**Comment by rusakovic** [comment]
`Disable cache` not solve this issue

**Comment by gaberogan** [comment]
@jhen0409 Why is this still closed? Do we need to open another issue?

**Comment by daihieptn97** [comment]
#### Try deleting the 
 - ./android/.idea folders. 
 - ./android/.gradle folders. 
#### It works for me

[![enter image description here][1]][1]


  [1]: https://i.stack.imgur.com/y2yib.png

**Comment by ajaymarathe** [comment]
> ![image](https://user-images.githubusercontent.com/848589/69504219-b0d46d00-0f85-11ea-99ed-de5e4e2e59c0.png)
> 
> What worked for me is disabling the cache in the network tab

yeah, it's working now, thanks everybody 👍🏻 💯
