### ISSUE TITLE
The profiler is profiling the RN debugger instead of the running app?

### ISSUE THREAD

**Issue by rclai** [jhen0409/react-native-debugger#429]
<img width="973" alt="Screen Shot 2019-11-07 at 4 26 32 PM" src="https://user-images.githubusercontent.com/1316261/68376640-7bedab00-017b-11ea-88bd-9e7486276335.png">

0.10.2
And yes, the app (iOS simulator) is connected to the debugger. This happens intermittently but now is happening all the time.

**Comment by jhen0409** [comment]
The Performance tab should includes the debugger app, but it also profiling `RNDebuggerWorker` if your React Native app has any behavior.

<img width="500" alt="Screen Shot 2019-11-10 at 8 54 43 AM" src="https://user-images.githubusercontent.com/3001525/68537003-ca779100-0397-11ea-8a8f-a84c3fd730f1.png">

**Comment by rclai** [comment]
The expandable worker is not even in there, so I don't know what's going on.

**Comment by rclai** [comment]
I guess I have to restart the app while the recording is happening to get it to work 🤷
