### ISSUE TITLE
Blackboxing scripts does not work consistently

### ISSUE THREAD

**Issue by JodiWarren** [jhen0409/react-native-debugger#43]
This appears to be a manifestation of this Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=589980

I appreciate that it will probably be fixed upstream, but I thought I'd raise it here as I'm not familiar enough with the dependencies to know who to bug.

**Comment by jhen0409** [comment]
It seems fixed in Chrome 56, so it should works fine in RNDebugger ^0.6.0. :)

**Comment by JodiWarren** [comment]
@jhen0409 It still seems to occur for me using RNDebugger 0.6.6:

![image](https://cloud.githubusercontent.com/assets/1337003/26491933/91a8ac62-4209-11e7-9e48-54a592e43840.png)

Apologies if it's something that I'm doing wrong!

**Comment by jhen0409** [comment]
Sorry about that, I just saw the chromium issue and thought it was fixed, but actually no even if Chrome 58. 😳

I tried it should fixed in Chrome 59 (current beta), we should waiting for stable version and Electron upgrade. I'll re-open this.
