### ISSUE TITLE
Cannot scroll inside Apollo tab

### ISSUE THREAD

**Issue by karltaylor** [jhen0409/react-native-debugger#434]
On version `0.10.4` I cannot scroll inside the Apollo tab even though I have loads of Data

![Screenshot 2019-11-15 at 12 32 28](https://user-images.githubusercontent.com/6763109/68943770-0483d100-07a4-11ea-822a-97a3bc4333fd.png)

**Comment by jhen0409** [comment]
It may fixed in https://github.com/jhen0409/react-native-debugger/commit/370205764045016b796916f33fdfaeb7b89ad5d1 ([apollo-client-devtools@2.2.5](https://github.com/apollographql/apollo-client-devtools/releases/tag/v2.2.5)), I'll release the new version soon.
