### ISSUE TITLE
Uncaught (in promise) ReferenceError: window is not defined

### ISSUE THREAD

**Issue by MakhouT** [jhen0409/react-native-debugger#441]
> RNDebuggerWorker.js:2 Uncaught (in promise) ReferenceError: window is not defined
>     at s (RNDebuggerWorker.js:2)
>     at ht (RNDebuggerWorker.js:2)
>     at executeApplicationScript (RNDebuggerWorker.js:2)
>     at RNDebuggerWorker.js:2

This just started happening out of nowhere?

React Native Debugger app version: 0.10.5
Platform: iOS, simulator
```
System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 277.91 MB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.2.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 26, 28
      Build Tools: 28.0.3
      System Images: android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.5429.30.34.5452501
    Xcode: 11.2/11B52 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.4 => 0.61.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7```

**Comment by jhen0409** [comment]
We can avoid the error. But it may has something wrong to causes React Native runtime didn't included `window` before RNDebugger setup?

**Comment by MakhouT** [comment]
If forgot the report back. I fixed it, the problem wasn't RND. I had to recreate my schemes in xcode and clean my cache. Now it's all good!

**Comment by shivabhusal** [comment]
I had to terminate the `Metro Bundler` window and run the `yarn android` command again to fix it.
