### ISSUE TITLE
react how to use @cparram/use-redux-api

### ISSUE THREAD

**Issue by natashanodine** [jhen0409/react-native-debugger#445]
I am trying to use the library @cparram/use-redux-api to connect my app to the backend. I have read the npm instructions and looked at the codesandbox example but cannot figure out how to implement it the correct way into my app. 

This is my Configure store js file
	import { createStore, combineReducers, applyMiddleware } from 'redux';
	import { Posts } from './posts';
	import { Comments } from './comments';
	import thunk from 'redux-thunk';
	import logger from 'redux-logger';

	import useReduxApi, { apiReducer } from "@cparram/use-redux-api";

	export const appReducer = combineReducers({
	  api: apiReducer
	  // ... other reducers.
	  // als
	});

	export const ConfigureStore = () => {
		const store = createStore(
			combineReducers({
				posts: Posts,
				comments: Comments
			}),
			appReducer,
			applyMiddleware(thunk,logger)
		);

		return store;
	}

and this is my ActionCreators.js

	import  * as ActionTypes from './ActionTypes';
	import { baseUrl } from '../shared/baseUrl';
	import React, { useEffect, useState } from "react";
	import useReduxApi, { apiReducer } from "@cparram/use-redux-api";

	export const addComment = (comment) => ({
		type: ActionTypes.ADD_COMMENT,
		payload: comment
	});

	export const postComment = (postId, email, name, body) => (dispatch) => {

		const newComment = {
			postId: postId,
			email: email,
			name: name,
			body: body
		};

		return fetch(baseUrl + 'comments', {
			method: "POST",
			body: JSON.stringify(newComment),
			headers: {
			  "Content-Type": "application/json"
			},
			credentials: "same-origin"
		})
		.then(response => {
			if (response.ok) {
			  return response;
			} else {
			  var error = new Error('Error ' + response.status + ': ' + response.statusText);
			  error.response = response;
			  throw error;
			}
		  },
		  error => {
				throw error;
		  })
		.then(response => response.json())
		.then(response => dispatch(addComment(response)))
		.catch(error =>  { console.log('post comments', error.message); alert('Your comment could not be posted\nError: '+error.message); });
	};

	export const fetchPosts = () => (dispatch) => {
		dispatch(postsLoading(true));

	const [api, apiCall] = useReduxApi("posts");

		return  useEffect(() => {
		apiCall({
		  endpoint: "https://jsonplaceholder.typicode.com/posts"
		});
	  }, []).then(response => {
				if(response.ok) {
					return response;
				}else{
					var error = new Error('Error' + response.status +': '+response.statusText);
					error.response = response;
					throw error;
				}
			},
			error => {
				var errmess = new Error(error.message);
				throw errmess;
			})
			.then(response => response.json() )
			.then(posts => dispatch(addPosts(posts)))
			.catch(error => dispatch(postsFailed(error.message)));
	}

	export const postsLoading = () => ({
		type:ActionTypes.POSTS_LOADING
	});

	export const postsFailed = (errmess) => ({
		type:ActionTypes.POSTS_FAILED,
		payload:errmess
	});

	export const addPosts = (posts) => ({
		type:ActionTypes.ADD_POSTS,
		payload:posts
	});

	export const fetchComments = () => (dispatch) => {
		return fetch(baseUrl + 'comments')
			.then(response => {
				if(response.ok) {
					return response;
				}else{
					var error = new Error('Error' + response.status +': '+response.statusText);
					error.response = response;
					throw error;
				}
			},
			error => {
				var errmess = new Error(error.message);
				throw errmess;
			})
			.then(response => response.json() )
			.then(comments => dispatch(addComments(comments)))
			.catch(error => dispatch(commentsFailed(error.message)));
	}

	export const commentsFailed = (errmess) => ({
		type:ActionTypes.COMMENTS_FAILED,
		payload:errmess
	});

	export const addComments = (comments) => ({
		type:ActionTypes.ADD_COMMENTS,
		payload:comments
	});

I have tried implementing this method with the library in the const fetchPosts but I am getting this error

×
Error: It looks like you are passing several store enhancers to createStore(). This is not supported. Instead, compose them together to a single function.
createStore
D:/Documents/job_application/tasks/interfell/node_modules/redux/es/redux.js:66
ConfigureStore
D:/Documents/job_application/tasks/interfell/src/redux/configureStore.js:17
  14 | });
  15 | 
  16 | export const ConfigureStore = () => {
> 17 |     const store = createStore(
  18 |         combineReducers({
  19 |             posts: Posts,
  20 |             comments: Comments

I am new to react and have never used this library before so I am a bit lost on how to do the get and post.

**Comment by jhen0409** [comment]
This issue is not related to this project.
