### ISSUE TITLE
cookie may not stored to device when using RND

### ISSUE THREAD

**Issue by KingAmo** [jhen0409/react-native-debugger#448]
we use `cookie` to store `token`, when a http response header has `set-cookie`, the value may not be stored to device when using RND, then following request can not take the cookie with token,  and i come to no authentication;  while everything is  fine when disable debugging

React Native Debugger app version: 0.10.5
React Native version: 0.61.5
Platform: iOS
Is real device of platform: No
Operating System: macOS

**Comment by KingAmo** [comment]
i use [react-native-cookie-store](https://github.com/safaiyeh/react-native-cookie-store) to get the cookie in the device

**Comment by KingAmo** [comment]
maybe it is not `RND`'s fault

**Comment by KingAmo** [comment]
https://github.com/electron/electron/releases/tag/v7.1.10 
`electron v7.1.10`  fix  `set-cookie` issue ,  wait for upgrate to  `v7.1.10`

**Comment by seancheung** [comment]
When device is connected to RND, `set-cookies` header becomes lost.
