### ISSUE TITLE
Show failures when 'Waiting for client connection (port 19001)' happens

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [jhen0409/react-native-debugger#450]
React Native Debugger app version: 10.15.1
React Native version: 35.0.0
Platform: iOS 13.1
Is real device of platform: No; simulator
Operating System: macOS 10.15.1 Catalina

When there is some kind of version mismatch between React Native (with or without Expo) and RND cannot connect, you get this window:
![Screenshot of React Native Debugger waiting for client connection](https://user-images.githubusercontent.com/3335181/71523162-cc3cdb80-2895-11ea-9ce9-46a585358976.png)

It's very frustrating - I only work in this area sporadically, and it seems like every month I get this and have to piece together (1) why it's happening and (2) which versions are out of date.

Could there be some kind of debug / diagnostics info about what the responses were on the port? Some kind of  _"we tried to talk to port ABC but the response was declined with XYZ"_ would be swell.

/cc @jonsamp, who has previously listened to me gripe about RN versioning.

**Comment by sohaib3335** [comment]
I have the same issue related to version. Do I have download a newer version of React Native Debugger?

**Comment by adenyx** [comment]
Same issue. @JoshuaKGoldberg Did you solve the problem?

**Comment by JoshuaKGoldberg** [comment]
No, I stopped working in React Native a couple of years ago 😄

**Comment by marklanhamhc** [comment]
I'm getting the same issue

**Comment by JoshuaKGoldberg** [comment]
Closing out my old issues I no longer have context on. If anybody else is still seeing this, I'd encourage you to file a new issue with more information. Cheers!
