### ISSUE TITLE
Explicit console.logs... what happened.

### ISSUE THREAD

**Issue by smooJitter** [jhen0409/react-native-debugger#454]
In an earlier version, I was able to see the exact file and line number of my console.log() outputs for  example, 

```
   undefined            view_something.js: 12
```
but now I get something like this, 

```
undefined              setUpDeveloperTools.js: 73
````

Is this an issue with settings, has this feature been abandoned?

**Comment by jhen0409** [comment]
It's react-native issue, and was fixed by https://github.com/facebook/react-native/pull/26883. You can also [blackboxing](https://developer.chrome.com/devtools/docs/blackboxing) the `setUpDeveloperTools.js` in devtools.
