### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by leesolway** [jhen0409/react-native-debugger#46]
remotedev-debugger i would pass setup options as follows: 

remotedev-debugger --hostname localhost --port 5678 

How would you solve this issue with react-native-debugger?

**Comment by jhen0409** [comment]
We used [API of redux-devtools-extension](https://github.com/jhen0409/react-native-debugger#redux-devtools-and-remotedev-on-local-even-mobx), it's included in debug remotely mode, just send message by WebWorker, so you don't need to set any server related options.

**Comment by leesolway** [comment]
I wonder if you could help me out there..

The state inspector isn't showing any Redux information, however http://remotedev.io/local/ shows me what i would expect.

Also the following are both undefined, not sure if this is an issue or not. I am using composeWithDevTools instead from remote-redux-devtools

    window.__REDUX_DEVTOOLS_EXTENSION__
    window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__

**Comment by leesolway** [comment]
Figured it: 

It was the version of react-native-debugger
