### ISSUE TITLE
Cannot make a network request i don't toggle "Enable Network Inspect"

### ISSUE THREAD

**Issue by hengvenchang** [jhen0409/react-native-debugger#460]
when i try to make axios request, it returns this error
<img width="419" alt="Screenshot 2020-02-19 at 7 53 03 PM" src="https://user-images.githubusercontent.com/17307495/74836210-83634980-5351-11ea-9023-3293922783fb.png">
 but when i enable network inspect, everything is working fine

**Comment by jhen0409** [comment]
Please see [the `Limitations` section](https://github.com/jhen0409/react-native-debugger/blob/master/docs/network-inspect-of-chrome-devtools.md#limitations).
