### ISSUE TITLE
Not possible to configure redux-devtools

### ISSUE THREAD

**Issue by zbycz** [jhen0409/react-native-debugger#461]
Maybe this is some issue on my side, but the redux tool in RND connects automatically even if I do not enhance the store in my app (aka `createStore(rootReducer, composeWithDevTools())`).

I kind of don't believe it, but just want to ask if its possible?
If this is true, is there a way to configure the devtool? lets say set [maxAge](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#maxage) bigger than default?

Possibly related lines:
- https://github.com/jhen0409/react-native-debugger/blob/master/app/containers/ReduxDevTools.js#L44
- https://github.com/zalmoxisus/remotedev-app/blob/master/src/app/reducers/instances.js

Thanks :) 

React Native Debugger app version: 0.10.6
React Native version: 0.61.1
Platform: Android
Is real device of platform: No
Operating System: macOS

**Comment by jhen0409** [comment]
No, it won't connect automatically. You may need to track your source code.
