### ISSUE TITLE
Can't find the redux store UI on debugger.

### ISSUE THREAD

**Issue by motogod** [jhen0409/react-native-debugger#464]
All of a sudden I can't see my redux store ui and I have no idea why it was happened.

I use mac and type command `brew cask reinstall react-native-debugger ` to reinstall.

react-native-debugger version is 0.10.6

<img width="1536" alt="截圖 2020-03-05 下午3 59 34" src="https://user-images.githubusercontent.com/17781603/75960476-14622500-5efb-11ea-8e66-95e86deccf82.png">

What mistake I made ?

**Comment by skay97** [comment]
Try going to view and toggling redux dev tools. Or try toggling the redux dev tools by pressing alt+cmd+k.

**Comment by motogod** [comment]
Thanks for your response, option+cmd+k in mac fix the problem.
