### ISSUE TITLE
Search by attribute / props

### ISSUE THREAD

**Issue by jambon-beurre-vodka** [jhen0409/react-native-debugger#466]
In the Elements view of RN debugger, I know how to search by Component name. 

But how do you search by attribute name / props name? Would be great if we can filter components by their attributes. 

For example now if I want to search for an `Icon` component, I can type Icon but it'll show me dozens of results. If I could filter the `Icon` by its `name` props that would be convenient.

**Comment by jhen0409** [comment]
I suggest report the issue to [the repo](https://github.com/facebook/react) for `react-devtools-core`.
