### ISSUE TITLE
Requiring unknown module "0"

### ISSUE THREAD

**Issue by bockc** [jhen0409/react-native-debugger#467]
I have an issue while connecting physical devices to react-native-debugger.

Here's how to reproduce it:
- Start your application with any physical device (iOS/Android) and connect it to react-native-debugger
- Start your application on another physical device (iOS if you first connected an Android, Android otherwise) and connect it to react-native-debugger
- The application will show a red screen saying `requiring unknown module "0"`

What I noticed is:
- it does not happen if you debug with Chrome instead of react-native-debugger
- the order of platforms used does not matter (iOS -> Android === Android -> iOS)
- only the first connected device will be able to start the application without the error, even if the error 
happened on the second device, you can still restart it on the first one
- the application is able to start on the second device (the one with the 'unknown module error') if you 
disconnect it from react-native-debugger
- restarting metro allows you to 'reset' this situation, so you can run and debug your app on the device that previously had the error
- it does not seem to happen if you start the application with a physical iOS device, then start the app in an iOS simulator
- it does seem to happen if you start the application in an iOS simulator then start the application in an Android simulator, definitely looks like it's a 'platform switch' issue

Unfortunately I only have one Android and one iOS devices to my disposal, so I couldn't test more scenarios.

I took a screenshot of the error in case it would be of any help:
![Screenshot_1584009361](https://user-images.githubusercontent.com/10670669/76512983-e2e6dd80-6455-11ea-99f5-38df2652f5a2.png)

React Native Debugger app version: 10.0.6
React Native version: 0.61.5
Platform: iOS & Android
Is real device of platform: Yes, but also occurs in simulators
Operating System: macOS

**Comment by jhen0409** [comment]
It was fixed by #468 and released as [`v0.10.7`](https://github.com/jhen0409/react-native-debugger/releases/tag/v0.10.7). Thanks for report! :)
