### ISSUE TITLE
Strange crontab related to ~/.rndebuggerrc

### ISSUE THREAD

**Issue by zhigang1992** [jhen0409/react-native-debugger#481]
![image](https://user-images.githubusercontent.com/1057756/77842716-3e3ffc00-71c8-11ea-849d-c323f953d7ba.png)

I've never added this myself, and I've search the source code in this repo and didn't find anything.

Please advice if anyone has any context about this.

**Comment by jhen0409** [comment]
This is not caused by the RNDebugger app. You may need to check the behavior of other programs.
