### ISSUE TITLE
DevTools v3 is incompatible

### ISSUE THREAD

**Issue by Marzdor** [jhen0409/react-native-debugger#483]
React Native Debugger app version: 0.10.7
React Native version: .62
Platform: ios
Is real device of platform: no
Operating System: Mac Catalina 10.15.3

Everything works except the react dev tools. After upgrading to React Native .62 it says DevTools v3 is incompatible

**Comment by jhen0409** [comment]
Yeah, please try to use [v0.11 beta](https://github.com/jhen0409/react-native-debugger/releases/tag/v0.11.0-beta-4).

**Comment by Marzdor** [comment]
Ah I completely missed this, it works now.
