### ISSUE TITLE
I can't download versions above 0.10.0

### ISSUE THREAD

**Issue by gabeDevlift** [jhen0409/react-native-debugger#486]
React Native Debugger app version: 0.10.0
React Native version: 0.61.5
Operating System: OS X Mojave

Whenever I open React Native Debugger, the following modal pops up:

![Screen Shot 2020-03-31 at 5 59 02 PM](https://user-images.githubusercontent.com/43910963/78079078-67ec5500-7379-11ea-8ace-7bdc1485c170.png)

I click "Download", and the modal closes and nothing else happens. I've tried running `brew cask upgrade` and this doesn't download it either. Does anyone know how I can approach trying to get the most recent version? I know that 0.10.0 isn't compatible with more recent versions of React Native.

**Comment by jhen0409** [comment]
The auto update of `v0.10.0` and `v0.10.1` is broken. ([Please see v0.10.2 release note](https://github.com/jhen0409/react-native-debugger/releases/tag/v0.10.2))

You can download it from [Release page](https://github.com/jhen0409/react-native-debugger/releases) if the auto update is broken on that version.
