### ISSUE TITLE
"react-devtools agent got no connection" warning and empty components panel

### ISSUE THREAD

**Issue by keyblade95** [jhen0409/react-native-debugger#487]
When I start my app and click on "Debug", the following warning shows up and I cannot see any component in the react-devtools panel (as you can see in the bottom left):
![screen2020-04-01](https://user-images.githubusercontent.com/11407258/78110233-de7d6700-73fa-11ea-8870-85dc41ef7a30.png)

**React Native Debugger app version**: 0.11.0-beta-4
**React Native version**: 0.61.5
**Platform**: Android
**Is real device of platform**: Emulator
**Operating System**: macOS and Windows

**Comment by jhen0409** [comment]
You're using React Native v0.61, but RNDebugger v0.11 beta is only supported for React Native version >= 0.62. ([Release note](https://github.com/jhen0409/react-native-debugger/releases/tag/v0.11.0-beta-4))

**Comment by Programm3r** [comment]
> You're using React Native v0.61, but RNDebugger v0.11 beta is only supported for React Native version >= 0.62. ([Release note](https://github.com/jhen0409/react-native-debugger/releases/tag/v0.11.0-beta-4))
> 
> However, if you want use React Native v0.61 with the new React DevTools, you can read [this comment](https://github.com/jhen0409/react-native-debugger/pull/371#issuecomment-513513181).

Hi,

Could you please elaborate as to how the link provided in the comment, can solve the issue one would face when your react-native version is < 0.62
Not sure I follow.

Many thanks!

**Comment by Devil-Cong** [comment]
I have the same problem.

React Native Debugger app version: 0.11.7
React Native version: 0.63.4
Platform: Android
Is real device of platform: Yes
Operating System: macOS

**Comment by Devil-Cong** [comment]
I solve it by this [way](https://github.com/facebook/react/issues/20455#issuecomment-763578633)
