### ISSUE TITLE
DevTools v3 is incompatible with this version of React when using RN >= 0.62

### ISSUE THREAD

**Issue by JohannesKlauss** [jhen0409/react-native-debugger#489]
When trying to debug a real device using RN >= 0.62 the following error occurs in React Native Debugger:
`DevTools v3 is incompatible with this version of React`

I guess this has to do with the fact, that DevTools need to be v4 to work with RN >= 0.62 as stated here by Dan:

https://github.com/facebook/react/issues/17215#issuecomment-603880575

React Native Debugger app version: 0.10.7
React Native version: 0.62.1
Platform: Android
Is real device of platform: Yes
Operating System: macOS

**Comment by jhen0409** [comment]
Yeah, please use [v0.11 beta](https://github.com/jhen0409/react-native-debugger/releases/tag/v0.11.0-beta-4). I'll keep this open because it duplicated many times.

**Comment by jhen0409** [comment]
v0.11 is now released, and you should be able to see more info for DevTools v3 is incompatible message on v0.10.8.
