### ISSUE TITLE
How do I enable the touchbar shortcuts?

### ISSUE THREAD

**Issue by brax10ward** [jhen0409/react-native-debugger#495]
React Native Debugger app version: 10.9
React Native version: 0.59.10
Platform: iOS
Is real device of platform: No
Operating System: macOS

When looking up the shortcuts for this app I saw that there is touchbar support. The problem is I can't get the touchbar to show any of the shortcuts available. Is there a setting that I am missing that needs to be turned on?

**Comment by stephanoparaskeva** [comment]
Did you figure this out?

Currently I can't:
Use any shortcuts (cmd+r etc)
See touchbar 

Additionally I'm not sure how to set this up to view redux state... any ideas?
