### ISSUE TITLE
Is there a way to see a breakdown of a given element?

### ISSUE THREAD

**Issue by gabeDevlift** [jhen0409/react-native-debugger#496]
In version 0.11.1, is there a way to see a breakdown of an element that you select, like its size, padding etc? I think I remember you were able to do this in previous versions. See image below from Chrome devtools.

![Screen Shot 2020-04-17 at 4 01 03 PM](https://user-images.githubusercontent.com/43910963/79609505-de50bd00-80c4-11ea-94f2-ed78c0dc2c2f.png)

**Comment by jhen0409** [comment]
It's not implemented on react-devtools v4. If you want this feature back, you can send a feature request on [`facebook/react/issues`](https://github.com/facebook/react/issues).
