### ISSUE TITLE
Packager running on non default port - error message "Failed to execute 'importScripts' (...)"

### ISSUE THREAD

**Issue by chmurson** [jhen0409/react-native-debugger#50]
Hello!

I'm running packager on port 8082. Everything is fine, e.g. HMR is working. When I enter remote debug mode I get following error on emulator.

<img width="401" alt="zrzut ekranu 2017-02-28 o 10 08 05" src="https://cloud.githubusercontent.com/assets/16591876/23398727/f2325cb4-fd9d-11e6-9704-aed91cb7ee55.png">

In Network Tab of React Native Debugger I can see that following HTTP request has been made:
http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false
```
Request URL:http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false
Request Method:GET
Status Code:403 Forbidden
Remote Address:[::1]:8081
```

I guess it should make a request that targets localhost:**8082** not localhost:8081, since this is where packager is listening. 

I could not find easy way to change a port, so remote debugging could work. How to change it ?

React Native version: 0.41.2 & 0.38
React Native boilerplate: https://github.com/jhen0409/react-native-boilerplate
Platform: Android,
Is real device of platform: No
Operating System: macOS

**Comment by jhen0409** [comment]
You can read the official doc: [`Using a port other than 8081`](http://facebook.github.io/react-native/releases/0.41/docs/troubleshooting.html#using-a-port-other-than-8081)

> You will also need to update your applications to load the JavaScript bundle from the new port. Open the in-app `Developer menu`, then go to __Dev Settings → Debug server host for device__ and replace 8081 with your port of choice.

Just use `localhost:8082` for that.

**Comment by chmurson** [comment]
Thanks @jhen0409 for response. I had been doing that. As I wrote in the description of the issue:

> I'm running packager on port 8082. Everything is fine, e.g. HMR is working.

**Comment by jhen0409** [comment]
Ahh I figured out it, it seems still load `localhost:8081` when toggled to debug remotely mode, I can sure it's official issue, have a same issue here -> https://github.com/facebook/react-native/issues/12527.

**Comment by chmursonss** [comment]
Thanks! I should have test it with basic setup for react native before posting here!

**Comment by chmursonss** [comment]
Should we keep it open, and once https://github.com/facebook/react-native/issues/12527 get fixed, double check if it works for `react-native-debugger` as well?

**Comment by jhen0409** [comment]
It looks https://github.com/facebook/react-native/pull/12095 have been landed, should release as the next rc version. (0.46-rc)

**Comment by jhen0409** [comment]
I confirmed it works fine on RN 0.46.
