### ISSUE TITLE
How to uninstall react native debugger?

### ISSUE THREAD

**Issue by timsonater** [jhen0409/react-native-debugger#501]
Hi, this is definitely a simple question but I cannot seem to figure out how to remove this from an expo project. I have removed it from my applications folder (I am on a mac) but every time I launch the simulator React Native Debugger still pops up in safari. Any Advice?

**Comment by anfo000** [comment]
You just type cmd + m and disable the Remote Debugging from there

**Comment by jhen0409** [comment]
It's possible if you're using [the npm-package](https://github.com/jhen0409/react-native-debugger/tree/master/npm-package), so just remove that package. Otherwise, Expo shouldn't try to open React Native Debugger.
