### ISSUE TITLE
RN dev tools stating that v4 is incompatible, even after installing v3.

### ISSUE THREAD

**Issue by By-Tor2114** [jhen0409/react-native-debugger#508]
React Native Debugger app version: 0.11.2
React Native version: 0.61.4
Platform: Android
Is real device of platform: No
Operating System: Windows

Running a virtual Android device via expo, and all of that works/connects perfectly. When I launch the RN dev tools, and change the port to 19001, it connects, but presents me with the following message, stating that DevTools v4 is incomptible with this version of React.

![Dev tools](https://user-images.githubusercontent.com/52948766/81158484-ef804180-8f7f-11ea-9800-4486dbf880b5.PNG)

EDIT: The console eventually produces the following message:

![Dev tools message](https://user-images.githubusercontent.com/52948766/81159073-82b97700-8f80-11ea-9512-8aef43eabff3.PNG)

I followed the instructions in the screenshot (to install dev tool v3). When I tried to reconnect, the same message persisted. I tried restarting the app, dev tools, expo, and even tried a full reboot, but the same message persists after running the command to install dev tools v3. Here is a screenshot of my package.json:

![Deps](https://user-images.githubusercontent.com/52948766/81158812-41c16280-8f80-11ea-807e-2b4c8c2dc679.PNG)

**Comment by jhen0409** [comment]
Please read [react-native compatibility notice](https://github.com/jhen0409/react-native-debugger#notice-react-native-compatibility) on readme, or startup log message of React Native Debugger.
