### ISSUE TITLE
Blank components tree

### ISSUE THREAD

**Issue by aZolo77** [jhen0409/react-native-debugger#510]
<!--
Before submitting the issue:

Hi!
I'm using Expo to run my RN-App. I installed RN-Debugger by downloading .zip file for Windows from here https://github.com/jhen0409/react-native-debugger/releases and unpacked it in folder next to my App folder.
When i run my app with Expo and run it with Android Studio Emulator, i try to debug it with RN-debugger on port 19001 (I change it of course before on new Tab in debugger) it shows me console.log from my App and reacts to all handlers but i don't see any components tree(
What do I do wrong?

**Comment by jhen0409** [comment]
Please provide the necessary information with issue template.
