### ISSUE TITLE
"Computed" visualized dimension cannot be found

### ISSUE THREAD

**Issue by nogamenofun98** [jhen0409/react-native-debugger#512]
React Native Debugger app version: 0.11.3
React Native version: 0.62.2
Platform: Android
Is real device of platform: Yes
Operating System: Windows 10

![image](https://user-images.githubusercontent.com/9070825/83090422-513d5280-a0cb-11ea-81c7-9c5640f6a255.png)

i saw some image on Internet that the debugger has this feature like the one in chrome developer tools.
![image](https://user-images.githubusercontent.com/9070825/83090521-89dd2c00-a0cb-11ea-9eb4-64f8d986e934.png)

but i cannot found this in the debugger.
and the "view source of this element" seems like doesnt show anything after clicked.
![image](https://user-images.githubusercontent.com/9070825/83090582-ad07db80-a0cb-11ea-8e92-7adc88d2fc2e.png)

**Comment by jhen0409** [comment]
Please see https://github.com/jhen0409/react-native-debugger/issues/496#issuecomment-623867308.
