### ISSUE TITLE
v0.10 Developer Tools crash on Ubuntu 20.04

### ISSUE THREAD

**Issue by wnz99** [jhen0409/react-native-debugger#516]
React Native Debugger app version: v0.10
React Native version: Expo SDK 37.0.0 - RN 0.61
Platform: Android
Is real device of platform:No
Operating System: Ubuntu 20.04

Hi, I just wanted to report that Developer Toots cashes with the following error on Ubuntu 20.04:

`seccomp-bpf failure in syscall 0230 `

This workaround fixes the issue:

https://github.com/rstudio/rstudio/issues/6782#issuecomment-625915754

**Comment by rwanito** [comment]
Hello,
I Have the same problem.
Is it possible de build with the new flag ?

Thanks !

**Comment by thienhophu** [comment]
Thanks to @wnz99 

Run this in terminal to open it with this argument: 
react-native-debugger --disable-seccomp-filter-sandbox

Please careful that if you close or end the process (Ctrl +C), the app will be closed as well.

Operating System: PopOS 20.04

**Comment by wnz99** [comment]
I've noticed that RND still crashes randomly after a while even if started with that flag.

**Comment by AnthonyWard** [comment]
I have created a fix here: https://github.com/jhen0409/react-native-debugger/pull/531

**Comment by jhen0409** [comment]
Released as v0.10.11. Thanks @AnthonyWard!
