### ISSUE TITLE
How to view dimensions (height/width etc.) of an element

### ISSUE THREAD

**Issue by jordanmkoncz** [jhen0409/react-native-debugger#52]
I've been using react-native-debugger without any issues for a while now, but one thing I haven't been able to figure out is how to view the dimensions (height/width etc.) of an element. When I click on an element in the hierarchy, the side panel shows the element name, props, and applied styles, but I can't find any way to see the actual rendered dimensions of the element. This is something that was possible to view when using the built in react-native inspector.

React Native version: 15.4.0
Platform: iOS
Is real device of platform: No, Simulator
Operating System: macOS

**Comment by thurt** [comment]
curious about this as well. chrome devtools calls this "computed" styles when inspecting regular web css

**Comment by jhen0409** [comment]
Currently we can [change this line](https://github.com/facebook/react-native/blob/master/Libraries/Inspector/InspectorPanel.js#L70) to keep the built-in inspector contents, I may try to PR for show / hide the contents.

The goal is show the information in `react-devtools`, I think it's possible to make plugin for RN on [here](https://github.com/facebook/react-devtools/tree/master/plugins).

**Comment by jordanmkoncz** [comment]
@jhen0409 Yeah even if there was some way to view the built in react-native inspector that shows this information already, that would be great.

**Comment by jhen0409** [comment]
I simply implemented it in https://github.com/facebook/react-devtools/pull/590, hope this feature can be landed in the future. :)

**Comment by jordanmkoncz** [comment]
@jhen0409 Okay great, thanks for that. I guess now we just wait for your pull request to be included in an upcoming release.

**Comment by jhen0409** [comment]
Released as [`v0.6.4`](https://github.com/jhen0409/react-native-debugger/releases/tag/v0.6.4).  🎉

**Comment by jordanmkoncz** [comment]
@jhen0409 How do you view the dimensions? I've got the latest version but I'm not sure how to see the dimensions.

**Comment by jhen0409** [comment]
@jordanmkoncz you need ensure `react-devtools-core` version is ^2.1.0 in your RN project (use `npm list react-devtools-core` check it), it's dependency of react-native. (starts with v0.43)

Inspect the measurable nodes, it should shown on `React Native Style Editor`.

**Comment by jordanmkoncz** [comment]
@jhen0409 Ah I see, my project is currently using React Native v0.41.2. I guess I'll have to upgrade to the latest version then! Cheers.
