### ISSUE TITLE
DevTools 4.6.0 doesn't show list of components

### ISSUE THREAD

**Issue by stevecode21** [jhen0409/react-native-debugger#523]
Hey.

My React Native Debugger doesn't show nothing on devtools:

![DevTools](https://user-images.githubusercontent.com/59179297/86550357-c04a6a00-bf07-11ea-8e61-f114b9d09772.JPG)

Operating System: Windows 10
I'm working with Expo: 37.0.0 
React Native Version: 0.61.4

**Comment by jhen0409** [comment]
The DevTools v4 was built-in for RNDebugger v0.11, and it's only supported React Native >= 0.62. Please downgrade the debugger app or upgrade your project.
