### ISSUE TITLE
How do you open the element inspector?

### ISSUE THREAD

**Issue by rostgoat** [jhen0409/react-native-debugger#525]
How do I open the element inspector?

![image](https://user-images.githubusercontent.com/22672124/86975549-6925de80-c12d-11ea-92c8-b886acbfe5a4.png)

React Native Debugger app version: 0.11.3
React Native version: 0.62.2
Platform: ios
Is real device of platform: simulator
Operating System: macOS

**Comment by jhen0409** [comment]
Please see https://github.com/jhen0409/react-native-debugger/issues/496#issuecomment-623867308.
