### ISSUE TITLE
How to hide element parent list

### ISSUE THREAD

**Issue by jordanmkoncz** [jhen0409/react-native-debugger#53]
Is there any way to hide the element parent list that appears when you inspect an element? I'm referring to the following part of the React Native Debugger interface:

<img width="653" alt="screen shot 2017-03-06 at 1 34 27 pm" src="https://cloud.githubusercontent.com/assets/3453584/23594889/c5e33470-0271-11e7-821e-ed76c962bf69.png">

I find that this part of the interface often ends up having such a high number of items in the element parent list that it takes up a huge amount of space in the interface, but doesn't really provide much value since the view above it with the full element hierarchy gives you the same information anyway. I'd like to completely hide this element parent list view, is that possible?

React Native version: 15.4.0
Platform: iOS
Is real device of platform: No, Simulator
Operating System: macOS

**Comment by jhen0409** [comment]
Recently `react-devtools` have a fixed height and scrollable for the list, currently it released as [beta version](https://github.com/jhen0409/react-native-debugger/releases/tag/0.6.0-beta2) of react-native-debugger.

The ideal situation should be make it the same with behavior of Chrome DevTools, submit new issue to [`react-devtools`](https://github.com/facebook/react-devtools) will be better. :)

**Comment by jordanmkoncz** [comment]
@jhen0409 Okay great, I guess I'll just wait for the next release then. Any rough ETA on when that will be?

**Comment by jhen0409** [comment]
It's released. :)

**Comment by jordanmkoncz** [comment]
@jhen0409 Just updated to the new release, that's much better now!
