### ISSUE TITLE
Can't reload Chrome dev tools

### ISSUE THREAD

**Issue by tlvince** [jhen0409/react-native-debugger#54]
If (JS) hot reload is enabled, due to a bug in [DevTools](https://bugs.chromium.org/p/chromium/issues/detail?id=438251), the source map is not reloaded. The suggested workaround of reloading dev tools with `alt+r` does not seem to work in react-native-debugger, nor does toggling via `alt+cmd+i`.

React Native version: 0.40
Platform: Android
Is real device of platform: Yes
Operating System: macOS
react-native-debugger version: 0.6.0-beta2

**Comment by jhen0409** [comment]
It does not seem to work in the official debugger of browser also, but re-open the devtools with `cmd+option+i` is work for me.

**Comment by tlvince** [comment]
Working for me now as well. Thanks.
