### ISSUE TITLE
Always attempting reconnection

### ISSUE THREAD

**Issue by hans-permana** [jhen0409/react-native-debugger#563]
React Native Debugger app version: 0.11.6
React Native version: 0.63.4 (as part of expo 40.0.0)
Platform: Android
Is real device of platform: Using Android Emulator
Operating System: Windows

I had been developing my RN app using RND and it was working fine for a while, and it suddenly broke after I updated my expo to 40.0.0. However, I am not sure if the issue is due to the upgrade. Now, everytime I start the RND standalone, I always get a message "Attempting reconnection" at the window title, and when the app in the android emulator is started, the debugger in the chrome tab is initiated instead of it connecting to the standalone one. 

![rnd-issue](https://user-images.githubusercontent.com/7643370/102294566-2984dd80-3f7c-11eb-8063-c72cea51ef70.png)

The problem with the one on the Chrome is that it cannot show the network inspection (or can it?) 

Thank you for your help!

**Comment by hans-permana** [comment]
Turned out by using port **19000** the RND can connect to the emulator device. Maybe in the new expo the default port number is changed? Anyway, I will close this issue since I can use RND again.

**Comment by dolubajo** [comment]
Worked for me. +1

**Comment by yxzhaoo** [comment]
> Turned out by using port **19000** the RND can connect to the emulator device. Maybe in the new expo the default port number is changed? Anyway, I will close this issue since I can use RND again.
How to turn out the port to 19000?

**Comment by hans-permana** [comment]
@yxzhaoo one way is to open a new RND window by pressing CTRL + t , and then specify the port number and click confirm

![image](https://user-images.githubusercontent.com/7643370/106168876-59511300-61c1-11eb-9941-efe8f3c1c1ff.png)
