### ISSUE TITLE
Error on installation using brew: non-checksummed download not supported (0.10)

### ISSUE THREAD

**Issue by stefanoeb** [jhen0409/react-native-debugger#567]
React Native Debugger app version: -
React Native version: -
OS: MacBook Pro with M1 processor

While following the docs to install the debugger using `brew` (version 2.7.1) I got the following error:

```
brew install --cask https://raw.githubusercontent.com/Homebrew/homebrew-cask/b6ac3795c1df9f97242481c0817b1165e3e6306a/Casks/react-native-debugger.rb

Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 164 formulae.

Traceback (most recent call last):
'brew extract' or 'brew create' and 'brew tap-new' to create a formula file in a tap on GitHub instead.: 
Invalid usage: Non-checksummed download of react-native-debugger formula file from an arbitrary URL is unsupported!  (UsageError)
```

**Comment by stefanoeb** [comment]
UPDATE: `brew install --cask react-native-debugger` worked, will propose an update to the documentation.

**Comment by GunnarAK** [comment]
Running into same issue. Not being able to debug my apps (RN0.61.5) is, of course, very very cumbersome.

**Comment by kai-kb** [comment]
cURL alternative to the solution above:
```
curl -L https://raw.githubusercontent.com/Homebrew/homebrew-cask/b6ac3795c1df9f97242481c0817b1165e3e6306a/Casks/react-native-debugger.rb > react-native-debugger.rb && brew install react-native-debugger.rb
``` 
Then optionally rm react-native-debugger.rb

**Comment by jerrylau91** [comment]
@kai-kb thanks for the tip!

**Comment by stefanoeb** [comment]
Closing since this is fixed on the recent version and we can curl it directly

**Comment by petervn** [comment]
> cURL alternative to the solution above:
> 
> ```
> curl -L https://raw.githubusercontent.com/Homebrew/homebrew-cask/b6ac3795c1df9f97242481c0817b1165e3e6306a/Casks/react-native-debugger.rb > react-native-debugger.rb && brew install react-native-debugger.rb
> ```
> 
> Then optionally `rm react-native-debugger.rb` to clean up.

you make my day,
thank you alot.
