### ISSUE TITLE
Hermes support

### ISSUE THREAD

**Issue by Ashoat** [jhen0409/react-native-debugger#573]
Hey, I just wanted to check to see if there's any interest / work on Hermes support for the React Native Debugger. The React Native team's work on JSI is still in progress, but once that is launched the approach of running the JS thread remotely won't work anymore, since JSI relies on having shared memory access between the JS thread and the native thread, which isn't possible when the two threads are running on different hosts.

The way that the React Native team is looking to address this is with Hermes, their custom JS runtime. JSI works with both Hermes and JSC, but the Hermes team has [implemented](https://reactnative.dev/docs/hermes#debugging-js-on-hermes-using-google-chromes-devtools) the Chrome inspector protocol for Hermes, which allows the Chrome debugger running on a laptop to communicate with the Hermes runtime running on a device.

It's also possible to debug Apple's JSC through Safari, which IIRC relies on a similar "remote inspection" approach. It probably won't be easy to integrate with RND though, since RND is based on the Chrome toolset.

Given that context, it seems like the best way forward for RND to work with JSI is through Hermes. The [link](https://reactnative.dev/docs/hermes#debugging-js-on-hermes-using-google-chromes-devtools) above explains how to get the Chrome debugger working with Hermes – I'm guessing that something similar can be done to get RND working with Hermes.

**Comment by madandrija** [comment]
If this isn't done, I'm not sure there will be any use for RND since [apps crash when they touch code that uses TurboModules](https://github.com/software-mansion/react-native-reanimated/issues/1663#issuecomment-770769922)

**Comment by rusakovic** [comment]
It's the most important feature for implementing.
All of us will be glad to see your best react native debugger with Hermes.
Flipper - is  a bull shit in comparison with your debugger!!

**Comment by pavermakov** [comment]
@rusakovic I'm glad I'm not the only one who can't stand flipper. Too bad flipper is now shipped and installed by default.

**Comment by minhchienwikipedia** [comment]
Same to me, I hope we can use RN Debugger for it, I don't want to use Flipper, it's too bad, it's hard to use, too much setup...!   I hope you guys can do it ASAP, thank you guys for what you did!

**Comment by minhchienwikipedia** [comment]
I found it, we can use Reanimated 2 with React Native Debugger until version `2.3.0-alpha.2` (suggest using version 2.3.0-beta.2 for now) or you can wait for official version, this is only a beta version 
https://github.com/software-mansion/react-native-reanimated/releases/tag/2.3.0-alpha.2 - Added chrome debugger support

**Comment by msageryd** [comment]
This would be awesome!
I have had a couple of weeks with Flipper. I thought Flipper was the *new* way to go. I even uninstalled RND, since I couldn't run it with Hermes anyway. Flipper has some nice features, but it's soo slow. Debugging Redux actions with Flipper is a PITA.

I have now reinstalled RND and will go back to V8 until RND supports Hermes. My thumbs up for this feature.

**Comment by mikeduminy** [comment]
How would this be accomplished in theory?

**Comment by imisshtml** [comment]
Yes, this would be helpful. Flipper is really horrible and on my machine it takes up too much processing power.

**Comment by vmechiev** [comment]
I hope u will implement hermes support, guys, because I don't want to use Flipper, bcs it is difficult to configurate and not so convinient as your tool.

**Comment by Ashoat** [comment]
If somebody is interested in adding a Flipper plugin with support for the Redux debugger, let me know. I don't currently have the cycles to work on it, but I have pretty good context on the problem and what it would take to solve it.

**Comment by Slapbox** [comment]
This just shot to the top of my wishlist when Flipper decided it wasn't going to work on any of my machines or projects one day...

**Comment by klitko13** [comment]
Up

**Comment by Reactor-Labs** [comment]
I'm using Reactotron and Flipper and both seem to be good options

https://github.com/infinitered/reactotron

https://fbflipper.com/

**Comment by HanggiAnggono** [comment]
> I'm using Reactotron and Flipper and both seem to be good options
> 
> https://github.com/infinitered/reactotron
> 
> https://fbflipper.com/

is it possible to use reactotron without integrating with our project directly?

**Comment by Reactor-Labs** [comment]
@HanggiAnggono here is the quick start for react native https://github.com/infinitered/reactotron/blob/master/docs/quick-start-react-native.md but to answer your question you have to integrate it with your project, thought it doesn't run in production.

**Comment by kvlknctk** [comment]
If an advanced console log output is made for reactotron, the others are not needed much. you may just need a simple browser to open an advanced debugger. webstorm handles this nicely. There is no need to deal with such nonsense. Decisions that will affect the workspace environment of many software developers are taken and are made without asking anyone. This issue bothered me a lot.

**Comment by Slapbox** [comment]
For anyone using Expo, SDK 47 beta supports Hermes debugging without relying on Flipper.

**Comment by Ashoat** [comment]
Expo 47 is a gamechanger!! So exciting to have this `debugger` working again for the first time since switching to Hermes.

With this change, wondering – is there any way to get `react-native-debugger` working with Hermes through Expo?

**Comment by clayrisser** [comment]
@Ashoat I have the same question. I am holding off switching to hermes because I'm waiting for rnd support for hermes in expo.

**Comment by toplac** [comment]
Any update on this Issue?

**Comment by Slapbox** [comment]
@clayrisser I very much doubt it's ever happening.

**Comment by albanx** [comment]
+1

**Comment by jalvarson** [comment]
+1 Really need this.

**Comment by Slapbox** [comment]
To everyone saying they really need this - you probably don't. _Why_ do you need it?

I am not a maintainer, but I want to reiterate how exceedingly unlikely it is that this will happen. This package is currently based on a version of Electron that is 10 behind the oldest still-supported version, and integrating Hermes is a big ask when there are other comparable tools now that did not exist when this project began.

**Comment by davidtiede** [comment]
> To everyone saying they really need this - you probably don't. _Why_ do you need it?
> 
> I am not a maintainer, but I want to reiterate how exceedingly unlikely it is that this will happen. This package is currently based on a version of Electron that is 10 behind the oldest still-supported version, and integrating Hermes is a big ask when there are other comparable tools now that did not exist when this project began.

The main reason for me is that Flipper is not compatible with `@react-native-firebase/app`, so right out of the box I'm without a debugger. `Chrome://inspect` seems nothing more than a familiar console and `react-devtools` works fine for inspecting react components / state, but both of these tools lack a network inspector (as far as I can tell). If `react-native-debugger` supported Hermes, debugging network requests would be possible.

**Comment by Slapbox** [comment]
@davidtiede that's fair - but I wouldn't get your hopes up that this will ever happen. 

If somebody needs it, it's likely they're going to have to be the one to figure it out and submit a PR. This issue has been open for years as releases of the project become more infrequent and the maintainers have never replied to this issue.

**Comment by davidtiede** [comment]
@Slapbox no I'm sure you're right.. It's a bit frustrating coming from the web world where DevTools are the standard, but mobile debugging seems like an after thought. I'll just `console.log` everything for now.

**Comment by Slapbox** [comment]
I've waited for over 3 years thinking mobile development would stop sucking any day now - but it just hasn't materialized sadly.

**Comment by Ashoat** [comment]
At Comm we've set up `react-devtools`, `redux-devtools`, and JS debugging via `expo-dev-client` without Flipper. It all works with Hermes, and we're able to fully replace all of the functionality in `react-native-debugger` with this stack.

Unfortunately it does require a lot of project configuration, and we don't have the cycles right now to package it into a standalone project like `react-native-debugger`. That said, our codebase is open source: https://github.com/CommE2E/comm

**Comment by gusgard** [comment]
I'm using `react-native-debugger` with Hermes and Firebase, could you try https://www.npmjs.com/package/react-native-devsettings?activeTab=readme? 



Related to: https://github.com/jhen0409/react-native-debugger/issues/755

**Comment by jaexplorer** [comment]
@gusgard trying now

**Comment by jaexplorer** [comment]
@gusgard Omg I love you this works.

**Comment by jncampbell** [comment]
We could really use some communication regarding if this is on the table or not. This tool no longer works with any react native versions that use the default hermes engine. It's totally fine if support is not on the horizon but I think that should be communicated so folks can look for (or build) more future-proof solutions.

**Comment by aleksandarbos** [comment]
i'm using expo v48,
after installation, and starting expo `npx expo start` and then enabling `› Press j │ open debugger` because there is no longer remote debugging option available, i get hermes debugger opened as `js devtools`. then when i make new window and set tab to `19000` for react native debugger it says pending and waiting:

![image](https://github.com/jhen0409/react-native-debugger/assets/15141614/aaee721c-cf3c-44c5-8dc7-61c68b470af6)


any ideas on how to solve this? thanks much!

**Comment by jhen0409** [comment]
Sorry for being late, I'll close this first. I created a new discussion about this, if you want to know any news about Hermes debugger support in RNDebugger, you can follow https://github.com/jhen0409/react-native-debugger/discussions/774.

**Comment by rolfen** [comment]
I hear that `console.log()` is still supported!
