### ISSUE TITLE
"Waiting for React to connect" when debugging Android devices

### ISSUE THREAD

**Issue by irrigator** [jhen0409/react-native-debugger#58]
** Please ensure:

- [ ] I'm using the latest version of react-native-debugger
- [ ] I have read [README.md](https://github.com/jhen0409/react-native-debugger/blob/master/README.md)

** Please provide the following information if you found some bugs or have question:

React Native version: [0.42]
Platform: [Android]
Is real device of platform: [real device]
Operating System: [macOS]

I follow the README but the React inspector keeps showing "Waiting for React to connect...". Break points do work.

**Comment by jhen0409** [comment]
[This section](https://github.com/jhen0409/react-native-debugger#use-real-device) (`Use real device`) didn't help you? Could you share your code as change `setupDevtools.js` for `>= 0.37`? Or have you run `adb reverse tcp:8097 tcp:8097` if you're debug via USB?

**Comment by irrigator** [comment]
I run `adb reverse tcp:8091 tcp:8091` and everything works. I didn't run it because I get RN 42 running on Android device without setting the host IP, so I assume it might have been done for me in this new version of RN.

Thanks for your answer. I should have tried harder before I file the issue.
