### ISSUE TITLE
RND in Fullscreen on Mac OS hot-reloading doesn't work if screen out of view

### ISSUE THREAD

**Issue by wkw** [jhen0409/react-native-debugger#59]
**RND v0.6.2, Mac OS 10.11.6**

I noticed yesterday that putting RND into it's own "Space" (full screen mode), if I have moved to a different "Space" hiding RND, hot reloading does not happen until I bring RND back into view. I don't think this is an RND problem, however I'm wondering if others have run into this issue?

Great tool, by the way!

**Comment by jhen0409** [comment]
> I noticed yesterday that putting RND into it's own "Space" (full screen mode), if I have moved to a different "Space" hiding RND

The same with https://github.com/jhen0409/react-native-debugger/issues/47, we have some problems of app invisible for Chrome 54 ~ 56, currently we need keep the app visible.

[Chrome 58 upgrade for Electron](https://github.com/electron/libchromiumcontent/tree/chrome58) have been in progress on upstream.

**Comment by wkw** [comment]
Sorry for double-posting. I looked through the existing issues by issed #47. Thanks for response.
