### ISSUE TITLE
PATCH requests ignore their body

### ISSUE THREAD

**Issue by atlanteh** [jhen0409/react-native-debugger#60]
** Please provide the following information if you found some bugs or have question:

React Native version: 41.3
Platform: iOS
Is real device of platform: No
Operating System: macOS
React Native Debugger: 0.6.2

When using react-native-debugger, all PATCH requests which have a body, just drop it and the server receives an empty body:

`fetch('http://myServer.com/test', {method: 'PATCH', body: {test: 1234}});`

when I use POST, it's working fine.

I'm have react-native-fetch-blob in my app and it polyfills xor, blob and fetch, so this might be what's causing it.

**Comment by jhen0409** [comment]
Just simple tried `PATCH` original fetch with `json-server` it works fine.

> I'm have react-native-fetch-blob in my app and it polyfills xor, blob and fetch, so this might be what's causing it.

I don't think it related here, have you tried it with `http://localhost:8081/debugger-ui`? I think there should be some reason causing the problem for the module in `Debug JS remotely` mode.

I'll try it when I have time.

**Comment by jhen0409** [comment]
I can reproduce the `react-native-fetch-blob` problem, but it still ignore body with `PATCH` request if I leave `Debug JS remotely` mode, it just called [the native method](https://github.com/wkh237/react-native-fetch-blob/blob/master/ios/RNFetchBlobReqBuilder.m#L83), so I'm sure it not related here. :\
