### ISSUE TITLE
Can not inspect elements

### ISSUE THREAD

**Issue by lgmf-daitan** [jhen0409/react-native-debugger#612]
Hello, 

Everything is working perfectly but the element inspector. Every time I try to inspect an element I'm receiving the error message: 
"Could not inspect element with id X"

React Native Debugger app version: 0.11.8
React Native version: "react-native": "~0.63.4",
Platform: Android Emulator
Is real device of platform: No
Operating System: Ubuntu 18.04.5 LTS

![image](https://user-images.githubusercontent.com/66316737/119380560-45ad4900-bc97-11eb-8ee5-db388de74a4c.png)

**Comment by jhen0409** [comment]
I think this is already fixed in v0.11.9. Just in case, please read [this doc](https://github.com/jhen0409/react-native-debugger/blob/master/docs/react-devtools-integration.md#question-i-got-unsupported-message-from-react-devtools) also.

**Comment by lgmf-daitan** [comment]
Thanks for the answer! 

I've upgrade to the latest version and I added the resolution in my package.json

![image](https://user-images.githubusercontent.com/66316737/119498857-73989900-bd3c-11eb-930e-7c8f9b44c625.png)

Now it's connecting but still the modal appears and prevents me to use

![image](https://user-images.githubusercontent.com/66316737/119498909-8743ff80-bd3c-11eb-87a7-a7d680b6662a.png)

I'm using in a React Native app

**Comment by jhen0409** [comment]
@lgmf-daitan You need to ensure the version is matched. So it's react-devtools-core@4.13.4.

**Comment by lgmf-daitan** [comment]
Ok! I'm so sorry... It was just an example in the docs.

Now its working properly!

Thanks a lot
