### ISSUE TITLE
React Native Debugger doesn't use the global react-devtools version and still shows 'Unsupported' error

### ISSUE THREAD

**Issue by abogdan0505** [jhen0409/react-native-debugger#620]
Hello all,

I'm having trouble using react native debugger. **I get the 'Unsupported' error telling me to downgrade to 4.11.0.**
After I ran `npm i -g react-devtools@"4.11.0"`, it installed the `react-devtools@4.10.4` version globally. I checked that with `npm list -g` and it was installed correctly.

The issue is that even though **I have the react-devtools version 4.10.4 installed globally**, I still see the same 'Unsupported' error message.

In the react native debugger app, the **DevTools header still indicates version 4.13.4-51ebccc374** which I guess was installed by default when I installed react native debugger.

It seems that **React Native Debugger doesn't use the global react-devtools version**.

I installed react native debugger with homebrew: `brew install --cask react-native-debugger`

I already tried uninstalling react native debugger, react-devtools and reinstalling everything again. With no success though..

Any ideas what else can I try ?

React Native Debugger app version: 0.11.9
React Native version: 0.62.2
Platform: iOS
Operating System: macOS Big Sur 11.4
Homebrew version: 3.1.9

**Comment by jhen0409** [comment]
Please see the [release note](https://github.com/jhen0409/react-native-debugger/releases/tag/v0.11.9):

# Note about React DevTools

If you got `Unsupported` message or some errors from React DevTools, please read the [`documentation`](https://github.com/jhen0409/react-native-debugger/blob/master/docs/react-devtools-integration.md#question-i-got-unsupported-meesage-from-react-devtools) first.

## __*Question*__: I got `Unsupported` meesage from React DevTools

If you're using React Native version >= 0.62 and keep React Native Debugger as the latest version, here is what you can do:

In your app project, upgrade `react-devtools-core` dependency to match the React DevTools version:

- OPTION 1: Just `yarn upgrade react-native`
- OPTION 2: Delete `react-devtools-core` block in yarn.lock, then re-install dependencies by `yarn`

**Comment by Arkan4ik** [comment]
@jhen0409 it does not work and not clear solution. I removed from yarn.lock as you wrote, but got error when run application. Then I installed react-dev-tools in dev dependency and project start working, but error that 'Unsupported DevTools backend version
' is still reproduced. It is annoing thing espacially if you have several projects with different react native version.

**Comment by jhen0409** [comment]
> it does not work and not clear solution. I removed from yarn.lock as you wrote, but got error when run application. 

@Arkan4ik what error did you got from running application?

Here is another method:

- Use [yarn resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/), just add `"react-devtools-core": "^4.13.4"` to resolutions of package.json.

**Comment by ArkanRomanPango** [comment]
@jhen0409 thanks.  yarn resolutions and then updating global package works. I also see that you updated the doc. Awesome. Thank you

**Comment by Arkan4ik** [comment]
@jhen0409 thanks. yarn resolutions and then updating global package works. I also see that you updated the doc. Awesome. Thank you

**Comment by jack-ayoka** [comment]
@jhen0409 I'm still receiving this error after trying all 3 options. My package-lock.json has react-devtools version 4.13.4, same as the one in the debugger. Then i run `npx react-native run-android`, and I get the 'Unsupported' error.
To clarify, does the backend version(react native renderer) rely on the frontend version(react native debugger)? Because having to update the dependencies of production code to work with the debugger seems wrong... 

Is there any way to manually set the frontend version being used by RN Debugger?

**Comment by Arkan4ik** [comment]
@jack-ayoka I can describe what I did.
1) in your package json add resolution
<img src="https://user-images.githubusercontent.com/23438777/121304196-b5147100-c904-11eb-9806-d7f6cbc0fc35.png" width="200" />
2)yarn/npm install - it will change in yarn.lock/package-lock file version of react-dev-core
<img src="https://user-images.githubusercontent.com/23438777/121304384-f1e06800-c904-11eb-9e3d-1e24e847187d.png" width="200" />
3)install globally react-devtools
4)paste command from RN debugger which you receive in terminal and execute.

**Comment by jack-ayoka** [comment]
> @jack-ayoka I can describe what I did.
> 
> 1. in your package json add resolution
> 
> <img alt="" width="500" src="https://user-images.githubusercontent.com/23438777/121304196-b5147100-c904-11eb-9806-d7f6cbc0fc35.png">
> 
> 1. yarn/npm install - it will change in yarn.lock/package-lock file version of react-dev-core <img alt="" width="500" src="https://user-images.githubusercontent.com/23438777/121304384-f1e06800-c904-11eb-9e3d-1e24e847187d.png">
> 2. install globally react-devtools if you don't have
> 3. paste command from RN debugger which you receive in terminal and execute. <img alt="" width="500" src="https://user-images.githubusercontent.com/23438777/121304994-babe8680-c905-11eb-935a-0a5c4f712880.png">

After banging on this for hours yesterday, this worked!!!!! thank you so much!
Do note, i also had to _uninstall_ react-devtools and react-devtools-core from my local project. so the only thing referencing react-devtools locally was react-native, and the 'resolutions' section.

**Comment by vishnuc** [comment]
I have referred the documentation , but its the same issue

**Comment by RewriteH** [comment]
> I have referred the documentation , but its the same issue

if you use npm, delete package.lock and install again with yarn, it helps me..

**Comment by vishnuc** [comment]
I use npm  , for some reasons my expo project breaks if i run yarn.. so any solutions with NPM ?

**Comment by 0x0a0d** [comment]
for anyone who still find solution
Note: I'm running `MacOS 10.15.7 (19H114)`

 first download react-native-debugger. **Then you must open it at least 1 time**
```bash
npm i -g asar
asar e /Applications/React\ Native\ Debugger.app/Contents/Resources/app.asar /tmp/app
cd /tmp/app

# option 1
npm install react-devtools-core@^4 # or 4.22.1

## option 2
## If you still unlucky, try edit `/tmp/app/package.json` as below
# npm update react-devtools-core

# last step
asar p . /Applications/React\ Native\ Debugger.app/Contents/Resources/app.asar
```

![image](https://user-images.githubusercontent.com/32500015/147460092-2e47060c-75fa-4ecb-93fd-391232427274.png)

**Comment by anttiabel** [comment]
The "Unsupported DevTools backend version" error persists for me, having tried everything listed. The tool seems bent on using react-devtools 4.14.0-d0ec283819 no matter how I try to upgrade to 4.22.1 everywhere for both react-devtools and react-devtools-core. I am working on an Expo project, on a Mac.

**Comment by frags51** [comment]
Same for me as @anttiabel

**Comment by garrett-gottlieb** [comment]
Exact same as @anttiabel. I am making a new issue as it seems to be re-broken.

**Comment by junkboy0315** [comment]
I found `4.22.1 >= react-devtools-core` doesn't seem to be compatible with RNDebugger.

Minimal reproductive sample:
https://github.com/facebook/react/issues/23035#issuecomment-1010676425

**Comment by kidproquo** [comment]
> Exact same as @anttiabel. I am making a new issue as it seems to be re-broken.
> 
> EDIT: Changing to use the resolution of the version that RND is using fixed this issue:
> 
> ```
>   "resolutions": {
>     "react-devtools-core": "4.14.0"
>   },
> ```
> 
> DO NOT upgrade to 4.22.1, remove all of those and just add this resolution (in my case with yarn workspaces to the package.json that contains the RN project).

This worked for me. Started a brand new RN app, using CLI. Debugger showed version mismatch error. Added the resolution to `4.14.0`. Ran `yarn install`. Rebuilt app. Debugger works.

**Comment by mjstelly** [comment]
@garrett-gottlieb I added the `resolutions` entry to my `package.json`, restarted metro bundler with `--reset-cache` flag, and relaunched my app. No change. Same error. Any thoughts?

**Comment by bfricka** [comment]
> @garrett-gottlieb I added the `resolutions` entry to my `package.json`, restarted metro bundler with `--reset-cache` flag, and relaunched my app. No change. Same error. Any thoughts?

Did you `yarn install` / `yarn dedupe` after changing the resolutions?

**Comment by Kawinesh** [comment]
For me the error never went even if i added the below and did a npm i (expo project) and also i tried all possible solutions as well with NPM

```
"resolutions": {
    "react-devtools-core": "4.14.0"
  },
```
So i created a new expo project with `yarn` now instead of `npm` and added the above in `package.json` and run `yarn install` and `yarn start` surprise react native debugger worked with the **Unsupported** error (Tested only in android)

**Comment by jologz** [comment]
> For me the error never went even if i added the below and did a npm i (expo project) and also i tried all possible solutions as well with NPM
> 
> ```
> "resolutions": {
>     "react-devtools-core": "4.14.0"
>   },
> ```
> 
> So i created a new expo project with `yarn` now instead of `npm` and added the above in `package.json` and run `yarn install` and `yarn start` surprise react native debugger worked with the **Unsupported** error (Tested only in android)

This worked for me!  I was using npm and switched to yarn.  I had to `rm -r node_modules` and `rm -r package-lock.json` and do `yarn install` (`npm i -g yarn` if you don't have yarn yet) and surprisingly it worked!

**Comment by jologz** [comment]
For `npm` lovers, you can add a `"preinstall": "npx npm-force-resolutions"` script on your package.json.  This will force the resolutions found on your package.json.  More info [here](https://github.com/rogeriochaves/npm-force-resolutions).  Once you do an `npm i` you should see if the `react-devtools-core` is set to `4.14.0` (command: `npm ls react-devtools-core`) if not, do another `npm i` and it should resolve it to `4.14.0`

**Comment by joey-harward** [comment]
> for anyone who still find solution Note: I'm running `MacOS 10.15.7 (19H114)`
> 
> first download react-native-debugger. **Then you must open it at least 1 time**
> 
> ```shell
> npm i -g asar
> asar e /Applications/React\ Native\ Debugger.app/Contents/Resources/app.asar /tmp/app
> cd /tmp/app
> 
> # option 1
> npm install react-devtools-core@^4 # or 4.22.1
> 
> ## option 2
> ## If you still unlucky, try edit `/tmp/app/package.json` as photo below, then execute next line
> # npm update react-devtools-core
> 
> # last step
> asar p . /Applications/React\ Native\ Debugger.app/Contents/Resources/app.asar
> ```
> 
> ![image](https://user-images.githubusercontent.com/32500015/147460092-2e47060c-75fa-4ecb-93fd-391232427274.png)

This was exactly the fix that worked for me. Thanks!

**Comment by afilp** [comment]
Is there a different solution than having to add extra code in package.json? Thanks!

**Comment by dkang23** [comment]
I "npm install"ed 'react-devtools' and 'react-devtools-core' and set them to the same version

   "react-devtools": "~4.14.0",
   "react-devtools-core": "~4.14.0",
   
and re-installed everything by deleting package-lock.json and node_modules

then ran npm install and it worked

I think the problem was those packages not being the same version

**Comment by cglacet** [comment]
Why is every comment suggesting to pin to something like `4.14.0` when the error message says `<4.11`? Is the error message wrong and the requirement is rather `>4.11`?

I'm really confused by this error message.

**Comment by stenes90** [comment]
> 

This worked for me. Tnx a lot

**Comment by stenes90** [comment]
> For `npm` lovers, you can add a `"preinstall": "npx npm-force-resolutions"` script on your package.json. This will force the resolutions found on your package.json. More info [here](https://github.com/rogeriochaves/npm-force-resolutions). Once you do an `npm i` you should see if the `react-devtools-core` is set to `4.14.0` (command: `npm ls react-devtools-core`) if not, do another `npm i` and it should resolve it to `4.14.0`

This worked for me. Tnx

**Comment by jwboardman** [comment]
> Why is every comment suggesting to pin to something like `4.14.0` when the error message says `<4.11`? Is the error message wrong and the requirement is rather `>4.11`?
> 
> I'm really confused by this error message.

Your comment is what finally saved me! I changed my resolutions to:
  "resolutions": {
    "react-devtools-core": "4.14.0"
  },

and the error FINALLY WENT AWAY! Thank you! The error message has to be wrong.

**Comment by shawngustaw** [comment]
> for anyone who still find solution Note: I'm running `MacOS 10.15.7 (19H114)`
> 
> first download react-native-debugger. **Then you must open it at least 1 time**
> 
> ```shell
> npm i -g asar
> asar e /Applications/React\ Native\ Debugger.app/Contents/Resources/app.asar /tmp/app
> cd /tmp/app
> 
> # option 1
> npm install react-devtools-core@^4 # or 4.22.1
> 
> ## option 2
> ## If you still unlucky, try edit `/tmp/app/package.json` as photo below, then execute next line
> # npm update react-devtools-core
> 
> # last step
> asar p . /Applications/React\ Native\ Debugger.app/Contents/Resources/app.asar
> ```
> 
> ![image](https://user-images.githubusercontent.com/32500015/147460092-2e47060c-75fa-4ecb-93fd-391232427274.png)

This worked for me. Thank you!

**Comment by alexlukelevy** [comment]
For npm, simply add 

```json
"overrides": {
    "react-devtools-core": "4.14.0"
},
```

**Comment by zn7726** [comment]
> Why is every comment suggesting to pin to something like `4.14.0` when the error message says `<4.11`? Is the error message wrong and the requirement is rather `>4.11`?
> 
> I'm really confused by this error message.

You asked the question that I was confused with after reading all these comments and how ppl reporting solutions are working!

the error message seemed to me mean that RND was expecting react-devtools with version <4.11 but a higher version is always used. With that impression in mind, I have been trying to link an earlier version of react-devtools-core to the app, including by adding the resolution clause in the package.json. I checked the globally installed react-devtools in yarn and npm and made sure they are all of version 4.10.4, specify the version 4.10.4 in the resolution clause and etc. but non worked. Of course those changes won't be helpful because the direction was wrong!

Once I changed the resolution section to specify the react-devtools-core to 4.14.0, ran yarn, and restarted the app, wow, all working now!

**Comment by garawaa** [comment]
I just edited my package.json file like below:
In first line of defendencies block added
    "react-devtools": "~4.14.0",
    "react-devtools-core": "~4.14.0",
**For examle:**
```
  "dependencies": {
    "react-devtools": "~4.14.0",
    "react-devtools-core": "~4.14.0",
    "react": "17.0.2",
    "react-native": "0.68.2"
  },
```
And added 
```
  "resolutions": {
    "react-devtools-core": "4.14.0"
  },
```
before last code block:
```
  "resolutions": {
    "react-devtools-core": "4.14.0"
  },
  "jest": {
    "preset": "react-native"
  }
```
If you are using yarn, delete yarn.lock file and run yarn install
if you are using npm, delete package-lock.json file and run npm install
Enjoy!

**Comment by karlhorky** [comment]
Seems like https://github.com/jhen0409/react-native-debugger/pull/706 is the PR to fix this by upgrading `react-devtools-core` in `react-native-debugger`.
