### ISSUE TITLE
[Feature Request] Apple Silicon native build

### ISSUE THREAD

**Issue by alexyangjie** [jhen0409/react-native-debugger#624]
Is there any plan to have an Apple Silicon native build on the newer m1 macs? It will bring much improved performance and lower memory footprint on these macs.

Thanks for the great work!

**Comment by jhen0409** [comment]
#592 did it.

Currently I’m stuck in the Developer ID Application cert issue (My backup is missing..), so I have to wait for Apple to reply before I can use codesign to release the app.

**Comment by alexyangjie** [comment]
@jhen0409 It seems the latest release is still only for Intel. Any plan to have the universal binary?

**Comment by jhen0409** [comment]
Sorry for close that. The universal binary may land in v0.12.1.

**Comment by jhen0409** [comment]
Provided in [v0.12.1](https://github.com/jhen0409/react-native-debugger/releases/tag/v0.12.1).
