### ISSUE TITLE
Confirming signature change

### ISSUE THREAD

**Issue by vitorgalvao** [jhen0409/react-native-debugger#629]
Up to (and including) [release 0.11.9](https://github.com/jhen0409/react-native-debugger/releases/tag/v0.11.9), the macOS app signature was `Jhen Jie Hong (C6EUM5DVB3)`. In [0.12.0](https://github.com/jhen0409/react-native-debugger/releases/tag/v0.12.0), it changed to `FUGOOD CORP. (Q5AB6DLD5L)`.

Just checking if that was an intentional / legitimate change.

Thank you.

**Comment by jhen0409** [comment]
> Just checking if that was an intentional / legitimate change.

Yes. I changed to use team ID.
