### ISSUE TITLE
Default debugger opens in chrome tab after upgrading to RN 0.43.4

### ISSUE THREAD

**Issue by aranda-adapptor** [jhen0409/react-native-debugger#65]
Prior to upgrading RN from 0.42.0 to 0.43.4, React Native Debugger would open when the project was launched or debugging was enabled. After the upgrade, I just get the default debugger.

React Native Debugger version: 0.6.4
React Native version: ^0.43.4
Platform: tested iOS simulator, Android device
Operating System: macOS

**Comment by jhen0409** [comment]
Try [examples](https://github.com/jhen0409/react-native-debugger/tree/master/examples) if you mean [`debugger-open`](https://github.com/jhen0409/react-native-debugger/tree/master/patch) not work, currently it also used RN 0.43.4, or you can just try to run `$(npm bin)/rndebugger-open` again.

**Comment by aranda-adapptor** [comment]
Thanks for the tips. After restarting macOS it seems to be working again.
