### ISSUE TITLE
Network Request Failed Error

### ISSUE THREAD

**Issue by farhanghazi97** [jhen0409/react-native-debugger#664]
React Native Debugger app version: 0.12.1
React Native version: 0.64.3
Platform: Android
Is real device of platform: Testing via Android Emulator
Operating System: Linux

I'm using expo with React Native Debugger. I've configured Expo to use React Native Debugger. I did this by changing the default React Native Debugger port to point to the expo debugger port. I've confirmed that this works since React Native Debugger successfully connects to my expo application.

The issue arises when I try and make network requests. I have set RNDebugger to boot with network inspect enabled (via config file). Any outbound requests that I try and make over LOCALHOST throws an error. During development, I have my expo application set  to query a separate backend server running on localhost. No requests over localhost go through. Instead, React Native Debugger picks up the requests and my expo application logs the following error:

```Network request failed
at file:///usr/lib/react-native-debugger/resources/app.asar/js/RNDebuggerWorker.js:2:78011 in XMLHttpRequest.a.onerror
Error: ENOENT: no such file or directory, open 'file:///usr/lib/react-native-debugger/resources/app.asar/js/RNDebuggerWorker.js'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at getCodeFrame (/home/farhan/Desktop/DTEX-Mobile/node_modules/metro/src/Server.js:1296:18)
    at /home/farhan/Desktop/DTEX-Mobile/node_modules/metro/src/Server.js:1367:24
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/farhan/Desktop/DTEX-Mobile/node_modules/metro/src/Server.js:146:24)
    at _next (/home/farhan/Desktop/DTEX-Mobile/node_modules/metro/src/Server.js:168:9)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Network request failed
at file:///usr/lib/react-native-debugger/resources/app.asar/js/RNDebuggerWorker.js:2:78011 in XMLHttpRequest.a.onerror
```

Upon further investigation, after turning off remote debugging and disconnecting from RNDebugger, my requests still do not go through. I get the following error:

```
Network request failed
at node_modules/whatwg-fetch/dist/fetch.umd.js:535:17 in setTimeout$argument_0
```

I really don't know what this error means and it does not point me towards anything application-specific that might be going wrong. Any help / advice would be appreciated. Thanks!

**Comment by afilp** [comment]
@farhanghazi97 I have the same problem, how did you fix it please?

It seems to be happening with requests to SVG assets:

![image](https://user-images.githubusercontent.com/7850073/159373657-7d3928d8-eeeb-46fd-9601-75040e014d10.png)

At `10.0.2.2:8081` (Android emulator)

![image](https://user-images.githubusercontent.com/7850073/159373711-65e6985f-28de-4ee0-806f-9f71cd8c8903.png)

**Comment by afilp** [comment]
@farhanghazi97 Do you or anybody else has an answer to this? Thanks!

**Comment by farhanghazi97** [comment]
> @farhanghazi97 Do you or anybody else has an answer to this? Thanks!

Mate, the issue seems to persist still. I have since then moved away from the particular React Native project so havent really attended to it.
