### ISSUE TITLE
See also:  API Reference link navigates to ... porn site

### ISSUE THREAD

**Issue by footios** [jhen0409/react-native-debugger#666]
React Native Debugger app version: [FILL THIS OUT]
React Native version: [FILL THIS OUT]
Platform: [FILL THIS OUT: iOS, Android, ...]
Is real device of platform: [Yes or No]
Operating System: [FILL THIS OUT: macOS, Linux, Windows]

**Comment by jhen0409** [comment]
It seems to be related to https://github.com/reduxjs/redux-devtools/issues/903. Fixed by 3211e13fef2c431b6b6f38cd778e36e7ee845d3a.
