### ISSUE TITLE
Slow AsyncStorage reading

### ISSUE THREAD

**Issue by matpaul** [jhen0409/react-native-debugger#68]
React Native version: [0.43.4]
Platform: [IOS], Simulator
Operating System: [macOS]

Hello, in my app i use AsyncStorage.(get/set)Item Module for profile save (object with ~100 props)

Using RND: verry slow reading so in my case around 3-5 seconds 
Using Chrome:  normal 0.4-0.7 seconds

Any suggestions for fix it, really like this awesome debugger)
Thanks!

**Comment by matpaul** [comment]
Sorry) found that chrome use e+3 in console.time =)

**Comment by zhenizhui** [comment]
@matpaul hello, i use AsyncStorage too. And it was slow when i debugger with `react-native-debugger`.

What does `e+3` mean?

**Comment by matpaul** [comment]
@zhenizhui browser show me timings * 1000 =)
as i remember slow asyncStorage was by default in (chrome/react native debugger)
not only in RND
