### ISSUE TITLE
react-naive-debugger-start doesn't work with expo

### ISSUE THREAD

**Issue by eladgoeuro** [jhen0409/react-native-debugger#689]
1) run `yarn` 
    PASS Replace `open debugger-ui with Chrome` to `open React Native Debugger` message received
2) run `expo start` and Enable Debug JS Remotely
    debugger-ui chrome is opened instead of the Native Debugger
3) run `find . -name  "getDevToolsMiddleware.js" `
6) No results

Note : running `$ REACT_DEBUGGER="rndebugger-open --open --expo" expo start` does work.

 Expo CLI 5.2.0 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.5.1 - ~/.nvm/versions/node/v16.13.2/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7199119
      Xcode: 12.5/12E262 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: 9.0.2 => 9.0.2
      expo: ^44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      eas-cli: 0.47.0
      expo-cli: 5.2.0
    Expo Workflow: managed

**Comment by hoIIer** [comment]
Any update? Trying to use this with expo and it's not working.

**Comment by adscud** [comment]
+1 with Expo 47

**Comment by adamblvck** [comment]
Can confirm that EAS builds (development) don't connect to React Native Debugger, after following documentation, manual port selection in UI, and trying every sensible host/port combination by doing a cli launch.

**Comment by medimachina** [comment]
I'm having the same problem, I think. I start React Native Debugger and run my expo app on a simulated android device (all on Windows 11). Both are on the same port. Still, starting the JS debugging launches a separate chrome dev tools window (which is also separate from any browser). Does anyone have a solution? Can I manually force it to use React Dev Tools instead?

**Comment by Aravindan07** [comment]
I am also facing the same problem with Expo SDK 48. Any solutions yet?

**Comment by medimachina** [comment]
For people with this problem. I posted the question here and also answered it myself later. The answer contains the reason it doesn't work, a way to "kind of" make it work and a reason why it is better not to use it at the moment, unfortunately. I hope this helps you! @Ricka7x and @Aravindan07 

https://stackoverflow.com/questions/76098915/expo-js-debugger-connects-to-chrome-instead-of-react-native-debugger

**Comment by wflanagan** [comment]
Ugh. +1 on this issue as well. These issues make troubleshooting a redux-based app pretty friggin horrendous right now.

**Comment by jhen0409** [comment]
I've removed the `--expo` flag due to the `packager-info` is no longer supported. You can use `--port 19000` instead. (Depends on your Expo packager used port)
