### ISSUE TITLE
show in source (with babel plugin) has this error: "Uncaught TypeError: Cannot convert undefined or null to object"

### ISSUE THREAD

**Issue by faceyspacey** [jhen0409/react-native-debugger#69]
```
Uncaught TypeError: Cannot convert undefined or null to object
    at Function.from (native)
    at _toArray (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/build/standalone.js:14797:49)
    at launchEditor (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/build/standalone.js:14852:63)
    at Object.showElementSource (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/build/standalone.js:92:13)
    at /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/build/standalone.js:293:34
```

It fails on the first line here (`Array.from(arr)`):

```js
function _toArray(arr) { return Array.isArray(arr) ? arr : Array.from(arr); }
	
var fs = __webpack_require__(2);
var path = __webpack_require__(3);
var child_process = __webpack_require__(260);
var shellQuote = __webpack_require__(261);
	
function isTerminalEditor(editor) {
	switch (editor) {
	    case 'vim':
	    case 'emacs':
	    case 'nano':
	      return true;
	}
	return false;
}	
```

I have the babel plugin set:

```json
{
  "presets": ["react-native"],
  "plugins": ["transform-react-jsx-source"]
}
```

The source filename and line number correctly shows in the standalone debugger app, but the link doesn't open (it has the above error). I'm using VSCode.

React Native version: 44
Platform: iOS
Is real device of platform: NO
Operating System: macOS

**Comment by faceyspacey** [comment]
Also, I tried running `react-native run-ios` from the VSCode terminal and I get the same issue. 

I'm doing your standard `postinstall` process. Everything was so automated and works so perfectly. AMAZING JOB!!!! This is the best!

**Comment by jhen0409** [comment]
It looks like [`guessEditor`](https://github.com/facebook/react-devtools/blob/master/packages/react-devtools-core/src/launchEditor.js#L74) returns `null`, it meaning your VSCode app is not in [`common path`](https://github.com/facebook/react-devtools/blob/master/packages/react-devtools-core/src/launchEditor.js#L38)?

You can run `process.env.REACT_EDITOR = 'your_editor_path'` in devtools console (`top` context), then try click `Show <> in source`. Maybe we can provide a better way for set `REACT_EDITOR`. :)

Also we should avoid the error, maybe just change [this line](https://github.com/facebook/react-devtools/blob/master/packages/react-devtools-core/src/launchEditor.js#L104) to `return []`.

**Comment by jhen0409** [comment]
__UPDATE:__ We should use `process.env.EDITOR = 'the_editor_path'`, the `REACT_EDITOR` will be parsed by `shell-quote`.

**Comment by jhen0409** [comment]
Fixed in https://github.com/jhen0409/react-native-debugger/commit/289efab9ce880a24e99e9895ff7ccc05c195bea1 and release as [`v0.7.1`](https://github.com/jhen0409/react-native-debugger/releases/tag/v0.7.1). It should work as I just migrated to VSCode. :)
