### ISSUE TITLE
I can't find Enable Network Inspect button in React Native Debugger IDE on Macos m1

### ISSUE THREAD

**Issue by duonghoangphong** [jhen0409/react-native-debugger#696]
<img width="1031" alt="Screen Shot 2022-04-05 at 16 43 33" src="https://user-images.githubusercontent.com/57445189/161726753-ba98d397-e581-439f-9b2b-63424dae3953.png">

**Comment by hoondeveloper** [comment]
+1

**Comment by duonghoangphong** [comment]
Have to update to the new version to have that feature
