### ISSUE TITLE
toggle developer tools doesn't work - ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by iArchin** [jhen0409/react-native-debugger#700]
it connect to debugger without any problem but when I'm trying to open developer tools to see network, console. etc I can't open the developer tools tab. toggle developer tools doesn't do anything

React Native Debugger app version: 0.12.1
React Native version: 0.63.4
Platform: Android
Is real device of platform: No
Operating System: Ubuntu 22.04 LTS

**Comment by valeri-terziyski** [comment]
I have the same problem

**Comment by iArchin** [comment]
> I have the same problem

any idea?

**Comment by valeri-terziyski** [comment]
Nope, tried many things (including other version), but unfortunately no luck so far.

**Comment by renomi** [comment]
I had a similar problem after upgrade Ubuntu 22.04.  As a temporary workaraound, i have to run the file  from the compressed version (rn-debugger-linux-x64.zip), by executing react-native-debugger with the --no-sandbox parameter. Like this:
`react-native-debugger --no-sandbox`

**Comment by joulgs** [comment]
I managed to make the installed version work by changing its shortcut with @renomi's tip :

´/usr/share/applications/react-native-debugger.desktop´

´Exec=react-native-debugger --no-sandbox %U´

**Comment by JoshBot-Debug** [comment]
Same problem here, using "react-native-debugger --no-sandbox" works.

**Comment by LYevhen** [comment]
I have same problem but with MacOs Monterey

**Comment by andrii-petlovanyi** [comment]
> 

Hi! Can you fixed this problem on your Mac?

**Comment by jhen0409** [comment]
The issue for Linux should fixed by [v0.14.0](https://github.com/jhen0409/react-native-debugger/releases/tag/v0.14.0) (bumped Electron version). I've confirmed with Ubuntu 22.04.

**Comment by brianaderer** [comment]
I'm on Windows 11 so the --no-sandbox flag doesn't work for me. What did work was to simply open another instance of the program on top of an already running one, and then close the first. DevTools are back
