### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by DannyBiezen** [jhen0409/react-native-debugger#713]
Hi @jhen0409, thanks a lot for creating such a great project!

I've ran into a few issues using this project and I noticed the last release was just over a year ago. Could you tell me if you plan to create new releases for this project (such as #706)? 

Either way, thanks a lot for creating this, it has saved me a lot of time already :)

**Comment by jhen0409** [comment]
Sorry for delay. I will plan for the next release.
