### ISSUE TITLE
how to debug the RN>=68 version

### ISSUE THREAD

**Issue by jgx-jay** [jhen0409/react-native-debugger#714]
React Native Debugger app version: [FILL THIS OUT]
React Native version: [FILL THIS OUT]
Platform: [FILL THIS OUT: iOS, Android, ...]
Is real device of platform: [Yes or No]
Operating System: [FILL THIS OUT: macOS, Linux, Windows]

**Comment by karlhorky** [comment]
Looks like this PR will address this: https://github.com/jhen0409/react-native-debugger/pull/706

**Comment by jhen0409** [comment]
v0.13.0 is now available.

**Comment by karlhorky** [comment]
Thanks so much @jhen0409 !! 🙌

**Comment by psionic12** [comment]
@jhen0409 Does this version (v0.13.0) support fabric debugging?
