### ISSUE TITLE
VM334 standalone.js:48 [React DevTools] Error calling listener 

### ISSUE THREAD

**Issue by JWESTMA2** [jhen0409/react-native-debugger#715]
React Native Debugger app version: 0.11.0-beta-4
React Native version: 0.69.3
React Devtools version: 4.6.0-6cceaeb67
Platform: iOS
Is real device of platform: No
Operating System: macOS

When I open react native debugger, react devtool connects but I the console is empty.
I get the following error in the developer tools console after React Devtools has connected:

VM334 standalone.js:48 [React DevTools] Error calling listener {event: "operations", payload: Array(1432)}

**Comment by matthewstyers** [comment]
I ran into this as well and was able to resolve by updating the `react-devtools-core` version override from `4.14.0`, which was the recommended version when I initially set up the integration, to `~4.25.0`, per the current [doc](https://github.com/jhen0409/react-native-debugger/blob/master/docs/react-devtools-integration.md#question-i-got-unsupported-message-from-react-devtools).

This may not be a universal solution, but it did resolve the issue in my case.

**Comment by jhen0409** [comment]
The react-devtools-core issue already mentioned in documentation.
