### ISSUE TITLE
how to debug Fabric

### ISSUE THREAD

**Issue by jgx-jay** [jhen0409/react-native-debugger#720]
React Native Debugger app version: [FILL THIS OUT]
React Native version: [FILL THIS OUT]
Platform: [FILL THIS OUT: iOS, Android, ...]
Is real device of platform: [Yes or No]
Operating System: [FILL THIS OUT: macOS, Linux, Windows]

**Comment by jhen0409** [comment]
Sorry for being late, I'll close this first. I created a new discussion about this, if you want to know any news about Hermes debugger support (related JSI / Fabric / New Architecture) in RNDebugger, you can follow https://github.com/jhen0409/react-native-debugger/discussions/774. Also, any help or advice would be appreciated.
