### ISSUE TITLE
Apollo devtools tab not showing

### ISSUE THREAD

**Issue by matomesc** [jhen0409/react-native-debugger#721]
React Native Debugger app version: [0.13.0]
React Native version: [0.69.5]
Platform: [Android]
Is real device of platform: [No]
Operating System: [Windows]

I'm trying to access the apollo client devtools but the `Apollo` tab is not showing in the debugger. Toggling the devtools doesn't work. I'm using `@apollo/client` version 3.6.9.

**Comment by Jonatthu** [comment]
Did you configure apollo client with connectToDevTools: true?
