### ISSUE TITLE
How to open Redux and console panes?

### ISSUE THREAD

**Issue by alexey-kuznetsov** [jhen0409/react-native-debugger#743]
React Native Debugger app version: 4.27.1
React Native version: 0.70.6
Platform: Android
Is real device of platform: No
Operating System: Windows 11

I  cant see in devtools console and redux panes. Interface has anly component tree and component info panes. How to display console and redux devtools?

This is how my debugger looks now:
![image](https://user-images.githubusercontent.com/17800898/212832466-dc9422b1-7b75-4984-9a0d-130f1f1a45f5.png)

**Comment by kalisoft93** [comment]
Same here

**Comment by kalisoft93** [comment]
Oke I got the solution in other issue ticket, please try to run with this command react-native-debugger --no-sandbox

**Comment by jhen0409** [comment]
As I understand in the issue description, I think you're using a wrong app. Also we don't provided React DevTools v4.27 in this app.
