### ISSUE TITLE
[RN 0.44][Android] Expected to run on UI thread

### ISSUE THREAD

**Issue by laclance** [jhen0409/react-native-debugger#76]
Since the last update every time I reload my app i get the error `Expected to run on UI thread.`
I have to stop remote debugging and start again every time.

"react": "16.0.0-alpha.6",
"react-native": "0.44.0",
Android API 21 (Device),
Android API 25 (Simulator),
Mac OSX Sierra,

**Comment by jhen0409** [comment]
That's true :\\, it looks like related to React Native (`/debugger-ui` have the same issue), but I tried 0.45-rc0 is works fine 🎉, would be better if you could file an issue to official repo.

I can keep this issue open for let more users know.

**Comment by laclance** [comment]
Sorry which do you mean by the official repo, react-devtools? I also made this one 
[https://github.com/facebook/react-devtools/issues/708 ](url)

**Comment by jhen0409** [comment]
The `Expected to run on UI thread` error looks not related to `react-devtools`, I've tried on the official debugger (`react-devtools` is not launched), but it doesn't always happen.

**Comment by naoyamakino** [comment]
+1 this, I am getting the same issue. any ideas?

**Comment by jhen0409** [comment]
@naoyamakino React Native 0.45-rc works fine I tried, we can waiting for release of next month, or downgrade to v0.43.

**Comment by fabien-h** [comment]
I have the same issue since this morning.

Do you think it has to do with useNativeDriver in animations ?

    react-native-git-upgrade 0.45-rc0
    ...
    Error: The specified version of React Native 0.45-rc0 doesn't exist.

What's the syntax ?

**Comment by jhen0409** [comment]
@fabien-h The correct rc version format for upgrade is `0.45.0-rc.2`.

**Comment by fabien-h** [comment]
Thank you.

BTW, did that and now I have a react-native svg issue :)

    Execution failed for task ':react-native-svg:compileReleaseJavaWithJavac'.

But it seems that it solved the issue with the UI thread thing.

**Comment by jhen0409** [comment]
Closing this because RN v0.45 is released.

**Comment by deepupathak** [comment]
+1 to this, I am getting the same issue. any ideas?

react-native: 0.48.3
windows 10 64 bit

**Comment by jhen0409** [comment]
@deepupathak maybe related to https://github.com/facebook/react-native/issues/15915?
