### ISSUE TITLE
Devtool dosen't work with Expo on Ubuntu 20.04

### ISSUE THREAD

**Issue by thoanghung** [jhen0409/react-native-debugger#761]
I'm using Expo to run app on my Iphone. Every time I enable debugger, it always open chrome default Devtools instead of RNDebugger. Althought RNDebugger already listenning on port 19000. 

React Native Debugger app version: 0.13.1
React Native version: 0.71.8
Platform: IOS
Is real device of platform: Yes
Operating System: Ubuntu 22.04 LTS

**Comment by flexbox** [comment]
Hey @thoanghung 

with expo SDK 47+ the JavaScript engine by default is Hermes
And right now there is no support for it #573

If your problem is solved can you please close the issue? 
It sparks joy for maintainers ✨

**Comment by jhen0409** [comment]
Sorry for being late, I'll close this first. I created a new discussion about this, if you want to know any news about Hermes debugger support (related JSI / Fabric / New Architecture) in RNDebugger, you can follow https://github.com/jhen0409/react-native-debugger/discussions/774. Also, any help or advice would be appreciated.
