### ISSUE TITLE
[Discussion] Future plan for RND (Expo 49+)?

### ISSUE THREAD

**Issue by maichongju** [jhen0409/react-native-debugger#765]
As for today, the Expo 49 beta is available for download. In their [changed log](https://blog.expo.dev/expo-sdk-49-beta-is-now-available-6373e78f8624) it stated `Remote debugging for JSC is disabled in Expo Go and expo-dev-client`, which means we won't able to use the JSC work around with the newer version. 

Will this project continue to update with the new change along with Expo?

**Comment by AJTJ** [comment]
this.

I've updated to the newest SDK (49) and I'm struggling to get Apollo information.

**Comment by jhen0409** [comment]
I guess Expo 49 has some reason to hide remote debugging option for JSC, there might be some functionality to start using blocking native method or JSI by default. You can still call `NativeModules.DevSettings.setIsDebuggingRemotely(true)` to enable it, but it may have some problems.

I'm start planning for new debugger support on this project, ou can follow #774, but it probably not works on JSC, only for Hermes or RNV8.

**Comment by AJTJ** [comment]
> 
I haven't been able to set `NativeModules.DevSettings.setIsDebuggingRemotely(true)` and get this working in expo managed workflow. Have you?

**Comment by ser-emejia** [comment]
> > 
> 
> I haven't been able to set `NativeModules.DevSettings.setIsDebuggingRemotely(true)` and get this working in expo managed workflow. Have you?

Hello, did you find a solution?

**Comment by losh11** [comment]
@AJTJ @ser-emejia someone has created a new package called [react-native-devsettings](https://www.npmjs.com/package/react-native-devsettings?activeTab=readme) which lets you re-enable the settings for remote debugger, which let you attach this debugger.
