### ISSUE TITLE
Console window issue

### ISSUE THREAD

**Issue by zeeshan7143** [jhen0409/react-native-debugger#766]
I am using latest version of Debugger
but console window is not  shown 

below screenshot attached

![Screenshot from 2023-07-03 12-05-14](https://github.com/jhen0409/react-native-debugger/assets/56158308/7a33fc2f-40ca-4ee2-a562-09bb4d41b465)

**Comment by enuelmorales-bullmarket** [comment]
Same issue on Linux

**Comment by vntech-engineering93** [comment]
Same issue on Ubuntu 22.04

**Comment by enuelmorales-bullmarket** [comment]
@vntech-engineering93 @saschati Hi guys I fix this issue on Linux Ubuntu 🙌 check this comment please https://github.com/jhen0409/react-native-debugger/issues/700#issuecomment-1138523135

**Comment by jhen0409** [comment]
The devtools issue should fixed by [v0.14.0](https://github.com/jhen0409/react-native-debugger/releases/tag/v0.14.0) (bumped Electron version). I've confirmed with Ubuntu 22.04.

**Comment by vntech-engineering93** [comment]
Thanks @jhen0409 and the team, It's working for 22.04 on v0.14.0.  Amazing..
