### ISSUE TITLE
How to turn off auto focus of UI window on reload?

### ISSUE THREAD

**Issue by zubko** [jhen0409/react-native-debugger#77]
React Native version: 0.44
Platform: iOS
Is real device of platform: No
Operating System: OS X El Capitan
React Native Debugger 0.6.5

React Native Debugger intercepts the focus and brings itself to front each time I save a file in a text editor while Live Reload is enabled. So I need to go back to the editor each time. This is very frustrating. Can I somehow turn it off?

I'm running debugger through command:
REACT_DEBUGGER=\"open 'rndebugger://set-debugger-loc?port=8081' ||\" yarn start

**Comment by jhen0409** [comment]
The `open` command will focus the app by default, we can use `-g` flag to avoid.

```bash
$ REACT_DEBUGGER="open -g 'rndebugger://set-debugger-loc?port=8081' ||" yarn start
```

Would be good if we also have this in [`npm package`](https://github.com/jhen0409/react-native-debugger/tree/master/npm-package). :)
