### ISSUE TITLE
Unable to enable network debugging, unable to debug Api

### ISSUE THREAD

**Issue by lllomh** [jhen0409/react-native-debugger#784]
After running, the network monitor cannot be turned on, and clicking to turn it on is invalid. As shown below：

![image](https://github.com/jhen0409/react-native-debugger/assets/20123291/9c86c487-4366-4c71-a262-c89bf050b308)

When after sending an axios request, the request record cannot be seen here. Why is this?
![image](https://github.com/jhen0409/react-native-debugger/assets/20123291/d161adba-b018-4ea4-8308-e51ce6760a82)

React Native Debugger app version: ![image](https://github.com/jhen0409/react-native-debugger/assets/20123291/40e0bc7d-92ee-439d-bf7a-a311b709ee42)
React Native version:    "react-native": "0.72.3"
Platform: [FILL THIS OUT: Android]
Is real device of platform: [ No]
Operating System: [FILL THIS OUT: Windows 10]

**Comment by rafauke** [comment]
Have you tried controlling the default behaviour for network inspect through `.rndebuggerrc`?

```jsonc
{
  // ...
  // Enable Network Inspect by default
  // See https://github.com/jhen0409/react-native-debugger/blob/master/docs/network-inspect-of-chrome-devtools.md
  defaultNetworkInspect: true,
}
```

**Comment by lllomh** [comment]
> Have you tried controlling the default behaviour for network inspect through `.rndebuggerrc`?
> 
> ```js
> {
>   // ...
>   // Enable Network Inspect by default
>   // See https://github.com/jhen0409/react-native-debugger/blob/master/docs/network-inspect-of-chrome-devtools.md
>   defaultNetworkInspect: true,
> }
> ```

Hello, I found the reason. Have to turn on debug mode in the emulator to be able to grab the request, thanks!
I think this issue can be closed now. Thank you！
