### ISSUE TITLE
At a high level how does React Native Debugger connect to an app?

### ISSUE THREAD

**Issue by jorgecolonconsulting** [jhen0409/react-native-debugger#786]
Thank you for this great tool. Wanted to reach out because I'm having intermittent issues with iOS connecting to the React Native Debugger. Sometimes it works and sometimes is doesn't. I can't get a grip on why. Sometimes it connects to the React Native Debugger, while sometimes it just launches the debugger in Chrome. On Android I can't even get a full debugger connection. At best, it'll open up in Chrome and say "Waiting". 

I have a feeling sometimes something is being cached, because sometimes after blowing away my node_modules and Pods and reinstalling everything it seems to connect again in React Native Debugger. But I can't prove it either.

At a high level could you describe how all the pieces fit together to make a full debugger connection?

I think this will help everyone that's having more complex issues connecting to the debugger.

Some questions that I'm trying to figure out:

* What are all of the services and ports involved? What runs where?
* How does devtools know whether to launch Chrome or allow React Native Debugger to connect? (because sometimes React Native Debugger is open and Chrome _still_ gets launched)
* What would cause a connection to try to open Chrome vs trying to open it in React Native Debugger?
* How does the debugger communicate with React Native Debugger?
* What needs to happen and in what specific order so that a full debugger connection can be successful?

React Native Debugger app version: 0.13.0
React Native version: 0.66.5
Platform: iOS and Android (Android is worse)
Is real device of platform: No
Operating System: MacOS
Package resolutions set to

```
"react-devtools-core": "~4.25.0"
```

**Comment by jhen0409** [comment]
RNDebugger will try to connect RN debugger proxy via WebSocket. (`/debugger-proxy`, default port is 8081)

If you haven’t use the [react-native-debugger-open](https://github.com/jhen0409/react-native-debugger/tree/master/npm-package) or set REACT_DEBUGGER env, the RN packager will attempt to launch Chrome if the current proxy does not have any connections.

If you see the `Waiting for client connection` title in RNDebugger, this means it is connected to the debugger proxy, at this time it should not try to launch Chrome.

Please note that you cannot have two or more connections to the same debugger proxy.

For how the debugger connecting to the debugger proxy, you can read:
- react-native-debugger: [app/middlewares/debuggerAPI.js](https://github.com/jhen0409/react-native-debugger/blob/master/app/middlewares/debuggerAPI.js)
- `@react-native-community/cli-debugger-ui`: [src/ui/index.js](https://github.com/react-native-community/cli/blob/v11.3.7/packages/cli-debugger-ui/) (should be used in Chrome)

**Comment by jorgecolonconsulting** [comment]
@jhen0409 This really helped a lot thank you! I finally found out why sometimes React Native Debugger wouldn't connect to the debugger proxy. For whatever reason it seems like debugger proxy was bound to the "unspecified IPv6 address" (i.e. ::) and the debugger proxy was trying to call the IPv4 address 127.0.0.1. Just specified the --host parameter in `npx react-native start --host 127.0.0.1` and everything was working after that.
