### ISSUE TITLE
[Feature]: Trim long variable content and show full content optionally

### ISSUE THREAD

**Issue by blaues0cke** [jhen0409/react-native-debugger#83]
For reasons I have to store a "huge" base64 encoded image in my state for a few actions until the image is removed again. If I want to debug the related reducer to see the content of another property beside this image property, I have to scroll through the whole base64 string since its displayed in full length.

![2017-05-24 09_52_01](https://cloud.githubusercontent.com/assets/5159398/26392367/a82a73f2-4066-11e7-854b-7016d2df5133.gif)

Would be nice to have something like a "max string length" feature (obviously this value can be very high, e.g. 2048 characters or so) since its only annoying when you have that much content like in my case.

**Comment by jhen0409** [comment]
Would be better to make a feature request to [`redux-devtools-log-monitor`](https://github.com/gaearon/redux-devtools-log-monitor).

We also have workaround to avoid long content for Redux DevTools Extension API, see [the documentation](https://github.com/zalmoxisus/redux-devtools-extension/blob/f8fdf91120d2e4fff32e2da831d4e04c2e6aec76/docs/API/Arguments.md), we can use `sanitizer` or `toJSON` to replace long content by custom content for show action / state on the devtools, it doesn't affect the original state.

**Comment by blaues0cke** [comment]
@jhen0409 Thanks, tried both ways. The `stateSanitizer` actually **does** change the state, but the `toJSON` function is perfect for that case! :-)
