### ISSUE TITLE
Switching Chrome devtools theme requires restart

### ISSUE THREAD

**Issue by frantic** [jhen0409/react-native-debugger#87]
When changing theme settings here, I need to restart RN debugger for them to be applied.

![image](https://cloud.githubusercontent.com/assets/192222/26644669/5d860d96-45ea-11e7-881a-383e52e293ef.png)

** Please ensure:

- [x] I'm using the latest version of react-native-debugger (0.7.0)
- [x] I have read [README.md](https://github.com/jhen0409/react-native-debugger/blob/master/README.md)

** Please provide the following information if you found some bugs or have question:

Operating System: macOS

**Comment by jhen0409** [comment]
It seems to be an issue of Electron, for browser devtools it should automatically reload as expected.

Currently we can just toggle the devtools (cmd+option+i) twice instead of restart the RN debugger.

**Comment by Gongreg** [comment]
@jhen0409, I see that there is quite a lot of old issues, maybe issues like this one should be closed? This is just how electron works, on chrome when you change the theme it simply reopens the tab so you don't have to do it manually.

This is not something that we should work on.
