### ISSUE TITLE
In IOS console.log has been mysteriously filtered without any filter applied

### ISSUE THREAD

**Issue by ApolloTang** [jhen0409/react-native-debugger#90]
- [x] I'm using the latest version of react-native-debugger
- [x] I have read [README.md](https://github.com/jhen0409/react-native-debugger/blob/master/README.md)

React Native version: [0.7.0]
Platform: [iOS]
Is real device of platform: [No]
Operating System: [macOS]

When debugging on ios, some **mysterious filtered** has been applied, as the result non of my console.log is shown.  

This happen suddenly, and only in ios. (please see image attached) 
 
![react-native-debugger-bug](https://cloud.githubusercontent.com/assets/1150961/26787068/b9ea5534-49d6-11e7-848b-c7c50c8b6e83.gif)

**Comment by jhen0409** [comment]
Could you check the console setting, are you selected the `Selected context only` checkbox?

<img width="666" alt="2017-06-05 10 10 03" src="https://cloud.githubusercontent.com/assets/3001525/26787363/5364a45c-4a3c-11e7-9d91-ab2974171e14.png">

If true, you should selected `RNDebuggerWorker.js` context (refer to [this section](https://github.com/jhen0409/react-native-debugger/blob/master/docs/debugger-integration.md#get-global-variables-of-react-native-runtime-in-the-console) if you're confused) or unselected the checkbox.

It has some strange cases, such as the Android screenshot, and iOS still show two action log, so I'm not sure if this comment is helpful.

**Comment by ApolloTang** [comment]
Makes no different (see image attached)
Thanks for helping! 

![report 2](https://cloud.githubusercontent.com/assets/1150961/26789144/5ae4b186-49dd-11e7-94f2-610e19f257bc.gif)

**Comment by ApolloTang** [comment]
forget to mention above, in the third case, it is also with RNDebuggerWorker.js

**Comment by jhen0409** [comment]
I saw the one possibility is that you filtered all logs from `index.ios.bundle`:

<img width="829" alt="2017-06-06 3 48 38" src="https://cloud.githubusercontent.com/assets/3001525/26800364/993b1284-4a6b-11e7-9856-0f0aa9e935cf.png">

If you have do it please click `Unhide All`.

I don't know why the logs `redux-logger` haven't filtered fully, maybe it's a bug for custom formatter. 😂

**Comment by ApolloTang** [comment]
Well, It works now, I really can't explain how I fixed it, but I solve the problem by restart my computer twice! 

glad it works again. now I can continue my development.  thanks for taken the time to help.

**Comment by ilovett** [comment]
Thanks @jhen0409 -- oddly the only way I could unfilter was by right clicking and going to `Filter` in the dropdown menu... and NOT using any of the visible dropdowns 
![image](https://user-images.githubusercontent.com/1776100/36497297-c12fc18a-16ef-11e8-83a7-e9687625e0e8.png)

**Comment by Aggie123** [comment]
Came into the same problem here, console.log doesn't show in the console in ios simulator, any solutions?
