### ISSUE TITLE
Uncaught (in promise) ReferenceError: window is not defined

### ISSUE THREAD

**Issue by pvinis** [jhen0409/react-native-debugger#91]
I often get this error

![screen shot 2017-06-16 at 12 27 42](https://user-images.githubusercontent.com/100233/27223063-3e3f0134-528f-11e7-93d0-83b4936cd368.png)

and then i have no idea how to fix it. I just restart things until it works again.

React Native Debugger version: 0.7.0 from homebrew
React Native version: 0.44.2
Platform: iOS
Is real device of platform: Yes
Operating System: macOS

**Comment by jhen0409** [comment]
It might caused by [these lines](https://github.com/jhen0409/react-native-debugger/blob/master/app/worker/index.js#L55-L56), but I'm not sure because `importScripts` function is sync.

We could to attempting check until `window` is available for that.

**Comment by jhen0409** [comment]
Release as [`v0.7.1`](https://github.com/jhen0409/react-native-debugger/releases/tag/v0.7.1). Feel free to re-open this issue if it still doesn't work for you. :)

**Comment by pvinis** [comment]
seems to be fine now. hasnt happened yet. thanks :)
