### ISSUE TITLE
How to use with React Devtools?

### ISSUE THREAD

**Issue by alxvallejo** [jhen0409/react-native-debugger#92]
I can't seem to get React Devtools to work in parallel with RNDebugger. I simply want to inspect DOM elements, but Devtools just says Waiting for React to connect.

So in an effort to debug, I tried reverting the RNDebugger script in my package.json:

```
  "scripts": {
    "postinstall": "rndebugger-open --revert",
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "devtools": "react-devtools"
  },
```

But this doesn't seem to stop the Debugger from opening each time. How can I turn RNDebugger off?

**Comment by jhen0409** [comment]
Please provide more information for issue template asking.

I guess you're using Android, and the [adb util](https://github.com/jhen0409/react-native-debugger/blob/master/app/middlewares/debuggerAPI.js#L101) doesn't working for you?

**Comment by alxvallejo** [comment]
@jhen0409 I'm not using Android, i'm using iOS Simulator.

I've found that the issue stems from Remote JS Debugging. If I enable remote js debugging, the React Native Debugger fires and i can use that tool, but I can't inspect elements and play with the CSS.

If I turn off Remote JS Debugging, the React Native Debugger stops listening and the React-Devtools electron instance fires up, but the app itself fails to load with no errors reported.

So, really, i can only use iOS simulator when remote js debugging is turned on. That's all i know right now.

**Comment by jhen0409** [comment]
> If I turn off Remote JS Debugging, the React Native Debugger stops listening and the React-Devtools electron instance fires up, but the app itself fails to load with no errors reported.

Why the React inspector will fires up when you turn off Remote JS Debugging? It should be impossible, they should fires up together, as [the screenshot](https://cloud.githubusercontent.com/assets/3001525/26518164/0dc2c5fc-42dd-11e7-8bfa-eab4515ba050.png).

If you mean you're using [this package](https://github.com/facebook/react-devtools/tree/master/packages/react-devtools) and RNDebugger together, we have already built-in the inspector to RNDebugger and set [the random port](https://github.com/jhen0409/react-native-debugger/blob/master/app/containers/ReactInspector.js#L75), so it doesn't use `8097` port, and why you not use the RNDebugger built-in react-devtools?

**Comment by alxvallejo** [comment]
I don't get how to use the inspector in RNDebugger then, because it seems to not work with my device ...
<img width="515" alt="screen shot 2017-06-28 at 1 12 17 pm" src="https://user-images.githubusercontent.com/947203/27650647-80166048-5c03-11e7-94fc-05057919938c.png">

**Comment by jhen0409** [comment]
The `react-devtools` should in `redux-devtools` below as [the screenshot](https://cloud.githubusercontent.com/assets/3001525/26518164/0dc2c5fc-42dd-11e7-8bfa-eab4515ba050.png), you're using the elements inspector of browser (RNDebugger). Please open the React inspector:

* `CMD+OPTION+J`
* `View` -> `Toggle React DevTools` in application menu
* `Toggle React DevTools` in context menu

Close this issue because this is misunderstanding.

**Comment by alxvallejo** [comment]
Honestly you might want to update the documentation then, the documentation specifically links to https://github.com/facebook/react-devtools/tree/master/packages/react-devtools#integration-with-react-native-inspector

**Comment by jhen0409** [comment]
We have the same usage with [`Integration with React Native Inspector`](https://github.com/facebook/react-devtools/tree/master/packages/react-devtools#integration-with-react-native-inspector) section of `react-devtools` package, is it have something wrong? You should can see the React Native Inspector usage in [the screenshot](https://cloud.githubusercontent.com/assets/3001525/26518164/0dc2c5fc-42dd-11e7-8bfa-eab4515ba050.png).

**Comment by isbinge** [comment]
I just run my react native app in Android simulator,but can't  inspect elements in simulator,also in devtools 
![image](https://user-images.githubusercontent.com/29256678/35602684-91e9f57a-0674-11e8-90fa-f1b75b496742.png)

**Comment by isbinge** [comment]
So Why,have anyone give me a answer please ?
