### ISSUE TITLE
Failed to connect (to React)

### ISSUE THREAD

**Issue by bristoljon** [jhen0409/react-native-debugger#95]
React Native Debugger version: v0.7.1 (linux x64)
React Native version: 0.44.3
Platform: Android
Is real device of platform: emulated (Nexus 5x API 23)
Operating System: Ubuntu 16.10 64bit

When enabling `Debug JS Remotely` on device with latest RNDebugger open, the React section just says 'Connecting to React...' and after a few seconds I get `failed to connect` in console.

Redux seems to connect fine and I can see and dispatch actions in that window and console output from the app is there too.. Just missing React inspector.

![screenshot from 2017-06-28 15-35-18](https://user-images.githubusercontent.com/13088751/27642696-7b0f8b56-5c17-11e7-95ee-b4f23b5d9420.png)

**Comment by jhen0409** [comment]
Have you read [this section of troubleshooting](https://github.com/jhen0409/react-native-debugger/blob/master/docs/troubleshooting.md#react-inspector-get-stuck-at-connecting-to-react-for-rn-043-45)?

**Comment by bristoljon** [comment]
Ah yeah, sorry didn't see the troubleshooting page. Upgrading `react-devtools-core` from `2.0.1` to `2.3.3` fixed this.

`yarn upgrade react-devtools-core`
`rm -rf node_modules`
`yarn install`

Thanks @jhen0409 for quick response (and great debugger)

**Comment by gayancharith** [comment]
does this only works for mac os ?
