### ISSUE TITLE
Refused to set unsafe header in console log

### ISSUE THREAD

**Issue by buncismamen** [jhen0409/react-native-debugger#96]
there is this error in my console log and I don't know what causes this

![image](https://user-images.githubusercontent.com/14258779/27675782-8c8cc196-5cd5-11e7-82a3-03dc91fb865d.png)

and whenever I do console.log this error is happened again 
![image](https://user-images.githubusercontent.com/14258779/27675861-cc66c9ec-5cd5-11e7-8661-8990d5f8a396.png)

React Native Debugger version: [0.7.0]
React Native version: [^0.44.0]
Platform: [Android]
Is real device of platform: [Yes]
Operating System: [Linux]

**Comment by jhen0409** [comment]
It looks like you're enabled `Network Inspect`, so it will use XHR from WebWorker, it's different from the XHR implementation of RN, so we have to pay attention to some restrictions.

You need to track what requests use these headers.

**Comment by buncismamen** [comment]
yup, seems it's from my project configuration
upgrade it to react native 0.45/reinit the project then the error is gone

**Comment by andriichernenko** [comment]
I need to set `User-Agent` and `Cookie`, which are unsafe.
Tried it on a fresh React Native 0.45.1 project, got "Refused to set unsafe header" error anyway.

According to the standard (see step 5 [here](https://xhr.spec.whatwg.org/#the-setrequestheader()-method)) there are "forbidden" headers which cannot be set. There's no way around it (other than patching the browser).

**Comment by jhen0409** [comment]
We can follow #102 for implement our Network Inspect feature.

**Comment by jhen0409** [comment]
#118 will fix the problem of forbidden headers, I'll release it later.
